### ISSUE TITLE
When creating an index during deploy, you need to judge whether it is the same index according to column and ts

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#1006]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion
When creating an index during deploy, you need to judge whether it is the same index according to column and ts

## Expected Behavior
Determine whether the index is duplicate through column and ts

## Current Behavior
Judge whether the index is duplicate only according to the column

**Comment by jingchen2222** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix tracking](https://trello.com/c/wEQ9HW0k/25-bugfix-tracking)
