### ISSUE TITLE
Fail to use yarn mode after importing data in local mode

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1010]
Now we will load the imported tables in openmldb databases. If we have imported offline data in Spark local mode, we will fail to load them in Spark yarn-cluster mode which will fail all the jobs from TaskManager.

Here is the error message when registering the offline tables.

<img width="1440" alt="Screen Shot 2022-01-04 at 5 56 32 PM" src="https://user-images.githubusercontent.com/2715000/148042037-566e384c-c914-43f1-a670-e523c9555104.png">

**Comment by jingchen2222** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix tracking](https://trello.com/c/wEQ9HW0k/25-bugfix-tracking)
