### ISSUE TITLE
Offline data is not removed when dropping tables with offline table info

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1011]
Now the offline data in HDFS is not removed in yarn cluster mode.

<img width="1375" alt="Screen Shot 2022-01-04 at 6 22 55 PM" src="https://user-images.githubusercontent.com/2715000/148045636-b85663e2-3f5b-4574-862d-5a8669ea38e9.png">

Success to drop table but without error message or removing remote files.

<img width="1792" alt="Screen Shot 2022-01-04 at 6 19 25 PM" src="https://user-images.githubusercontent.com/2715000/148045663-0abc1858-7675-46c9-8b47-f17e364efa70.png">

**Comment by jingchen2222** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix tracking](https://trello.com/c/wEQ9HW0k/25-bugfix-tracking)
