### ISSUE TITLE
`updatetablealive` cmd run failed

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1016]
![WX20220105-110422](https://user-images.githubusercontent.com/6183996/148154320-a7aef298-a5aa-4c09-b734-629895dada70.png)

**Comment by jingchen2222** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix tracking](https://trello.com/c/wEQ9HW0k/25-bugfix-tracking)
