### ISSUE TITLE
when spark.master = yarn, offline.data.prefix = hdfs://*******.

### ISSUE THREAD

**Issue by KaidoWang** [4paradigm/OpenMLDB#1068]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

when spark.master = yarn, offline.data.prefix = hdfs://*******.

## Expected Behavior
In taskmanager.properties,
when spark.master = yarn, offline.data.prefix = hdfs://*******.

## Current Behavior

now offline.data.prefix default starts with file:///*******

## Steps to Reproduce

1.
2.
3.
4.

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-dihao](https://trello.com/c/NcZTvHzh/16-bugfix-dihao)
