### ISSUE TITLE
Fail to start TaskManager if the zk node of openmlb base path does not exist

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1077]
The TaskManager may fail to start when the openmldb base zk path does not exist.

<img width="1792" alt="Screen Shot 2022-01-12 at 2 51 22 PM" src="https://user-images.githubusercontent.com/2715000/149078443-5fdafcab-3123-4284-a1b8-d411d90c6024.png">

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-dihao](https://trello.com/c/NcZTvHzh/16-bugfix-dihao)
