### ISSUE TITLE
Wheel file of PythonSDK removed  by "Remove_directory" command in CMakeList of Hybridse Python package 

### ISSUE THREAD

**Issue by HuilinWu2** [4paradigm/OpenMLDB#1085]
In file `OpenMLDB-main/hybridse/src/sdk/CMakeLists.txt` line170:
`COMMAND ${CMAKE_COMMAND} -E remove_directory dist`

This command will clean the directory `OpenMLDB-main/build/python/dist/`, where the wheel file of OpenMLDB PythonSDK `openmldb-0.4.0-py3-none-any.whl` may be deleted.

**Comment by aceforeverd** [comment]
the python module inside hybridse can be deleted
