### ISSUE TITLE
Fail to stop yarn job in cluster mode and connect the incorrect Yarn cluster

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1088]
Now we get request timeout when try to stop yarn job in cluster mode. Here is the error log of client.

<img width="1426" alt="企业微信截图_1fc4ed93-ffdd-4233-a4b8-23c45fae8e9b" src="https://user-images.githubusercontent.com/2715000/149263861-be8df9f8-fd26-419b-8737-6491427c0144.png">

Here is the log of TaskManager.

<img width="1792" alt="Screen Shot 2022-01-13 at 11 56 29 AM" src="https://user-images.githubusercontent.com/2715000/149263731-3c12a1ad-b1b4-4e40-b5a5-00f80abca20c.png">

In fact, `HADOOP_CONF_DIR` is set but TaskManager does not read the config and find the correct Yarn cluster.

**Comment by tobegit3hub** [comment]
Now we can put the Hadoop XML configuration files in `./taskmanager/con/` for workaround. It would be better to read files in `$HADOOP_CONF_DIR` or set path in `taskmanager.properties`.

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-P1](https://trello.com/c/yMBAuhYq/22-bugfix-p1)

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TaskManager improvement and bugfix](https://trello.com/c/raqCp82f/11-taskmanager-improvement-and-bugfix)
