### ISSUE TITLE
Importing CSV file in offline may create files with incorrect schema without warning

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1100]
Now importing CSV file in offline may generate parquet files whose schema is not expected, maybe all string columns.

We should raise exception if the schema does not match.

**Comment by tobegit3hub** [comment]
For example, we may create table like this.

```
CREATE TABLE demo_table1(c1 string, c2 int, c3 bigint, c4 float, c5 double, c6 timestamp, c7 date);
```

The data file looks like this.

```
c1,c2,c3,c4,c5,c6,c7
aaa,11,22,1.2,11.3,1636097290000,2021-07-20
aaa,12,22,2.2,12.3,1636097390000,2021-08-19
```

And try to load offline data with this SQL.

```
SET @@execute_mode='offline';

LOAD DATA INFILE 'data/data.csv' INTO TABLE demo_table1;
```

We can read the parquet with pyspark and find the schema is all string.

```
df = spark.read.parquet("file:////tmp/data.csv")
df.schema
```

**Comment by vagetablechicken** [comment]
`LOAD DATA` offline mode reading doesn't add "schema" option. Online mode has it, ref
https://github.com/4paradigm/OpenMLDB/blob/f6a6ea5e75692f43b25576429310db671cc71bee/java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/LoadDataPlan.scala#L66
