### ISSUE TITLE
`Date` type value is incorrect when load data into online table

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1103]
row data:
<img width="753" alt="bfa650d027b33ef19cb81c560661ddc5" src="https://user-images.githubusercontent.com/6183996/149605353-e4ad02a3-5199-40d5-9d6a-78ad86e1e7de.png">

select from online table
![688ef9decdfe63ff33a5d9ff94f58f9a](https://user-images.githubusercontent.com/6183996/149605342-3441e168-129c-4bce-a5e7-99b05849695f.png)

**Comment by tobegit3hub** [comment]
We could reproduce the issue by quickstart docs. @yabg-shuai666 please check and try to fix this.

**Comment by yabg-shuai666** [comment]
> We could reproduce the issue by quickstart docs. @yabg-shuai666 please check and try to fix this.

ok!
