### ISSUE TITLE
build(link system thirdparty ): use result variables from `find_package` 

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#1118]
somethings compile error might happen if he installed e.g boost in `/lib64` already in there system. It may necessary to use variables set by `find_package`, like `Boost_LIBRARIES`, in case cmake accidentally link boost  to that system installed boost ( a non-standard system)

In detail, e.g  https://github.com/4paradigm/OpenMLDB/blob/72a052400996b80a5c9ae8408802e23e04370ce7/hybridse/CMakeLists.txt#L98, should replace `boost_*` with `${Boost_LIBRARIES}`

It might one of the things to support link openmldb with system libraries

**Comment by zhanghaohit** [comment]
- [x] boost
- [x] ICU
- [ ] protobuf
- [ ] glog
