### ISSUE TITLE
CLI command will not be executed if we add space after semicolon 

### ISSUE THREAD

**Issue by keyu813** [4paradigm/OpenMLDB#1121]
![image](https://user-images.githubusercontent.com/60570208/150107977-81df1627-0fc7-4cfb-875c-644691b7e0ca.png)
In sql_client, if we add space after semicolon and ENTER, command will not be executed

**Comment by dl239** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bug-denglong](https://trello.com/c/sdJl9Vdl/2-bug-denglong)

**Comment by aceforeverd** [comment]
resolved in #1820
