### ISSUE TITLE
Log optimization

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#1126]
Describe the cause of failure as much as possible. It is best not to use error: OK

**Comment by jingchen2222** [comment]
![image](https://user-images.githubusercontent.com/6291173/150400251-dac89c59-bb8e-4f62-9706-43cd6aaf9220.png)

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-chenjing](https://trello.com/c/J5u9EIk4/17-bugfix-chenjing)

**Comment by jingchen2222** [comment]
Resolved by #1130
