### ISSUE TITLE
Auto Create table throw error when new ttl greater than current ttl

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#1131]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

Now OpenMLDB will auto-create a table when we deploy SQL in CLI. So when the TTL > the original table's TTL, we should update the TTL or throw error if we can't support ttl update
## Steps to Reproduce

1.
2.
3.
4.

**Comment by dl239** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bug-denglong](https://trello.com/c/sdJl9Vdl/2-bug-denglong)

**Comment by dl239** [comment]
It need to check ttl in [`HandleDeploy`](https://github.com/4paradigm/OpenMLDB/blob/main/src/sdk/sql_cluster_router.cc#L2883) function if relevant tables exist
