### ISSUE TITLE
Add blocking api for TaskManager APIs

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1137]
Add new APIs of TaskManager to submit jobs and wait for job finished.

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TaskManager improvement and bugfix](https://trello.com/c/raqCp82f/11-taskmanager-improvement-and-bugfix)

**Comment by vagetablechicken** [comment]
link to #1436
