### ISSUE TITLE
Un-support statement type: SystemVariableAssignment

### ISSUE THREAD

**Issue by weekstudy** [4paradigm/OpenMLDB#1140]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion
使用docker 镜像4pdosc/openmldb:latest ，启动容器，运行案例1：出租车行车时间预测，出现Un-support statement type: SystemVariableAssignment的错误

![image](https://user-images.githubusercontent.com/39413303/150902421-ec4e0e6a-afac-43c9-bea7-adb4d03e0f01.png)

**Comment by tobegit3hub** [comment]
@@execute_mode is treated as a system variable which is not supported yet. We should update the docs and let users to set offline mode with the following command.

```
SET @@SESSION.execute_mode='offline';
```

@weekstudy You may try the above command now and the docs may be updated later.

**Comment by weekstudy** [comment]
> @@execute_mode is treated as a system variable which is not supported yet. We should update the docs and let users to set offline mode with the following command.
> 
> ```
> SET @@SESSION.execute_mode='offline';
> ```
> 
> @weekstudy You may try the above command now and the docs may be updated later.
还是报错
![image](https://user-images.githubusercontent.com/39413303/150904468-946b367a-0680-4c60-bd39-b92a55225b79.png)

**Comment by dl239** [comment]
@weekstudy 重新拉下镜像试试

**Comment by weekstudy** [comment]
> SET @@SESSION.execute_mode='offline';

没有报错了，感谢！
