### ISSUE TITLE
执行内置的predict.py脚本，并未返回案例结果

### ISSUE THREAD

**Issue by weekstudy** [4paradigm/OpenMLDB#1142]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion
运行最新的docker 镜像，使用在线模式测试案例1：出租车行车时间预测，出现如下报错

![image](https://user-images.githubusercontent.com/39413303/150920883-ec60b8ff-42b8-41ec-9686-3a38c7ec106f.png)

**Comment by dl239** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bug-denglong](https://trello.com/c/sdJl9Vdl/2-bug-denglong)
