### ISSUE TITLE
cppunit not found

### ISSUE THREAD

**Issue by zoyopei** [4paradigm/OpenMLDB#1156]
Could NOT find cppunit when build third-party from source. My cppunit library is in `${CPPUNIT_ROOT_DIR}/lib` .
`make BUILD_BUNDLED=ON THIRD_PARTY_CMAKE_FLAGS="-DCPPUNIT_ROOT_DIR=${CPPUNIT_ROOT_DIR}"`
```
-- Could NOT find cppunit (missing: CPPUNIT_LIBRARY CPPUNIT_INCLUDE_DIR)
CMake Error at cmake/FetchZookeeper.cmake:28 (message):
  zookeeper require cppunit
Call Stack (most recent call first):
  CMakeLists.txt:194 (include)
```

**Comment by aceforeverd** [comment]
affected environment ? os & cppunit path

**Comment by zoyopei** [comment]
> affected environment ? os & cppunit path

ubuntu18.04  CPPUNIT_ROOT_DIR=~/.linuxbrew/Cellar/cppunit/1.15.1
