### ISSUE TITLE
Fail to insert data with db name in Python SDK

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1161]
Now we can use insert SQL to insert data into table. But it fails if the table name has db name prefix.

<img width="829" alt="Screen Shot 2022-01-29 at 4 08 49 PM" src="https://user-images.githubusercontent.com/2715000/151653280-d160a1f3-572c-4309-989f-a7a681150429.png">

**Comment by tobegit3hub** [comment]
It would be the issue of sql parser in CLI and SDK. We should fix it after refactoring the router sdk.

**Comment by dl239** [comment]
refer https://github.com/4paradigm/OpenMLDB/issues/977

**Comment by tobegit3hub** [comment]
Resolved by https://github.com/4paradigm/OpenMLDB/pull/1173 .
