### ISSUE TITLE
Load csv file failed if schema set `not null`

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1170]
`CREATE TABLE test_click_table2(
device_id STRING NOT NULL,
event_type STRING NOT NULL,
ability_id STRING NOT NULL,
category_first_id STRING NOT NULL,
std_time TIMESTAMP,
std_date DATE,
testno bigint
) OPTIONS(partitionnum=8, replicanum=2);`

![WX20220208-151634](https://user-images.githubusercontent.com/6183996/152965047-b4715be8-4e6a-4997-8af4-ca6b0f000171.png)

**Comment by vagetablechicken** [comment]
csv sample
```
device_id,event_type,ability_id,category_first_id,std_time,std_date,testno
aaa,A001,ab0001,100,1644237660000,2022-02-07,1
```
and write to online storage.

The column `std_time` is int64, but spark read csv only support Y-M-D H:M:S.
So after read, std_time value is `null`.
If `std_time` col has non-null values, it won't get error.


- [x] We will support int64 to be a csv timestamp format, so we should read 1 row to decide which ts format we should use.

If we read integer in ts column, we will read it as bigint, then convert this column(bigint) to timestamp type.

Further more

Why the error is "write null to non-null column `device_id` failed"? Not the column `std_time`?
**We can set any nullable column to `null`, it will got the same error.** code version ef2e6e826
e.g.
```
device_id,event_type,ability_id,category_first_id,std_time,std_date,testno
aaa,a,a,100,2022-02-07 20:54:20,2022-02-01,null
```

We should check about spark read df. `openmldb-spark-connector` has ut about insert null, it's ok, so the source df may have some error. 
I'll open another issue to track.

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-huangwei](https://trello.com/c/RB2WAims/18-bugfix-huangwei)

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [improvement for CSV import](https://trello.com/c/eSTnTgIY/13-improvement-for-csv-import)
