### ISSUE TITLE
`Offline path` may not displayed after import offline data

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1172]
![WX20220208-212147](https://user-images.githubusercontent.com/6183996/152995514-a8068337-deed-46d2-a6d8-7059c810e6ec.png)

![WX20220208-212344](https://user-images.githubusercontent.com/6183996/152995869-a6ab7027-5e75-4aab-8160-6a7860fad3c8.png)

**Comment by vagetablechicken** [comment]
Forgot to call `NotifyTableChanged()` in the function
https://github.com/4paradigm/OpenMLDB/blob/f7996e6991bd8b0470781bf34ef05347afa1ac87/src/nameserver/name_server_impl.cc#L10173

**Comment by tobegit3hub** [comment]
`NotifyTableChanged()` was add but does not work immediately so we have deleted it. It seems that we have add here.
