### ISSUE TITLE
We can create database with number as name in SDK but can not drop it later

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1198]
Now we can create database with number as name in Python SDK. But we can not drop it in CLI or Python SDK.

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/2715000/153532932-229fa2d6-34c6-4b71-af04-63e1f5bd5264.png">

**Comment by HuilinWu2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve functionality of Python SDK](https://trello.com/c/xlXZPfTf/20-improve-functionality-of-python-sdk)

**Comment by dl239** [comment]
drop  database  \`10\`
