### ISSUE TITLE
CMake error when compiling and testing newly added functions

### ISSUE THREAD

**Issue by Liu-2001** [4paradigm/OpenMLDB#1199]
I encountered this issue when try compiling OpenMLDB within hybridsql Docker Container. CMake error occurs when I followed the the 4th step given in [development guide for built-in function](https://github.com/4paradigm/OpenMLDB/blob/main/docs/en/built_in_function_develop_guide.md) to compile and test newly added functions.
![Image 11-2-22 at 3 24 PM](https://user-images.githubusercontent.com/59218442/153552265-dc842791-3b32-49f2-94a8-f426285305ee.jpg)
![Image 11-2-22 at 3 23 PM](https://user-images.githubusercontent.com/59218442/153552285-8ac3107c-2f3c-445b-8089-3bc0d1e28fcb.jpg)

**Comment by aceforeverd** [comment]
Sorry the doc is a bit outdated.
Currently user is encouraged to use the makefile in top directory. So u can run 'make hybridse TESTING_ENABLE=ON'.

**Comment by Liu-2001** [comment]
> Sorry the doc is a bit outdated.
> Currently user is encouraged to use the makefile in top directory. So u can run 'make hybridse TESTING_ENABLE=ON'.

Noted with thanks!

**Comment by jingchen2222** [comment]
@Liu-2001 Hi Liu, thank you for your issue. Is your problem solved now? I would like to close the issue if you are ok with the compiling.

**Comment by Liu-2001** [comment]
> @Liu-2001 Hi Liu, thank you for your issue. Is your problem solved now? I would like to close the issue if you are ok with the compiling.

Yes, thanks @aceforeverd for kind reply!
