### ISSUE TITLE
Incorrect SQL in Python SDK does not throw exception

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1201]
We have test the incorrect SQL but it does not throw errors like this.

```
select abc
```

And the incorrect SQL throws errors just like what we expect.

```
selectt abc
```

<img width="1336" alt="Screen Shot 2022-02-11 at 6 32 34 PM" src="https://user-images.githubusercontent.com/2715000/153576701-8743f08e-2ac5-400b-8e1d-e5306e80436a.png">

**Comment by HuilinWu2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve functionality of Python SDK](https://trello.com/c/xlXZPfTf/20-improve-functionality-of-python-sdk)

**Comment by HuilinWu2** [comment]
The bug is fixed both on shell and python sdk 
![image](https://user-images.githubusercontent.com/68987242/155092498-5f44a351-ef92-4e04-a3cc-2b9c37889053.png)
