### ISSUE TITLE
Allow non-empty tables for deploy

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#1203]
**Is your feature request related to a problem? Please describe.**
For now, we do not allow `deploy` if there is already some data in the related tables.

**Describe the solution you'd like**
After automatically adding indexes, we scan all the data and update the newly-added indexes

**Comment by dl239** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [deployment with data](https://trello.com/c/tJq7yPrU/25-deployment-with-data)
