### ISSUE TITLE
Incorrect SQL like `SELECT 100ss` or `select 100s` can be run 

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1208]
Now we can run SQL like `SELECT 100ss` in CLI which may output unexcepted result. Here is the execution and result.

<img width="1191" alt="Screen Shot 2022-02-12 at 7 56 42 PM" src="https://user-images.githubusercontent.com/2715000/153710393-e2bf3e3b-fffd-43ac-8381-c1cf6820739e.png">

**Comment by aceforeverd** [comment]
confirmed. https://github.com/4paradigm/OpenMLDB/blob/7712aeec6714ee21ec2d5d9cc959f5a3366c1e0c/hybridse/src/node/expr_node.cc#L883 there are many data type not handled in the function

**Comment by aceforeverd** [comment]
2. in zetasql `select 100ss` compiles:
```
select 100ss;
--
QueryStatement [0-12]
  Query [0-12]
    Select [0-12]
      SelectList [7-12]
        SelectColumn [7-12]
          IntervalLiteral(100s) [7-11]
          Alias [11-12]
            Identifier(s) [11-12]
--
SELECT
  100s AS s
==
```

**Comment by tobegit3hub** [comment]
This is the log of mysql client.

<img width="764" alt="image" src="https://user-images.githubusercontent.com/2715000/154437780-e75b9f22-1a2b-4ae9-aef8-681413e79ccc.png">

**Comment by aceforeverd** [comment]
Left TODO:
- `select 100s` is invalid

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-P1](https://trello.com/c/yMBAuhYq/22-bugfix-p1)
