### ISSUE TITLE
TestWindowUnion failed:  20 did not equal 10 (TestWindowUnion.scala:58)

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#122]
TestWindowUnion failed when executing `mvn test`

## Expected Behavior

all test pass

## Current Behavior

1 test `TestWindowUnion` Failed
```log
21/07/06 09:28:07 INFO DAGScheduler: Job 10 is finished. Cancelling potential speculative or zombie tasks for this job
21/07/06 09:28:07 INFO TaskSchedulerImpl: Killing all running tasks in stage 48: Stage finished
21/07/06 09:28:07 INFO DAGScheduler: Job 10 finished: count at OpenmldbDataframe.scala:103, took 3.472455 s
21/07/06 09:28:07 WARN SparkSession$Builder: Using an existing SparkSession; some spark core configurations may not take effect.
- Test end2end window union *** FAILED ***
  20 did not equal 10 (TestWindowUnion.scala:58)
TestUnsafeRowRowProject:
21/07/06 09:28:07 WARN SparkSession$Builder: Using an existing SparkSession; some spark core configurations may not take effect.
21/07/06 09:28:07 INFO ConfigReflections$: Native Spark Configuration: openmldb.unsaferow.opt -> true
21/07/06 09:28:07 INFO ConfigReflections$: Native Spark Configuration: spark.sql.session.timeZone -> Etc/UTC
```

## Possible Solution
TBD

## Reproduce
- go to terminal
- execute: `mvn test`
- scroll up and there is ` Test end2end window union *** FAILED ***`

However
it run test in IDEA or execute single test e.g 
  `mvn test -Dtestmvn test -Dsuites='com._4paradigm.openmldb.batch.end2end.TestWindowUnion'`
 test will pass

## Context (Environment)

commit: https://github.com/4paradigm/OpenMLDB/pull/103/commits/bd3db96cafadc165dd6385c9b715f90d2fa4b3db
Host: macos & linux
Java: 8

## Full Log
[logs_1420.zip](https://github.com/4paradigm/OpenMLDB/files/6774037/logs_1420.zip)

**Comment by tobegit3hub** [comment]
Resolve by https://github.com/4paradigm/OpenMLDB/pull/300 .
