### ISSUE TITLE
openmdlb or so failed to run on Linux with higher glibc version: undefined symbol: _dl_sym, version GLIBC_PRIVATE

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1228]
OpenMLDB Python SDK  can not load OpenMLDB dynamic file in Ubuntu 21.10. Just like the issue in https://github.com/PaddlePaddle/Paddle/issues/36801 .

Here is the error message and environment.

<img width="1792" alt="Screen Shot 2022-02-15 at 4 44 06 PM" src="https://user-images.githubusercontent.com/2715000/154026491-48fadf9d-d8bc-4fcc-ab19-6136e0703628.png">

<img width="1034" alt="Screen Shot 2022-02-15 at 4 46 14 PM" src="https://user-images.githubusercontent.com/2715000/154026503-5b9e4301-7499-485e-9cb1-f6ab7dace20a.png">

**Comment by HuilinWu2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve functionality of Python SDK](https://trello.com/c/xlXZPfTf/20-improve-functionality-of-python-sdk)

**Comment by aceforeverd** [comment]
> undefined symbol: _dl_sym, version GLIBC_PRIVATE

any OS wit a higher glibc version may has this issue. Also, both openmldb binary and SDK meets the same problem

**Comment by aceforeverd** [comment]
root cause may related to BRPC. Paddle seems to fixed the same problem by upgrading BRPC version https://github.com/PaddlePaddle/Paddle/issues/36801#issuecomment-1229459392
