### ISSUE TITLE
Get warning when extracting the release package file

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1229]
We extract the release file with `tar xzvf ./openmldb-0.4.1-linux.tar.gz` in Linux and get the following warning.

<img width="1136" alt="Screen Shot 2022-02-15 at 4 15 27 PM" src="https://user-images.githubusercontent.com/2715000/154031278-df0946d5-7ebd-4c0d-9a7e-f611e0a86399.png">

BTW, no warning in MacOS.

**Comment by dl239** [comment]
This package is manually packaged under mac. So it has some warnings on linux when extracting

**Comment by aceforeverd** [comment]
COPYFILE_DISABLE=1 tar czf xxx.tar.gz xxx/ on mac

**Comment by aceforeverd** [comment]
workflow released file won't have the problem.
