### ISSUE TITLE
Support GitHub Codespaces

### ISSUE THREAD

**Issue by haifeng-jin** [4paradigm/OpenMLDB#1255]
**Is your feature request related to a problem? Please describe.**
Let open-source contributors easily open the project in [GitHub Codespaces](https://github.com/features/codespaces).
It is a cloud-based IDE to let the contributors open with one click.
With some config files in the repo, the IDE should have everything ready at start. For example, the tests should be ready to run.

It would make contributing to the repo much easier.

**Describe the solution you'd like**
Here is an example setting. [[Link](https://github.com/keras-team/autokeras/tree/master/.devcontainer)]
Another example: [[Link](https://github.com/keras-team/keras/tree/master/.devcontainer)]

**Comment by aceforeverd** [comment]
Yes, nice point.  We have official compile image and let's see if we can build based on that, maybe some extra develop tools needed e.g clangd

PR is welcome
