### ISSUE TITLE
OpenMLDB Batch fail when timestamp value is null

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1263]
Handle timestamp type with null value when try to get timestamp value in openmldb-batch

![wecom-temp-e4713a0c966269cbbc9ab6d031b786ff](https://user-images.githubusercontent.com/2715000/154662729-e4a6d176-5ab9-4bc2-9392-289ad5ab466a.png)

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-dihao](https://trello.com/c/NcZTvHzh/16-bugfix-dihao)

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [online monitoring](https://trello.com/c/arsSP4R6/1-online-monitoring)

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-dihao](https://trello.com/c/NcZTvHzh/16-bugfix-dihao)
