### ISSUE TITLE
refactor `const std::shared_ptr<T>` to `std::shared_ptr<const T>`

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#1293]
It should be the `std::shared_ptr<const T>`, which means the data pointed by the shared_ptr cannot be changed rather than the shared_ptr itself cannot be changed.

e.g., `const std::shared_ptr<OptionsMap> options_`

**Comment by IZUMI-Zu** [comment]
Can I have a try?

**Comment by lumianph** [comment]
> Can I have a try?

sure! I have assigned to you. Thanks.
