### ISSUE TITLE
add `storage_mode` option for `create table` statement

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#1294]
**Is your feature request related to a problem? Please describe.**
disk-based storage

**Describe the solution you'd like**
OPTIONS(storage_mode="HDD")

**Comment by zhanghaohit** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [long time window - storage engine](https://trello.com/c/UxAMvWh5/5-long-time-window-storage-engine)

**Comment by dl239** [comment]
We can also set this by `engine` option like [mysql](https://dev.mysql.com/doc/refman/8.0/en/using-innodb-tables.html) or specific `engine` in our `OPTIONS`

**Comment by zhanghaohit** [comment]
> We can also set this by `engine` option like [mysql](https://dev.mysql.com/doc/refman/8.0/en/using-innodb-tables.html) or specific `engine` in our `OPTIONS`

Yes. It is an alternative. But our option is like `hdd`, `memory` and `ssd`, which may be different from the `engine` context like mysql (e.g., `InnoDB`).
