### ISSUE TITLE
Fail to register notebook magic function with Python SDK

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1309]
With latest code, we will fail when register the notebook magic function. Here is the error message.

![企业微信截图_6946022b-d027-43bd-8d51-e9df9de5cb7e](https://user-images.githubusercontent.com/2715000/155507015-fb1e82a1-b5fa-4cf8-9d87-264dadfa8133.png)

Comment out the test code will work again.

<img width="895" alt="wecom-temp-9e9772f701c9c8b2c904c8d10664a881" src="https://user-images.githubusercontent.com/2715000/155507082-421114aa-f0c9-450a-baa8-ed4cba0d6e86.png">

**Comment by HuilinWu2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve functionality of Python SDK](https://trello.com/c/xlXZPfTf/20-improve-functionality-of-python-sdk)
