### ISSUE TITLE
python sdk,  when import openmldb, find ImportError: cannot import name 'default' from 'sqlalchemy.engine' (unknown location)

### ISSUE THREAD

**Issue by KaidoWang** [4paradigm/OpenMLDB#1313]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

import openmldb;
Success!

ImportError: cannot import name 'default' from 'sqlalchemy.engine' (unknown location)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by tobegit3hub** [comment]
@KaidoWang Can you provide the methods to reproduce the issue? And provide the information of environment, like run in MacOS or docker container?

**Comment by KaidoWang** [comment]
MacOS

**Comment by tobegit3hub** [comment]
Done.
