### ISSUE TITLE
Add assertion in unit test of OpenmldbCatalogService

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1317]
Now the unit test of `OpenmldbCatalogService` is quite simple and lack of assertions. You can find the test code in https://github.com/4paradigm/OpenMLDB/blob/main/java/openmldb-batch/src/test/scala/com/_4paradigm/openmldb/batch/catalog/TestOpenmldbCatalogService.scala .

Now we can get all the table names from internal db. It would be better to add code in line 36 and check the table name like this using assertation.
```
val internalTableNames = List("JOB_INFO", "PRE_AGG_META_INFO")
assert(internalTableNames.contains(tables(i)))
```

**Comment by tobegit3hub** [comment]
Now we can get all the table names from internal db.

It would be better to add code in line 36 and check the table name like this.

```
val internalTableNames = List("JOB_INFO", "PRE_AGG_META_INFO")

assert(internalTableNames.contains(tables(i)))
```

**Comment by SaumyaBhushan** [comment]
I would like to work on this issue.

**Comment by SaumyaBhushan** [comment]
@tobegit3hub @lumianph I have raised a PR. Please review.
