### ISSUE TITLE
Resolve the compile warning of openmldb-batch

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1320]
Now we can get logs of warning of Java module `openmldb-batch` when compiling.

```
[WARNING] /Users/tobe/code/4pd/OpenMLDB/java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/SparkPlanner.scala:342: warning: object Jav
aConversions in package collection is deprecated (since 2.12.0): use JavaConverters
[WARNING]       engine = new SqlEngine(sql, dbs, engineOptions, config.defaultDb)
[WARNING]                                   ^
```

You can reproduce the issue by compiling java modules with `mvn clean package`.

**Comment by vagetablechicken** [comment]
- [ ] 2nd 

```
[WARNING] /Users/tobe/code/4pd/OpenMLDB/java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/WindowAggPlan.scala:530: warning: com
paring values of types Long and Null using `==' will always yield false
[WARNING]     if (key == null) {
[WARNING]             ^
```

**Comment by mangoGoForward** [comment]
[WeOpen Star]I would like to help

**Comment by lumianph** [comment]
i have assigned to you, thanks.

**Comment by mangoGoForward** [comment]
Hi @lumianph ,Sorry about that I don't know how to solved this issue, and not familiar with `scala` language.
if ok, please unassigned to me, and others want to contribute, please go on.

**Comment by lumianph** [comment]
> Hi @lumianph ,Sorry about that I don't know how to solved this issue, and not familiar with `scala` language. if ok, please unassigned to me, and others want to contribute, please go on.

noted, but I saw a PR from you related to this issue, you want to close the PR as well?

**Comment by lumianph** [comment]
this issue is still open right now, contributions are welcome

**Comment by TBCCC** [comment]
[WeOpen Star]I would like to help
