### ISSUE TITLE
docs: translate OpenMLDB QuickStart from Chinese to English

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#1321]
1. Translate this latest OpenMLDB QuickStart from Chinese to English: https://docs.openmldb.ai/quickstart/openmldb_quickstart
The source of this doc is here: https://github.com/4paradigm/openmldb-docs-zh/blob/dev/quickstart/openmldb_quickstart.md
2. Save the translated English quickstart in this repo as docs/en/openmldb_quickstart.md

**Comment by cswjd** [comment]
I would like to help.

**Comment by cswjd** [comment]
Images in the en ver documentation need to be placed in the directory: docs/en/images/ ？

**Comment by lumianph** [comment]
> 

yes, it can be placed there. Thanks.
