### ISSUE TITLE
docs: translate the Java SDK quickstart from Chinese to English

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#1322]
1. Translate the Java SDK from Chinese to English: https://docs.openmldb.ai/quickstart/java_sdk
The source of this doc is here: https://github.com/4paradigm/openmldb-docs-zh/blob/dev/quickstart/java_sdk.md
2. Save the translated English version in this repo as docs/en/java_sdk.md

**Comment by cswjd** [comment]
I would like to help
