### ISSUE TITLE
docs: translate the Python SDK quickstart from Chinese to English

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#1323]
- Translate the Python SDK from Chinese to English: https://docs.openmldb.ai/quickstart/python_sdk
The source of this doc is here: https://github.com/4paradigm/openmldb-docs-zh/blob/dev/quickstart/python_sdk.md
- Save the translated English version in this repo as docs/en/python_sdk.md

**Comment by cswjd** [comment]
I would like to help
