### ISSUE TITLE
importer: count how many rows we read

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1327]
https://github.com/4paradigm/OpenMLDB/blob/1aecdbc7f3bffe62373fecdab158f9f6611d9775/java/openmldb-import/src/main/java/com/_4paradigm/openmldb/importer/Importer.java#L210-L221

We don't know how may rows we read. So count it and print a log.

You can use this logger https://github.com/4paradigm/OpenMLDB/blob/1aecdbc7f3bffe62373fecdab158f9f6611d9775/java/openmldb-import/src/main/java/com/_4paradigm/openmldb/importer/Importer.java#L55
or `System.out.println` or any better ways for printing.

**Comment by vagetablechicken** [comment]
You can use this logger https://github.com/4paradigm/OpenMLDB/blob/1aecdbc7f3bffe62373fecdab158f9f6611d9775/java/openmldb-import/src/main/java/com/_4paradigm/openmldb/importer/Importer.java#L55
or `System.out.println` or any better way.

**Comment by cswjd** [comment]
I would like to help

**Comment by Manny-op** [comment]
I would like to help contribute.
