### ISSUE TITLE
scripts: improve onebox script

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1328]
https://github.com/4paradigm/OpenMLDB/blob/1aecdbc7f3bffe62373fecdab158f9f6611d9775/onebox/start_onebox.sh#L35-L36

The onebox start script will create all dirs and logs in the root dir. It's hard to cleanup.
Plz move it to another place, and each server should have an unique log path(use `-openmldb_log_dir=xxx`).

**Comment by auula** [comment]
I can complete this task~
