### ISSUE TITLE
spark connector: should handle the returns after write 

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1329]
https://github.com/4paradigm/OpenMLDB/blob/1aecdbc7f3bffe62373fecdab158f9f6611d9775/java/openmldb-spark-connector/src/main/java/com/_4paradigm/openmldb/spark/write/OpenmldbDataWriter.java#L130

`executeBatch` will return a list of int, 0 means ok, -1 means insert failed.
Read the list, if not all 0, throw an exception.

**Comment by TheFu527** [comment]
I would like to help.

**Comment by vagetablechicken** [comment]
> I would like to help.

👍  If you need help, just ask for it.

**Comment by cswjd** [comment]
I would like to help.
