### ISSUE TITLE
用导入工具 dataimporter.jar，6个2亿行数据并行导入，报连不上zk

### ISSUE THREAD

**Issue by zhanglei4pd** [4paradigm/OpenMLDB#134]
用导入工具 dataimporter.jar，6个2亿行数据并行导入，报错如下
fail to refresh nodemanager
fail to refresh table
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /rtidb_zk_root_path/nodes

**Comment by imotai** [comment]
@zhanglei4pd  
是导入开始时，就连不上zk，还是导入运行一段时间后，出错？

**Comment by zhanglei4pd** [comment]
单独导入一份2亿的数据，可以导入，耗时1h40min
6个两亿并行，开始导入一会就报错了。
目前将tickTime改为5000，并重启zookeeper，目前不再报错，重新并行导入6个2亿数据测试中

**Comment by zhanglei4pd** [comment]
共3台机器，每台机器上都部署了zookeeper和rtidb，每台机器配置20物理核， 80虚拟核，256内存。
6个两亿行的csv并行导入，三个节点的cpu使用率都很低，%Cpu（s）：0.2us ，0.1ys。
但导入程序依然在报fail to refresh nodemanager
fail to refresh table
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /rtidb_zk_root_path/nodes

**Comment by zhanglei4pd** [comment]
![image](https://user-images.githubusercontent.com/87460998/125778286-8696bec8-fde4-4e64-a76f-4b426b15fb18.png)

**Comment by zhanglei4pd** [comment]
![image](https://user-images.githubusercontent.com/87460998/125778440-2b4f0867-8fbf-4915-9987-7cb2a6cf9340.png)

**Comment by zhanglei4pd** [comment]
导入运行一段时间后出错

![image](https://user-images.githubusercontent.com/87460998/125778503-e050d12c-d6a6-40ae-bf15-b6d503051f39.png)

**Comment by imotai** [comment]
@zhanglei4pd 错误是客户端的报出来的 ，可以把session超时调整大一些
