### ISSUE TITLE
Use the new ExecuteSQL API for Python DB API and SQLAchemely

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1349]
Now we can execute arbitrary SQL commands with new ExeucteSQL API from C library. Just update the wrapper of DB API and SQLAchemely for Python SDK.

<img width="838" alt="wecom-temp-b69d239ab9c90d048cc165f15f9bc511" src="https://user-images.githubusercontent.com/2715000/155963882-b5753bf9-173a-4a68-a3e1-2adb524b3d00.png">

**Comment by tobegit3hub** [comment]
ExecuteSQL is added by https://github.com/4paradigm/OpenMLDB/commit/9e0e480d63503db51481ef06a7938e35c831218a .

**Comment by HuilinWu2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve functionality of Python SDK](https://trello.com/c/xlXZPfTf/20-improve-functionality-of-python-sdk)
