### ISSUE TITLE
Support SQL syntax of "create table if not exists"

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1353]
Now we can run SQL to create databases and create tables but `create database if not exists` and `create table if not exists` are not supported. They are useful to demo when creating databases and tables without failures.

It requires SQL syntax support and need @aceforeverd to support.

**Comment by aceforeverd** [comment]
Sure, syntax supported, need adopt in openmldb

**Comment by tobegit3hub** [comment]
Thanks @aceforeverd . We will add support in client to check the options from SQL logical node.
