### ISSUE TITLE
coverage error on scoverage: No source root found for '/_w/OpenMDLB/OpenMLDB/java/openmldb-batch/src/test/scala/com/_4paradigm/batch/TestDate.scala'

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1375]
Now the CICD job may fail because of java coverage plugin. Here is the error message.

<img width="1300" alt="wecom-temp-bba425fa8fcff775c4c9b192aa63a08e" src="https://user-images.githubusercontent.com/2715000/156692840-f9951701-cd11-4256-8e7d-69e108706a35.png">

**Comment by tobegit3hub** [comment]
Example error in https://github.com/4paradigm/OpenMLDB/runs/5403702911?check_suite_focus=true .

**Comment by lumianph** [comment]
@aceforeverd you may take a look?

**Comment by aceforeverd** [comment]
https://github.com/scoverage/scoverage-maven-plugin/issues/38

**Comment by aceforeverd** [comment]
coverage fail start by d5573ef51a8f888b9fd34adcb877eb96d7f1e764, but I don't understand why #1343 will fail coverage

**Comment by vagetablechicken** [comment]
Have you tested the version before d5573ef?

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-liguo](https://trello.com/c/Ut8UamBY/37-bugfix-liguo)
