### ISSUE TITLE
taskmanager: compare int with null

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1377]
```
[WARNING] /Users/ark/Code/OpenMLDB/java/openmldb-taskmanager/src/main/scala/com/_4paradigm/openmldb/taskmanager/spark/SparkJobManager.scala:81: warning: comparing values of types Int and Null using `!=' will always yield true
[INFO]     if (TaskManagerConfig.SPARK_YARN_MAXAPPATTEMPTS != null) {
```

**Comment by lumianph** [comment]
is this an urgent bug?

**Comment by wuteek** [comment]
Hello, I added a PR for this one as well if you could check it out for me (:

**Comment by lumianph** [comment]
> Hello, I added a PR for this one as well if you could check it out for me (:

thank you for your contribution!!

**Comment by wuteek** [comment]
Is anyone able to assist me with my pull request that was linked here? I posted a comment on it but I'm not sure if anyone would be able to see it. Thank you!

**Comment by wuteek** [comment]
> > Hello, I added a PR for this one as well if you could check it out for me (:
> 
> thank you for your contribution!!

How am i able to pass the coverage check?

**Comment by wuteek** [comment]
Hey there! I updated the requested changes for my PR. Just wondering when someone can get back to me and check it (:
