### ISSUE TITLE
Exclude the current row in window aggregation

### ISSUE THREAD

**Issue by HongHuangNeu** [4paradigm/OpenMLDB#1387]
**Is your feature request related to a problem? Please describe.**
In time window aggregation, we would like to to have support for us to exclude the current row in aggregation. This is useful because in some cases, the current row only serves as a pivot to offer timestamps to identify a certain event. Any other  data of this row is not relevant for the aggregation.

**Describe the solution you'd like**
`SELECT count(*) OVER w1  as w1_col2_sum FROM t1
WINDOW w1 as (PARTITION BY user_id ORDER BY time ROWS_RANGE BETWEEN 1s PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW)`

**Describe alternatives you've considered**
We can achive our goal now in a very unintuitive way:
First we add 1 to time stamp column(in milliseconds)
Then we use "1 preceeding" to exclude the added 1 millisecond, as follows:

`SELECT count(*) OVER w1  as w1_col2_sum FROM t1
WINDOW w1 as (PARTITION BY user_id ORDER BY time ROWS_RANGE BETWEEN 1s PRECEDING AND 1 PRECEDING)`

**Additional context**

**Comment by vagetablechicken** [comment]
`EXCLUDE CURRENT_ROW` may be better. And we need to modify `zetasql::ASTWindowSpecification` to support it.

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [exclude current row](https://trello.com/c/2KPIBLFI/105-exclude-current-row)

**Comment by aceforeverd** [comment]
syntax summary:
```
window w1 as ( [ ROWS | ROWS_RANGE | ... ] between ... and ... 
  MAXSIZE <integer literal>
 [ EXCLUDE CURRENT_TIME | EXCLUDE CURRENT_ROW | INSTANCE_NOT_IN_WINDOW ] + )
```
