### ISSUE TITLE
python sdk executemany not work

### ISSUE THREAD

**Issue by kitty-eu-org** [4paradigm/OpenMLDB#1389]
### python sdk executemany not work
When I run executemany with python sdk openmldb and sqlachemy, 
it raises error: "Unsupported in OpenMLDB", 
but I may need to bulk insert data into openmldb
### Anything else
No response
### Are you willing to submit a PR?
 Yes I am willing to submit a PR!

**Comment by vagetablechicken** [comment]
👍  If you need help, just ask for it.

**Comment by tobegit3hub** [comment]
Thanks and any contribution is welcome. @HuilinWu2 may help and provide some guide to support `executemany` API.

**Comment by kitty-eu-org** [comment]
thanks, I would be very grateful if you could provide relevant documentation

**Comment by HuilinWu2** [comment]
Thanks for the issue :)

FYI.
* You can find the raw Python DBAPI under the directory `OpenMLDB/python/openmldb/dbapi/dbapi.py`. 
* You will find that we call the functions from C library in `OpenMLDB/python/openmldb/sdk/sdk.py` and wrap them into Python APIs, that are used in `dbapi.py`.
* Then, you will find the C functions finally in `OpenMLDB/src/sdk/sql_cluster_router.h` and there implementations `sql_cluster_router.cc`

If you have any questions, please feel free to ask :)

**Comment by HuilinWu2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve functionality of Python SDK](https://trello.com/c/xlXZPfTf/20-improve-functionality-of-python-sdk)

**Comment by HuilinWu2** [comment]
solved with [PR](https://github.com/4paradigm/OpenMLDB/pull/1402)
