### ISSUE TITLE
python3 train.py ./fe.sql /tmp/model.txt ， cause coredump

### ISSUE THREAD

**Issue by backyes** [4paradigm/OpenMLDB#140]
Env：
- MacBook Pro (13-inch, M1, 2020)，Apple M1， docker qemu

其他step by step

```bash
[root@47647bd314d4 taxi-trip]# python3 train.py ./fe.sql /tmp/model.txt
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Traceback (most recent call last):
  File "train.py", line 36, in <module>
    train_set, predict_set = openmldb_batch.run_batch_sql(sql)
  File "/work/taxi-trip/openmldb_batch.py", line 11, in run_batch_sql
    spark = SparkSession.builder.appName("OpenMLDB Demo").getOrCreate()
  File "/usr/local/lib/python3.6/site-packages/pyspark-3.0.0-py3.6.egg/pyspark/sql/session.py", line 186, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/usr/local/lib/python3.6/site-packages/pyspark-3.0.0-py3.6.egg/pyspark/context.py", line 371, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/usr/local/lib/python3.6/site-packages/pyspark-3.0.0-py3.6.egg/pyspark/context.py", line 128, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/usr/local/lib/python3.6/site-packages/pyspark-3.0.0-py3.6.egg/pyspark/context.py", line 320, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/usr/local/lib/python3.6/site-packages/pyspark-3.0.0-py3.6.egg/pyspark/java_gateway.py", line 105, in launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number
[root@47647bd314d4 taxi-trip]#
```

**Comment by imotai** [comment]
thanks for the feedback，it‘s seem that the precompiled library can not be ran normally on mac m1. You can try the demo on a linux sever currently and we will create a PR to fix the bug.

**Comment by aceforeverd** [comment]
it's bug from qemu: https://github.com/docker/for-mac/issues/5123#issuecomment-784992589

**Comment by aceforeverd** [comment]
> Env：
> 
> * MacBook Pro (13-inch, M1, 2020)，Apple M1， docker qemu
> 
> 其他step by step
> 
> ```shell
> [root@47647bd314d4 taxi-trip]# python3 train.py ./fe.sql /tmp/model.txt
> qemu: uncaught target signal 11 (Segmentation fault) - core dumped
> Traceback (most recent call last):
>   File "train.py", line 36, in <module>
>     train_set, predict_set = openmldb_batch.run_batch_sql(sql)
>   File "/work/taxi-trip/openmldb_batch.py", line 11, in run_batch_sql
>     spark = SparkSession.builder.appName("OpenMLDB Demo").getOrCreate()
>   File "/usr/local/lib/python3.6/site-packages/pyspark-3.0.0-py3.6.egg/pyspark/sql/session.py", line 186, in getOrCreate
>     sc = SparkContext.getOrCreate(sparkConf)
>   File "/usr/local/lib/python3.6/site-packages/pyspark-3.0.0-py3.6.egg/pyspark/context.py", line 371, in getOrCreate
>     SparkContext(conf=conf or SparkConf())
>   File "/usr/local/lib/python3.6/site-packages/pyspark-3.0.0-py3.6.egg/pyspark/context.py", line 128, in __init__
>     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
>   File "/usr/local/lib/python3.6/site-packages/pyspark-3.0.0-py3.6.egg/pyspark/context.py", line 320, in _ensure_initialized
>     SparkContext._gateway = gateway or launch_gateway(conf)
>   File "/usr/local/lib/python3.6/site-packages/pyspark-3.0.0-py3.6.egg/pyspark/java_gateway.py", line 105, in launch_gateway
>     raise Exception("Java gateway process exited before sending its port number")
> Exception: Java gateway process exited before sending its port number
> [root@47647bd314d4 taxi-trip]#
> ```

Hi @backyes, thanks for reporting.
Just open a pr to support arm64 docker image: #194
You can try again by running
```bash
docker pull ghcr.io/aceforeverd/openmldb:0.2.1-beta3
docker run -it ghcr.io/aceforeverd/openmldb:0.2.1-beta3
```

we'll port the arm64 image to docker hub and other place later

**Comment by imotai** [comment]
> > Env：
> > 
> > * MacBook Pro (13-inch, M1, 2020)，Apple M1， docker qemu
> > 
> > 其他step by step
> > ```shell
> > [root@47647bd314d4 taxi-trip]# python3 train.py ./fe.sql /tmp/model.txt
> > qemu: uncaught target signal 11 (Segmentation fault) - core dumped
> > Traceback (most recent call last):
> >   File "train.py", line 36, in <module>
> >     train_set, predict_set = openmldb_batch.run_batch_sql(sql)
> >   File "/work/taxi-trip/openmldb_batch.py", line 11, in run_batch_sql
> >     spark = SparkSession.builder.appName("OpenMLDB Demo").getOrCreate()
> >   File "/usr/local/lib/python3.6/site-packages/pyspark-3.0.0-py3.6.egg/pyspark/sql/session.py", line 186, in getOrCreate
> >     sc = SparkContext.getOrCreate(sparkConf)
> >   File "/usr/local/lib/python3.6/site-packages/pyspark-3.0.0-py3.6.egg/pyspark/context.py", line 371, in getOrCreate
> >     SparkContext(conf=conf or SparkConf())
> >   File "/usr/local/lib/python3.6/site-packages/pyspark-3.0.0-py3.6.egg/pyspark/context.py", line 128, in __init__
> >     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
> >   File "/usr/local/lib/python3.6/site-packages/pyspark-3.0.0-py3.6.egg/pyspark/context.py", line 320, in _ensure_initialized
> >     SparkContext._gateway = gateway or launch_gateway(conf)
> >   File "/usr/local/lib/python3.6/site-packages/pyspark-3.0.0-py3.6.egg/pyspark/java_gateway.py", line 105, in launch_gateway
> >     raise Exception("Java gateway process exited before sending its port number")
> > Exception: Java gateway process exited before sending its port number
> > [root@47647bd314d4 taxi-trip]#
> > ```
> 
> Hi @backyes, thanks for reporting.
> Just open a pr to support arm64 docker image: #194
> You can try again by running
> 
> ```shell
> docker pull ghcr.io/aceforeverd/openmldb:0.2.1-beta3
> docker run -it ghcr.io/aceforeverd/openmldb:0.2.1-beta3
> ```
> 
> we'll port the arm64 image to docker hub and other place later

@backyes  you can try the release version `docker pull mirror.baidubce.com/4pdosc/openmldb:0.2.1`
