### ISSUE TITLE
Support batch request for Python SDK

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1400]
Batch request is supported in Java SDK and API Server. We should support in Python SDK.

**Comment by HuilinWu2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve functionality of Python SDK](https://trello.com/c/xlXZPfTf/20-improve-functionality-of-python-sdk)

**Comment by HuilinWu2** [comment]
is supported by `cursor.batch_row_request(sql, common_row, parameters)`.
Then to see the result through `cursor.fetchone()`
