### ISSUE TITLE
batch: replace the deprecated registerTempTable() to reslove the compile warning

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1407]
```
[WARNING] /Users/tobe/code/4pd/OpenMLDB/java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/tobe/CheckNull.scala:56: warning: method re
gisterTempTable in class Dataset is deprecated (since 2.0.0): Use createOrReplaceTempView(viewName) instead.
[WARNING]     df.registerTempTable("t1")
[WARNING]        ^
[WARNING] /Users/tobe/code/4pd/OpenMLDB/java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/tobe/CheckNull.scala:57: warning: method re
gisterTempTable in class Dataset is deprecated (since 2.0.0): Use createOrReplaceTempView(viewName) instead.
[WARNING]     df.registerTempTable("t2")
[WARNING]        ^
```

You can reproduce the issue by compiling java modules with `mvn clean package`.

**Comment by lumianph** [comment]
this issue belongs to our Contributor Challenges program, you can redeem your rewards after your PR is merged.
https://github.com/4paradigm/OpenMLDB/issues/1344

**Comment by wangxinyu666666** [comment]
把registerTempTable替换为createOrReplaceTempView即可~

**Comment by lumianph** [comment]
> createOrReplaceTempView

pls bring your PR :-D

**Comment by lumianph** [comment]
> 把registerTempTable替换为createOrReplaceTempView即可~

pls bring your PR :-D @wangxinyu666666

**Comment by wangxinyu666666** [comment]
> > 把registerTempTable替换为createOrReplaceTempView即可~
> 
> pls bring your PR :-D @wangxinyu666666

https://github.com/4paradigm/OpenMLDB/pull/1798
