### ISSUE TITLE
batch: compile warning that check a long for null

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1408]
```
[WARNING] /Users/tobe/code/4pd/OpenMLDB/java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/WindowAggPlan.scala:530: warning: com
paring values of types Long and Null using `==' will always yield false
[WARNING]     if (key == null) {
[WARNING]             ^
```

You can reproduce the issue by compiling java modules with `mvn clean package`.

**Comment by lumianph** [comment]
this issue belongs to our Contributor Challenges program, you can redeem your rewards after your PR is merged.
https://github.com/4paradigm/OpenMLDB/issues/1344

**Comment by Ivyee17** [comment]
I want to help this!WeOpen Star
