### ISSUE TITLE
Rename `fedb` to `OpenMLDB` in some files

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1409]
Rename `fedb` to `OpenMLDB` in the following files:
- src/sdk/sql_sdk_base_test.cc  line 237
- hybridse/tools/documentation/c++_api/SUMMARY.md.tmpl line 10
- hybridse/tools/documentation/java_api/SUMMARY.md.tmpl line 10
- hybridse/tools/documentation/udf_doxygen/SUMMARY.md.tmpl  line 10

**Comment by shiyoubun** [comment]
I would like to help
