### ISSUE TITLE
Add `return` after the `switch` statement

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1410]
![WX20220310-093747](https://user-images.githubusercontent.com/6183996/157570060-8ab9c053-ce1d-472d-97bf-c42d33024300.png)

It needs to add `return` after the `switch` statement in `ShadowCopy` function. Please log error message such as 'Unsupported Data type' and return nullptr;

**Comment by cvsschaitanya** [comment]
How to reproduce the error?

**Comment by dl239** [comment]
> How to reproduce the error?

@cvsschaitanya  this is a compiling warning, please refer [compile doc](https://github.com/4paradigm/OpenMLDB/blob/main/docs/en/compile.md)

**Comment by TheFu527** [comment]
I would like to help.
