### ISSUE TITLE
Get table row count of online table

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1412]
Users may try `select * from t1;` to get the count of table `t1`. But we may truncate the scan response in tablet server(by `FLAGS_scan_max_bytes_size`).
So we should:
1. add `preview` or other cmd to get the count(sum of TableInfo), note that the count may be not accurate and why.
2. add doc about `select *` does not work well if table is big.

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.5.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-05x)
