### ISSUE TITLE
DistributedIterator

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#1419]
`DistributedIterator` can be used to iterate over the table that is partitioned into multiple tablet servers.

This can be used to:
- replace the SQLRouter in the tablet server.
- support online batch query

**Describe the solution you'd like**
An iterator interface to scan all the data in a distributed table.

**Comment by dl239** [comment]
Both `DistributedIterator`  and `FullTableIterator` are needed.
#1350
