### ISSUE TITLE
put之后scan报错

### ISSUE THREAD

**Issue by zhangjun9302** [4paradigm/OpenMLDB#142]
![image](https://user-images.githubusercontent.com/87636437/126116179-3b6313c1-eaeb-4972-9ed9-f6dbfbf4bb8b.png)
test表插入一条记录之后查询报错。
按如下文档操作的http://172.24.4.39:4000/usage/cmd.html#get
![image](https://user-images.githubusercontent.com/87636437/126116645-b215ddad-077e-427d-b8bc-0573eaa482e3.png)
![image](https://user-images.githubusercontent.com/87636437/126116719-3c9d18c3-f22a-4d9a-9d01-022008eee2f4.png)

**Comment by dl239** [comment]
ttl是多少，这个时间戳是否过期
