### ISSUE TITLE
The SDK insert of version 042 is successful, and the data is inserted online

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#1423]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

## Expected Behavior
Consistent with the command line, error messages should be prompted. Offline insertion is not supported

## Current Behavior
The SDK is in offline mode by default, but it is successfully inserted and inserted into the online table

**Comment by dl239** [comment]
`execute_mode` has no impact on sdk in 0.4.2 and can be set only by `CLI`

**Comment by lumianph** [comment]
> `execute_mode` has no impact on sdk in 0.4.2 and can be set only by `CLI`

shall we close this issue? @dl239
