### ISSUE TITLE
Add pulsar connector

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1435]
We only need to add the sink, not the source. Write to online storage.
According to  https://pulsar.apache.org/docs/en/io-develop/#sink , we should impl two methods, the schema, and package this sink connector.

Another way is to support jdbc, so we can use [JDBC sink connector](https://pulsar.apache.org/docs/en/io-jdbc-sink/), just need a config file. But we haven't support jdbc now, so we need to impl it.

**Comment by vagetablechicken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Apache Pulsar connector](https://trello.com/c/RFPkvEzM/42-apache-pulsar-connector)

**Comment by vagetablechicken** [comment]
- [x] how to use this connector, detail doc -> rfc

**Comment by lumianph** [comment]
RFC draft: https://docs.google.com/document/d/1hhiE4QPJo05cA_s-ZYkUbkm0O1XX_Y0e3kwpSs8ztsw/edit?usp=sharing

**Comment by vagetablechicken** [comment]
pulsar merged
