### ISSUE TITLE
docker: outside can't access openmldb server in container

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1441]
1. docs: how to publish the  ports in container  when using `docker run`
2. config: if other hosts want to  access server in container, default endpoint ip is 127.0.0.1, can't do that. Maybe we should convert all to 0.0.0.0

**Comment by aceforeverd** [comment]
that what #1032 comes

**Comment by vagetablechicken** [comment]
closed by #1598
