### ISSUE TITLE
job info table ，Fail to execute insert SQL 

### ISSUE THREAD

**Issue by KaidoWang** [4paradigm/OpenMLDB#1449]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

Insert Success

Fail

## Steps to Reproduce

1.
2.
3.
4.

**Comment by tobegit3hub** [comment]
It is the issue about that restarting table will not recover JOB_INFO table.

**Comment by dl239** [comment]
> It is the issue about that restarting table will not recover JOB_INFO table.

Why the JOB_INFO table has not been recovered. restart multi tablets at the same time?

**Comment by tobegit3hub** [comment]
> > It is the issue about that restarting table will not recover JOB_INFO table.
> 
> Why the JOB_INFO table has not been recovered. restart multi tablets at the same time?

We run script to start all tablets(in these case there are two tablets). Will it help if we sleep for a while after starting one tablet?

**Comment by tobegit3hub** [comment]
Resolved by upgrading tablet.
