### ISSUE TITLE
When $LANG=zh_CN.UTF-8,  taskmanager start fail

### ISSUE THREAD

**Issue by KaidoWang** [4paradigm/OpenMLDB#1450]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

Start Success

 

Only $Lang = en_US.UTF-8,taskmanager success

## Steps to Reproduce

1.
2.
3.
4.

**Comment by vagetablechicken** [comment]
the same as https://github.com/4paradigm/OpenMLDB/issues/981

**Comment by tobegit3hub** [comment]
Resolved by https://github.com/4paradigm/OpenMLDB/pull/1912 .
