### ISSUE TITLE
Hidden database  should create in standalone mode as well

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#1458]
hidden dbs should exists in standalone as well
1. __INTERNAL_DB
2. __PRE_AGG_DB
3. INFORMATION_SCHEMA

https://github.com/4paradigm/OpenMLDB/blob/420398b8349880bce262db06c3b143d023b56862/src/nameserver/name_server_impl.cc#L5448-L5494

**Comment by aceforeverd** [comment]
__PRE_AGG_DB & INFORMATION_SCHEMA should fine with standalone mode. Does __INTERNAL_DB should support standalone mode ? @tobegit3hub @dl239  It only have a `JOB_INFO` database

**Comment by aceforeverd** [comment]
@keyu813 you may have a look ~

**Comment by keyu813** [comment]
> @keyu813 you may have a look ~

ok I will fix it

**Comment by aceforeverd** [comment]
`JOB

> __PRE_AGG_DB & INFORMATION_SCHEMA should fine with standalone mode. Does __INTERNAL_DB should support standalone mode ? @tobegit3hub @dl239 It only have a `JOB_INFO` database

`JOB_INFO` only exists in cluster mode
