### ISSUE TITLE
batch: return error if `select into` gets empty

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1459]
https://github.com/4paradigm/OpenMLDB/blob/420398b8349880bce262db06c3b143d023b56862/java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/SelectIntoPlan.scala#L39-L41

If `select` closure in `select into` result is empty, we just skip saving, and the job is succeed. But users can't find the output file. It's not intuitive.
We should throw an exception.

**Comment by lumianph** [comment]
this issue belongs to our Contributor Challenges program, you can redeem your rewards after your PR is merged.
https://github.com/4paradigm/OpenMLDB/issues/1344
