### ISSUE TITLE
Update default partition number and replica num in cluster mode

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1473]
The partition num and replica num will be set to one when table created currently.
replica num: min(tablet num, 3)
partiton num: 8

**Comment by jingchen2222** [comment]
> The partition num and replica num will be set to one when table created currently. replica num: min(tablet num, 3) partiton num: 8

What if the users only have 2 tables. Will it fail for 3 replicas?

**Comment by dl239** [comment]
`min(tablet num, 3)`,  if only have 2 tablets, we will set as 2.

**Comment by dl239** [comment]
> > The partition num and replica num will be set to one when table created currently. replica num: min(tablet num, 3) partiton num: 8
> 
> What if the users only have 2 tables. Will it fail for 3 replicas?

`min(tablet_num, 3)`, if only have 2 tablets, we will set as 2.
