### ISSUE TITLE
show variables/databases return None in Python SDK 

### ISSUE THREAD

**Issue by HuilinWu2** [4paradigm/OpenMLDB#1477]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/68987242/158966446-0aa41ff3-2331-4f32-9f0f-648c89cb0467.png">

We get None in result set `_resultSet`.

**Comment by aceforeverd** [comment]
how about the result in Openmldb cli ?

**Comment by lumianph** [comment]
@HuilinWu2

**Comment by aceforeverd** [comment]
cli work as expect. Might relate to python or c -> python side.

**Comment by aceforeverd** [comment]
fixed in #1584
