### ISSUE TITLE
`setsdkendpoint` not working if server's endpoint is 0.0.0.0 or 127.0.0.1

### ISSUE THREAD

**Issue by lotabout** [4paradigm/OpenMLDB#148]
## Expected Behavior

`setsdkendpoint` should working correctly(e.g. could be connected outside docker) if nameserver/tablet's endpoint is set to `0.0.0.0` or `127.0.0.1`.

## Current Behavior

1. Both zk, nameserver, tablet are deployed inside docker.
2. nameserver/tablet's `endpoint` are set to `0.0.0.0` or `127.0.0.1`
3. The ports are exposed via docker's port mapping.
4. Java client failed to create table given docker's exposed zk port.
5. Things are fine with binary client(`./bin/fedb`) inside docker.
6. If endpoint is set to docker's IP, then everything's fine.

## Steps to Reproduce

1.
2.
3.
4.

## Detailed Description

Inside docker, the sdkendpoint is set.
![WeChatWorkScreenshot_1b414c73-867d-4848-b6d8-e48232032df6(1)](https://user-images.githubusercontent.com/1527040/126282961-1c90de4c-576f-45fc-a014-fc63b624a190.png)

Docker mappings are set:
![WeChatWorkScreenshot_714817d3-9329-4f26-975d-0a2fc024327f(1)](https://user-images.githubusercontent.com/1527040/126282991-39cce2fa-0bd3-483f-b5aa-761b9fb4531d.png)

Errors when trying to create database.
![WeChatWorkScreenshot_63099310-7a19-4422-b126-a8d9456623ee(2)](https://user-images.githubusercontent.com/1527040/126283021-243ac078-4c55-4024-9774-1a7a46d301cd.png)

**Comment by dl239** [comment]
use real IP address in endpoint
