### ISSUE TITLE
Support query offline data in cli and show result

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1480]
Now we can only get job info when executing offline sql in cmd.

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TaskManager improvement and bugfix](https://trello.com/c/raqCp82f/11-taskmanager-improvement-and-bugfix)

**Comment by lumianph** [comment]
this one can be finished in v0.5.0?
