### ISSUE TITLE
doc: update the English version of compilation

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#1491]
- The English version is out-of-date (v0.4.1): docs/en/compile.md
- Please refer to the latest Chinese version (https://openmldb.ai/docs/zh/v0.4/deploy/compile.html), and update the English version accordingly

**Comment by lumianph** [comment]
this issue belongs to our Contributor Challenges program, you can redeem your rewards after your PR is merged.
https://github.com/4paradigm/OpenMLDB/issues/1344

**Comment by cswjd** [comment]
I would like to help.
