### ISSUE TITLE
doc translation (Chinese to English): cli

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#1494]
- Translate the Chinese version to English: https://openmldb.ai/docs/zh/v0.4/reference/cli.html (you can download as a markdown file from the button at the top-right corner)
- Save the English version to docs/en/cli.md

**Comment by lumianph** [comment]
this issue belongs to our Contributor Challenges program, you can redeem your rewards after your PR is merged.
https://github.com/4paradigm/OpenMLDB/issues/1344

**Comment by cswjd** [comment]
I would like to help.
