### ISSUE TITLE
sql_client: zk "exceeded deadline by N ms" floods logs

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1500]
Ref https://issues.apache.org/jira/browse/ZOOKEEPER-642
We should support two feature:
1. set zk_session_timeout in sql_client(only sql_client haven't supported zk_session_timeout)
2. set log level of zk client in sql_client(servers don't need to remove the zk logs, only interactive client needs)

optional:
update zk c api version to 3.5.0, it'll reduce the amount of meaningless log messages.

**Comment by lumianph** [comment]
@dl239 any comments? i think either approach is fine, but the purpose is to remove the useless logs (for users) in CLI from zk.

**Comment by dl239** [comment]
there are others log such as node change log which is unnecessary in CLI, but is useful for debugging in java/python sdk. So i think it's better to set log level only in CLI.

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [删除CLI内不必要的输出信息](https://trello.com/c/03WaBLjf/23-%E5%88%A0%E9%99%A4cli%E5%86%85%E4%B8%8D%E5%BF%85%E8%A6%81%E7%9A%84%E8%BE%93%E5%87%BA%E4%BF%A1%E6%81%AF)

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.5.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-05x)
