### ISSUE TITLE
Add `override` to the method of `MultipleResultSetSQL`

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1508]
The [MultipleResultSetSQL](https://github.com/4paradigm/OpenMLDB/blob/main/src/sdk/result_set_sql.h#L103) class is derived from [::hybridse::sdk::ResultSet](https://github.com/4paradigm/OpenMLDB/blob/main/hybridse/include/sdk/result_set.h#L33), and it's better to add `override` label to the overrode method.

**Comment by lumianph** [comment]
this issue belongs to our Contributor Challenges program, you can redeem your rewards after your PR is merged.
https://github.com/4paradigm/OpenMLDB/issues/1344

**Comment by cswjd** [comment]
I would like to help.

**Comment by lumianph** [comment]
> I would like to help.

Thank you so much~

**Comment by aceforeverd** [comment]
> The [MultipleResultSetSQL](https://github.com/4paradigm/OpenMLDB/blob/main/src/sdk/result_set_sql.h#L103) class is derived from [::hybridse::sdk::ResultSet](https://github.com/4paradigm/OpenMLDB/blob/main/hybridse/include/sdk/result_set.h#L33), and it's better to add `override` label to the overrode method.

@dl239 we might need to add more strict compiler flag in CMakeLIsts as default, so those will simply be compile time error ?
