### ISSUE TITLE
resolve the dependency warning in java modules

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#1522]
**Bug Description**

![Screenshot_20220323_082152_com android chrome](https://user-images.githubusercontent.com/11715200/160317997-43513ce1-40d6-4de9-ba6a-0fbab114e86a.png)

**Expected Behavior**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-liguo](https://trello.com/c/Ut8UamBY/37-bugfix-liguo)

**Comment by aceforeverd** [comment]
there is no critical problems since 
1. hadoop upgrade may not happen, it conflict with 4paradigm/spark 's hadoop version
2. log4j problem only appear in testing tools, that is not available in production

**Comment by lumianph** [comment]
> there is no critical problems since
> 
> 1. hadoop upgrade may not happen, it conflict with 4paradigm/spark 's hadoop version
> 2. log4j problem only appear in testing tools, that is not available in production

noted with thanks.

**Comment by aceforeverd** [comment]
update with current warnings:
![wecom-temp-78ce6cfe0cc8aaf2fee4892db591ae42](https://user-images.githubusercontent.com/11715200/166905699-bfbf8312-14d7-431f-83af-6faff86b9493.png)

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs (Normal)](https://trello.com/c/WhbjlRN2/69-bugs-normal)

**Comment by aceforeverd** [comment]
Note: guava not upgraded
