### ISSUE TITLE
PRE_AGG_META table can't create in standalone mode

### ISSUE THREAD

**Issue by keyu813** [4paradigm/OpenMLDB#1523]
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/60570208/160344392-d30884bb-dac6-42d4-a3ba-34afa73d6985.png">

**Comment by aceforeverd** [comment]
Creating `INNER_DB` should appear in all modes

**Comment by keyu813** [comment]
This issue will be solved in pr #1485
