### ISSUE TITLE
support `RowBuilder` external buffer

### ISSUE THREAD

**Issue by nautaa** [4paradigm/OpenMLDB#1525]
**Describe the feature you'd like**

now, `RowBuilder` uses the internal str pointer to maintain encoded row. Like `RowView`, it should support external str buffer to encode row. So that the rows that share the same schema can use one `RowBuilder` to encode row concurrently.
```c++
int32_t GetValue(const int8_t* row, uint32_t idx, ::openmldb::type::DataType type, void* val) const;
```

**Additional context**

**Comment by aceforeverd** [comment]
sounds like need another abstract layer. Both `owned str RowBuilder` & `ref str RowBuilder` reply on same `SchemaFactory` to encode/decode rows
