### ISSUE TITLE
Recover `sp_cache` after restart the tablet

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1529]
`sp_cache` which store the compile info is not recovered after restart the tablet

**Comment by aceforeverd** [comment]
how to recover ?

**Comment by dl239** [comment]
o, `sp_cache_` has been recovered in [CreateProcedure](https://github.com/4paradigm/OpenMLDB/blob/main/src/tablet/tablet_impl.cc#L4926) which will be called in `RefreshTableInfo`
