### ISSUE TITLE
Delete java dir from `gitignore`

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1531]
hybridse/java dir has been deleted, so we should delete java dir from [gitignore](https://github.com/4paradigm/OpenMLDB/blob/main/hybridse/.gitignore)

**Comment by samyberkane04** [comment]
@dl239 
can i work on this issue please ?

**Comment by dl239** [comment]
> @dl239 can i work on this issue please ?

 of course, thank you

**Comment by lumianph** [comment]
> @dl239 can i work on this issue please ?

thank you for the contribution!

**Comment by dl239** [comment]
hi @samyberkane04 are you working for this issue?

**Comment by lumianph** [comment]
@samyberkane04 any progress on this issue?

**Comment by zjx1319** [comment]
Is anyone working on this issue? If not, I want to have a try

**Comment by aceforeverd** [comment]
> Is anyone working on this issue? If not, I want to have a try

sure, feel free to send the PR
