### ISSUE TITLE
delete unused variable and do right close

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1536]
https://github.com/4paradigm/OpenMLDB/blob/230f99b9b5744f2663b0253a87a2496c9f5ce96b/java/openmldb-taskmanager/src/main/scala/com/_4paradigm/openmldb/taskmanager/JobInfoManager.scala#L141-L170

`pstmt ` is useless, delete it. And delete `statement ` in `finally` block.

**Comment by johndinh391** [comment]
May I be assigned this task?

**Comment by vagetablechicken** [comment]
> May I be assigned this task?

👍  waiting for your pull request
