### ISSUE TITLE
当string数据量很大时使用split函数出现问题

### ISSUE THREAD

**Issue by Scarlett-xu** [4paradigm/OpenMLDB#1542]
**Bug Description**
对长度超过20000的string类型数据使用fz_split时报错：
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/55266405/160789787-ddce5ab8-a374-44a0-a378-b0306f29d330.png">

**Expected Behavior**
希望可以解决string较大时的处理

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by dl239** [comment]
the same problem as #1537
