### ISSUE TITLE
cluster_router of tablet server is only inited in cluster mode

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#1548]
**Bug Description**
SQLClusterRouter of tablet server is only inited when zookeeper config is available. 

**Expected Behavior**
- should have both SQLClusterRouter or StandaloneRouter
- or provide a function to iterate local table easily

**Comment by zhanghaohit** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [long time window - SQL engine](https://trello.com/c/0Ad2TWFJ/4-long-time-window-sql-engine)

**Comment by aceforeverd** [comment]
Just an idea, in `name_server_impl`, I use a function to lazy get `SQLClusterRouter` only in need:
https://github.com/4paradigm/OpenMLDB/blob/06ccd67533d682d58c80afa6cb151bb4f36c2ac4/src/nameserver/name_server_impl.cc#L10568
