### ISSUE TITLE
`lag()/at()/lead()` return show offset'th row, it is not related to window frame bound

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#1554]
**Bug Description**

```yaml
  - id: 6
    desc: window merge optimization
    inputs:
      - columns: [ "row_id int","ts timestamp","group1 string","val1 int" ]
        indexs: [ "index1:group1:ts" ]
        name: t1
        data: |
          1, 1612130400000, g1, 1
          2, 1612130401000, g1, 2
          3, 1612130402000, g1, 3
          4, 1612130403000, g1, 4
          5, 1612130404000, g1, 5
    sql: |
      select
      `row_id` as row_id_1,
      `row_id` as t1_row_id_original_0,
      case when !isnull(at(`val1`, 0)) over t1_group1_ts_0s_5s_10 then count_where(`val1`, `val1` = at(`val1`, 0)) over t1_group1_ts_0s_5s_10 else null end as t1_val1_window_count_1,
      case when !isnull(at(`val1`, 0)) over t1_group1_ts_1s_5s_10 then count_where(`val1`, `val1` = at(`val1`, 0)) over t1_group1_ts_1s_5s_10 else null end as t1_val1_window_count_2
      from
        `t1` WINDOW
        t1_group1_ts_0s_5s_10 as (partition by `group1` order by `ts` rows_range between 5s preceding and 0s preceding MAXSIZE 10),
        t1_group1_ts_1s_5s_10 as (partition by `group1` order by `ts` rows_range between 5s preceding and 1s preceding MAXSIZE 10);
    expect:
      columns: ["row_id_1 int", "t1_row_id_original_0 int", "t1_val1_window_count_1 int64", "t1_val1_window_count_2 int64"]
      order: row_id_1
      data: |
        1, 1, 1, 0
        2, 2, 1, 0
        3, 3, 1, 0
        4, 4, 1, 0
        5, 5, 1, 0
```

**Expected Behavior**

the case should pass. Current result is not:

```log
+----------+----------------------+------------------------+------------------------+
| row_id_1 | t1_row_id_original_0 | t1_val1_window_count_1 | t1_val1_window_count_2 |
+----------+----------------------+------------------------+------------------------+
| 1        | 1                    | 1                      | NULL                   |
| 2        | 2                    | 1                      | NULL                   |
| 3        | 3                    | 1                      | NULL                   |
| 4        | 4                    | 1                      | NULL                   |
| 5        | 5                    | 1                      | NULL                   |
+----------+----------------------+------------------------+------------------------+
```

**Work List**
- [x] add extra handling in logic plan for `lag` functions
  - working in #1605 
- [x] fix lag correctness in request mode & cluster environment
- [x] fix window merge result correctness ( may related to #1587 )

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs](https://trello.com/c/h7opm5kE/45-high-priority-bugs)

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-liguo](https://trello.com/c/Ut8UamBY/37-bugfix-liguo)

**Comment by aceforeverd** [comment]
the problem might be complex, I just have a look for `at()` function (which is alias for `lag()`) currently:

### the output for SQL: 

```sql
      select
      `row_id` as row_id_1,
      `row_id` as t1_row_id_original_0,
      `val1` as val1,
      lag(`val1`, 0) over t1_group1_ts_1s_5s_10 as t1_val1_window_count_2
      from `t1` WINDOW
        t1_group1_ts_1s_5s_10 as (partition by `group1` order by `ts` rows_range between 5s preceding and 1s preceding MAXSIZE 10);
```
is:
```
+-----------------+----------+----------------------+------+------------------------+
| MemTableHandler | row_id_1 | t1_row_id_original_0 | val1 | t1_val1_window_count_2 |
+-----------------+----------+----------------------+------+------------------------+
| 0               | 1        | 1                    | 1    | NULL                   |
| 1               | 2        | 2                    | 2    | 1                      |
| 2               | 3        | 3                    | 3    | 2                      |
| 3               | 4        | 4                    | 4    | 3                      |
| 4               | 5        | 5                    | 5    | 4                      |
+-----------------+----------+----------------------+------+------------------------+
```

here `lag(val1, 0)` returns the first row in window, that feels not corret. I tested MySQL, and the meaning there is just `offset`th row relative to current row:
```
MariaDB [test]> select id, ts, `group`, lag(val, 0) over (partition by `group` order by ts rows between 5 preceding and 1 preceding) as l from t1;
+----+-----+-------+------+
| id | ts  | group | l    |
+----+-----+-------+------+
|  1 | 100 | g1    |    1 |
|  2 | 200 | g1    |    2 |
|  3 | 300 | g1    |    3 |
|  4 | 400 | g1    |    4 |
|  5 | 500 | g1    |    5 |
+----+-----+-------+------+
5 rows in set (0.000 sec)

MariaDB [test]> select id, ts, `group`, lag(val, 1) over (partition by `group` order by ts rows between 5 preceding and 1 preceding) as l from t1;
+----+-----+-------+------+
| id | ts  | group | l    |
+----+-----+-------+------+
|  1 | 100 | g1    | NULL |
|  2 | 200 | g1    |    1 |
|  3 | 300 | g1    |    2 |
|  4 | 400 | g1    |    3 |
|  5 | 500 | g1    |    4 |
+----+-----+-------+------+
5 rows in set (0.000 sec)
```

SparkSQL do not support lag over window frame, so there is no standard from spark. But to get first or nth row in window, there is `first_value` or `nth_value` in spark. 
Do we have detailed definition for `lag` @jingchen2222  @tobegit3hub 🌝

other reference:
- https://docs.microsoft.com/en-us/sql/t-sql/functions/lag-transact-sql?view=sql-server-ver15

**Comment by aceforeverd** [comment]
previous definition for `lag` and `lead`: https://github.com/4paradigm/OpenMLDB/issues/265

**Comment by aceforeverd** [comment]
the documents seems not correct or accurate

https://github.com/4paradigm/OpenMLDB/blob/06ccd67533d682d58c80afa6cb151bb4f36c2ac4/hybridse/src/udf/default_defs/window_functions_def.cc#L97-L115

**Comment by aceforeverd** [comment]
> **Bug Description**
> 
> ```yaml
>   - id: 6
>     desc: window merge optimization
>     inputs:
>       - columns: [ "row_id int","ts timestamp","group1 string","val1 int" ]
>         indexs: [ "index1:group1:ts" ]
>         name: t1
>         data: |
>           1, 1612130400000, g1, 1
>           2, 1612130401000, g1, 2
>           3, 1612130402000, g1, 3
>           4, 1612130403000, g1, 4
>           5, 1612130404000, g1, 5
>     sql: |
>       select
>       `row_id` as row_id_1,
>       `row_id` as t1_row_id_original_0,
>       case when !isnull(at(`val1`, 0)) over t1_group1_ts_0s_5s_10 then count_where(`val1`, `val1` = at(`val1`, 0)) over t1_group1_ts_0s_5s_10 else null end as t1_val1_window_count_1,
>       case when !isnull(at(`val1`, 0)) over t1_group1_ts_1s_5s_10 then count_where(`val1`, `val1` = at(`val1`, 0)) over t1_group1_ts_1s_5s_10 else null end as t1_val1_window_count_2
>       from
>         `t1` WINDOW
>         t1_group1_ts_0s_5s_10 as (partition by `group1` order by `ts` rows_range between 5s preceding and 0s preceding MAXSIZE 10),
>         t1_group1_ts_1s_5s_10 as (partition by `group1` order by `ts` rows_range between 5s preceding and 1s preceding MAXSIZE 10);
>     expect:
>       columns: ["row_id_1 int", "t1_row_id_original_0 int", "t1_val1_window_count_1 int64", "t1_val1_window_count_2 int64"]
>       order: row_id_1
>       data: |
>         1, 1, 1, NULL
>         2, 2, 1, 1
>         3, 3, 1, 1
>         4, 4, 1, 1
>         5, 5, 1, 1
> ```
> 
> **Expected Behavior**
> 
> the case should pass. Current result is not:
> 
> ```
> +----------+----------------------+------------------------+------------------------+
> | row_id_1 | t1_row_id_original_0 | t1_val1_window_count_1 | t1_val1_window_count_2 |
> +----------+----------------------+------------------------+------------------------+
> | 1        | 1                    | 1                      | NULL                   |
> | 2        | 2                    | 1                      | NULL                   |
> | 3        | 3                    | 1                      | NULL                   |
> | 4        | 4                    | 1                      | NULL                   |
> | 5        | 5                    | 1                      | NULL                   |
> +----------+----------------------+------------------------+------------------------+
> ```
> 
> **Steps to Reproduce**

neither the yaml case is correct. actual result should be:
```
        1, 1, 1, 0
        2, 2, 1, 0
        3, 3, 1, 0
        4, 4, 1, 0
        5, 5, 1, 0
```

`at(val1, 0)` refer to current row, so `!isnull(at(val1, 0))` always true. And since the second window is above current row absolutely, `count_where` always have zero match

**Comment by lumianph** [comment]
@jingchen2222 can you help take a look, and probably give some suggestions where we should look into this issue?

**Comment by jingchen2222** [comment]
> the problem might be complex, I just have a look for `at()` function (which is alias for `lag()`) currently:
> 
> ### the output for SQL:
> ```sql
>       select
>       `row_id` as row_id_1,
>       `row_id` as t1_row_id_original_0,
>       `val1` as val1,
>       lag(`val1`, 0) over t1_group1_ts_1s_5s_10 as t1_val1_window_count_2
>       from `t1` WINDOW
>         t1_group1_ts_1s_5s_10 as (partition by `group1` order by `ts` rows_range between 5s preceding and 1s preceding MAXSIZE 10);
> ```
> 
> is:
> 
> ```
> +-----------------+----------+----------------------+------+------------------------+
> | MemTableHandler | row_id_1 | t1_row_id_original_0 | val1 | t1_val1_window_count_2 |
> +-----------------+----------+----------------------+------+------------------------+
> | 0               | 1        | 1                    | 1    | NULL                   |
> | 1               | 2        | 2                    | 2    | 1                      |
> | 2               | 3        | 3                    | 3    | 2                      |
> | 3               | 4        | 4                    | 4    | 3                      |
> | 4               | 5        | 5                    | 5    | 4                      |
> +-----------------+----------+----------------------+------+------------------------+
> ```
> 
> here `lag(val1, 0)` returns the first row in window, that feels not corret. I tested MySQL, and the meaning there is just `offset`th row relative to current row:
> 
> ```
> MariaDB [test]> select id, ts, `group`, lag(val, 0) over (partition by `group` order by ts rows between 5 preceding and 1 preceding) as l from t1;
> +----+-----+-------+------+
> | id | ts  | group | l    |
> +----+-----+-------+------+
> |  1 | 100 | g1    |    1 |
> |  2 | 200 | g1    |    2 |
> |  3 | 300 | g1    |    3 |
> |  4 | 400 | g1    |    4 |
> |  5 | 500 | g1    |    5 |
> +----+-----+-------+------+
> 5 rows in set (0.000 sec)
> 
> MariaDB [test]> select id, ts, `group`, lag(val, 1) over (partition by `group` order by ts rows between 5 preceding and 1 preceding) as l from t1;
> +----+-----+-------+------+
> | id | ts  | group | l    |
> +----+-----+-------+------+
> |  1 | 100 | g1    | NULL |
> |  2 | 200 | g1    |    1 |
> |  3 | 300 | g1    |    2 |
> |  4 | 400 | g1    |    3 |
> |  5 | 500 | g1    |    4 |
> +----+-----+-------+------+
> 5 rows in set (0.000 sec)
> ```
> 
> SparkSQL do not support lag over window frame, so there is no standard from spark. But to get first or nth row in window, there is `first_value` or `nth_value` in spark. Do we have detailed definition for `lag` @jingchen2222 @tobegit3hub 🌝
> 
> other reference:
> 
> * https://docs.microsoft.com/en-us/sql/t-sql/functions/lag-transact-sql?view=sql-server-ver15

@aceforeverd You're right. The lag should have returned the expression of the row preceding n offset from the current row. The current implementation of the `lag` function, however, is based on the expression of the row preceding n offset from the start row of the window.

I think it would be a tough job.
@lumianph @aceforeverd @tobegit3hub 
I suggest that **firstly** **we can put a restriction on the usage of the `lag` function.** That is the `lag` function can only be used when the associated a CurrentHisotryWindow. (a window rows/rows_range between x preceding and current row)
```sql
select id, ts, `group`, lag(val, 1) over (partition by `group` order by ts rows between 5 preceding and current row) as l from t1;
```

Secondly, fix the `lag` expression over a pure history window, a window excludes the current row. 
```sql
select id, ts, `group`, lag(val, 1) over (partition by `group` order by ts rows between 5 preceding and 2 preceding) as l from t1;
```
  - We should extend the pure history window to a CurrentHisotryWindow. And then you should pass the extended window instead of the pure history window to the `lag` function 
  - This might introduces some changes to the [HistroyWindow](https://github.com/4paradigm/OpenMLDB/blob/release/0.4.0/hybridse/include/vm/mem_catalog.h#L366) class for BatchMode queries.
  - Consider how to construct a window for RequestMode query when the `lag` over a pure history window. We should keep in mind that simply scanning a range of rows and then union on the current row can not meet the requirement in this case.  

Things will be worse if we are trying to deal with expression as follows:
  ```select count_where(val, val != lag(val,1)) over (partition by `group` order by ts rows between 5 preceding and current row) as l from t1;```
we should pass a current history window to lag(val, 1) while pass a pure history window to count_where(val,...)

**Comment by lumianph** [comment]
@jingchen2222 thank you very much. @aceforeverd can you first help evaluate the workload. i will call a meeting to discuss the solution.

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [the window bug](https://trello.com/c/jaszXOzG/6-the-window-bug)

**Comment by aceforeverd** [comment]
> @jingchen2222 thank you very much. @aceforeverd can you first help evaluate the workload. i will call a meeting to discuss the solution.

sure

**Comment by aceforeverd** [comment]
> 
> @aceforeverd You're right. The lag should have returned the expression of the row preceding n offset from the current row. The current implementation of the `lag` function, however, is based on the expression of the row preceding n offset from the start row of the window.
> 
> I think it would be a tough job. @lumianph @aceforeverd @tobegit3hub I suggest that **firstly** **we can put a restriction on the usage of the `lag` function.** That is the `lag` function can only be used when the associated a CurrentHisotryWindow. (a window rows/rows_range between x preceding and current row)
> 
> ```sql
> select id, ts, `group`, lag(val, 1) over (partition by `group` order by ts rows between 5 preceding and current row) as l from t1;
> ```
> 
> Secondly, fix the `lag` expression over a pure history window, a window excludes the current row.
> 
> ```sql
> select id, ts, `group`, lag(val, 1) over (partition by `group` order by ts rows between 5 preceding and 2 preceding) as l from t1;
> ```
> 
> * We should extend the pure history window to a CurrentHisotryWindow. And then you should pass the extended window instead of the pure history window to the `lag` function
> * This might introduces some changes to the [HistroyWindow](https://github.com/4paradigm/OpenMLDB/blob/release/0.4.0/hybridse/include/vm/mem_catalog.h#L366) class for BatchMode queries.
> * Consider how to construct a window for RequestMode query when the `lag` over a pure history window. We should keep in mind that simply scanning a range of rows and then union on the current row can not meet the requirement in this case.
> 
> Things will be worse if we are trying to deal with expression as follows: `` select count_where(val, val != lag(val,1)) over (partition by `group` order by ts rows between 5 preceding and current row) as l from t1; `` we should pass a current history window to lag(val, 1) while pass a pure history window to count_where(val,...)

Thank you ~. Since the problem is the `offset` in `lag` appears out-of-range of window frame bound, so it is also possible for `offset` to be beyond window upper bound. Hence I'm thinking giving all `lag/at` function the same window frame as `UNBOUND AND CURRENT ROW`

It is some kind misleading in SQL view as `lag` is actually not related to window frame bound

**Comment by aceforeverd** [comment]
The first thing I'd like to do is in the Planner when transform from `SQLNote`, will create a separate window for all `at/lag` project by its `order` and `partition`, but make frame `unbound preceding and current row`.

Meanwhile SQL engine should support the syntax without window frame or even without partition by, e.g `select lag(row) over (order by col1 partition by col2) from t1;`, as it is the encouraged way to use `lag` function.

**Comment by aceforeverd** [comment]
> @aceforeverd You're right. The lag should have returned the expression of the row preceding n offset from the current row. The current implementation of the `lag` function, however, is based on the expression of the row preceding n offset from the start row of the window.
> 
> I think it would be a tough job. @lumianph @aceforeverd @tobegit3hub I suggest that **firstly** **we can put a restriction on the usage of the `lag` function.** That is the `lag` function can only be used when the associated a CurrentHisotryWindow. (a window rows/rows_range between x preceding and current row)
> 
> ```sql
> select id, ts, `group`, lag(val, 1) over (partition by `group` order by ts rows between 5 preceding and current row) as l from t1;
> ```
> 
> Secondly, fix the `lag` expression over a pure history window, a window excludes the current row.
> 
> ```sql
> select id, ts, `group`, lag(val, 1) over (partition by `group` order by ts rows between 5 preceding and 2 preceding) as l from t1;
> ```
> 
> * We should extend the pure history window to a CurrentHisotryWindow. And then you should pass the extended window instead of the pure history window to the `lag` function
> * This might introduces some changes to the [HistroyWindow](https://github.com/4paradigm/OpenMLDB/blob/release/0.4.0/hybridse/include/vm/mem_catalog.h#L366) class for BatchMode queries.
> * Consider how to construct a window for RequestMode query when the `lag` over a pure history window. We should keep in mind that simply scanning a range of rows and then union on the current row can not meet the requirement in this case.
> 
@jingchen2222  I can't understand the third point though

> Things will be worse if we are trying to deal with expression as follows: `` select count_where(val, val != lag(val,1)) over (partition by `group` order by ts rows between 5 preceding and current row) as l from t1; `` we should pass a current history window to lag(val, 1) while pass a pure history window to count_where(val,...)

**Comment by jingchen2222** [comment]
> thinking giving all `lag/at` function the same window frame as `UNBOUND AND CURRENT ROW`

Giving all lag/at function the same window frame as UNBOUND AND CURRENT ROW might introduce another problem.
That is the unpredictable performance of an unbounded window especially when the dataset contains hundreds and thousands of rows associated with one key?

**Comment by aceforeverd** [comment]
> > thinking giving all `lag/at` function the same window frame as `UNBOUND AND CURRENT ROW`
> 
> Giving all lag/at function the same window frame as UNBOUND AND CURRENT ROW might introduce another problem. That is the unpredictable performance of an unbounded window especially when the dataset contains hundreds and thousands of rows associated with one key?

Yeah. We do not seem to have restriction for the type of `offset`, so it is not determined on compile time how big the `offset` value will be. If `offset` is restricted to integer or simple expr that can transformed to integer in compile time, it may do some optimization for `lag`'s window ?

**Comment by zhanghaohit** [comment]
> > > thinking giving all `lag/at` function the same window frame as `UNBOUND AND CURRENT ROW`
> > 
> > 
> > Giving all lag/at function the same window frame as UNBOUND AND CURRENT ROW might introduce another problem. That is the unpredictable performance of an unbounded window especially when the dataset contains hundreds and thousands of rows associated with one key?
> 
> Yeah. We do not seem to have restriction for the type of `offset`, so it is not determined on compile time how big the `offset` value will be. If `offset` is restricted to integer or simple expr that can transformed to integer in compile time, it may do some optimization for `lag`'s window ?

`offset` can be something that can only be known at runtime? Support type is not like this?
```
Supported Types:
[list<bool>, int64]
[list<date>, int64]
[list<number>, int64]
[list<string>, int64]
[list<timestamp>, int64]
```

**Comment by aceforeverd** [comment]
> 
> `offset` can be something that can only be known at runtime? Support type is not like this?
> 
> ```
> Supported Types:
> [list<bool>, int64]
> [list<date>, int64]
> [list<number>, int64]
> [list<string>, int64]
> [list<timestamp>, int64]
> ```
yeah, it is runnable e.g `lag(col1, lag(col2, 1))`, I think we just need `lag(col, 0)` or `lag(col, 1+1)`. Meanwhile, spark sql seems do the same restriction.
