### ISSUE TITLE
创建索引后，desc不展示ttl的值

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#156]
## Expected Behavior
期望结果，在desc时展示ttl的值

## Current Behavior
![wecom-temp-4158b1c407045be244b401799de6f484](https://user-images.githubusercontent.com/18275570/126605797-ee0f5d82-1af4-401c-8482-53c1cfa1198a.png)

## Steps to Reproduce
1.先创建一个带索引的表
2.在单独创建索引
3.desc

**Comment by wuyou10206** [comment]
![wecom-temp-3b112b480b2964f1459cf2bf899f09b9](https://user-images.githubusercontent.com/18275570/126746775-317e4775-fbaf-46f1-b63c-73a5426ea10f.png)
![wecom-temp-971bee34baebbf1d1f99d1409156212f](https://user-images.githubusercontent.com/18275570/126746788-7b87108d-0499-48a4-a7a8-842ef0df025b.png)
<img width="530" alt="wecom-temp-357a697bf55c4f360db98d0f36beaa8d" src="https://user-images.githubusercontent.com/18275570/126746806-b51292e1-fafb-41c5-bc63-fd1c45923a79.png">

**Comment by vagetablechicken** [comment]
sql client HandleCreateIndex fixed.
how about ns client HandleNSClientAddIndex? -- do not change.
