### ISSUE TITLE
Create PreAggrTables in standalone mode

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#1560]
**Bug Description**
Only in cluster mode, it will create pre-aggr tables. We should do it also in standalone mode.

**Comment by zhanghaohit** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [long time window - compute engine](https://trello.com/c/XMMF5TXl/6-long-time-window-compute-engine)

**Comment by aceforeverd** [comment]
https://github.com/4paradigm/OpenMLDB/blob/06ccd67533d682d58c80afa6cb151bb4f36c2ac4/src/nameserver/name_server_impl.cc#L5491-L5511 maybe I just fixed it before in #1497

**Comment by aceforeverd** [comment]
> https://github.com/4paradigm/OpenMLDB/blob/06ccd67533d682d58c80afa6cb151bb4f36c2ac4/src/nameserver/name_server_impl.cc#L5491-L5511
> 
> maybe I just fixed it before in #1497

No I don't 😅
