### ISSUE TITLE
taskmanager: registerOpenmldbOfflineTable should use options

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1565]
https://github.com/4paradigm/OpenMLDB/blob/ba4c408c1b4dd9c488e31308b33044ccab988a07/java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/api/OpenmldbSession.scala#L269

Now we can't read offline path with options. e.g. when soft copy, csv file has header, but `spark.read.csv()` won't parse header. And we can't load without header, it's no schema(col name, type name).

**Comment by aceforeverd** [comment]
any idea how to fix it @vagetablechicken ?

**Comment by vagetablechicken** [comment]
> any idea how to fix it @vagetablechicken ?

Just use format, path, options, schema to read files in offline storage. It's similar with `autoLoad`.

**Comment by vagetablechicken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [talkingdata demo](https://trello.com/c/RphJ2gvS/48-talkingdata-demo)

**Comment by lumianph** [comment]
this issue may be fixed asap
