### ISSUE TITLE
Execute load data failed on standalone mode

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1567]
<img width="956" alt="WX20220401-225323@2x" src="https://user-images.githubusercontent.com/6183996/161288403-b4b1b863-2b7e-475c-87f8-8d02530805b7.png">

**Comment by lumianph** [comment]
it looks like `use` is not working?

**Comment by dl239** [comment]
> it looks like `use` is not working?

the db passed to load data function is not correct
