### ISSUE TITLE
default udf `sum/sum_where/avg/avg_where` should return NULL if no rows in range or all values is NULL

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#1586]
**Bug Description**

currently the `sum()` is defined with init value `0`, https://github.com/4paradigm/OpenMLDB/blob/f5fc988a38d0d9b8952155cdfe9d782133502e46/hybridse/src/udf/default_udf_library.cc#L99-L103, which should be `NULL` instead.

The same situation apply to `sum_where/avg/avg_where`. For `count/count_where`, it is correct to have `0` as init value 

a example test case:
```yaml
  - id: 15
    desc: sum correctness when no rows in range or value is all null
    inputs:
      - columns: [ "row_id int","ts timestamp","group1 string","val1 int" ]
        indexs: [ "index1:group1:ts" ]
        name: t1
        data: |
          1, 1612130400000, g1, NULL
          2, 1612130401000, g1, 2
          3, 1612130402000, g2, 3
          4, 1612130403000, g2, 4
          5, 1612130404000, g2, 5
    sql: |
      select
      `row_id`,
      `val1`,
      sum(val1) over w1 as agg1,
      from `t1` WINDOW
        w1 as (partition by `group1` order by `ts` rows_range between 5s preceding and 0s preceding MAXSIZE 10);
    expect:
      columns: ["row_id int", "val1 int", "agg1 int"]
      order: row_id
      data: |
        1, 1, NULL
        2, 2, 2
        3, 3, 3
        4, 4, 7
        5, 5, 12
```

**Expected Behavior**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by zhanghaohit** [comment]
pre-aggregation logics (in `src/storage/aggregation` and `hybridse/vm/aggregation`) should be updated too.

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.5.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-05x)
