### ISSUE TITLE
`at/lag/first_value` udf function over merged window report different result compared to those not merged

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#1587]
**Bug Description**

two compared case: 
1.  case one
```yaml
  - id: 6
    desc: window merge optimization
    inputs:
      - columns: [ "row_id int","ts timestamp","group1 string","val1 int" ]
        indexs: [ "index1:group1:ts" ]
        name: t1
        data: |
          1, 1612130400000, g1, 1
          2, 1612130401000, g1, 2
          3, 1612130402000, g1, 3
          4, 1612130403000, g1, 4
          5, 1612130404000, g1, 5
    sql: |
      select
      `row_id`,
      `val1`,
      lag(`val1`, 0) over w1 as agg1,
      lag(`val1`, 0) over w2 as agg2
      from `t1` WINDOW
        w1 as (partition by `group1` order by `ts` rows_range between 5s preceding and 0s preceding MAXSIZE 10),
        w2 as (partition by `group1` order by `ts` rows_range between 5s preceding and 1s preceding MAXSIZE 10);
```

2.   case two
 ```yaml
  - id: 6
    desc: window merge optimization
    inputs:
      - columns: [ "row_id int","ts timestamp","group1 string","val1 int" ]
        indexs: [ "index1:group1:ts" ]
        name: t1
        data: |
          1, 1612130400000, g1, 1
          2, 1612130401000, g1, 2
          3, 1612130402000, g1, 3
          4, 1612130403000, g1, 4
          5, 1612130404000, g1, 5
    sql: |
      select
      `row_id`,
      `val1`,
      lag(`val1`, 0) over w2 as agg2
      from `t1` WINDOW
        w2 as (partition by `group1` order by `ts` rows_range between 5s preceding and 1s preceding MAXSIZE 10);
```

in case two , `lag(val1, 0) over w1` will produce series `NULL, 1, 2, 3, 4`, while in case one, it produce `NULL, NULL , NULL, NULL, NULL` instead. 

The case do not concern correctness of `lag` function but the consistency of two similar windows before and after merged in compilation, for lag correctness refer #1554 

**Expected Behavior**

**Steps to Reproduce**

1. 
2. 
4. 
5.

**Comment by aceforeverd** [comment]
since `lag` result may not correct, the case should use `first_value` instead:
```yaml
  - id: 6
    desc: window merge optimization
    inputs:
      - columns: [ "row_id int","ts timestamp","group1 string","val1 int" ]
        indexs: [ "index1:group1:ts" ]
        name: t1
        data: |
          1, 1612130400000, g1, 1
          2, 1612130401000, g1, 2
          3, 1612130402000, g1, 3
          4, 1612130403000, g1, 4
          5, 1612130404000, g1, 5
    sql: |
      select
      `row_id`,
      `val1`,
      first_value(`val1`) over w1 as agg1,
      first_value(`val1`) over w2 as agg2
      from `t1` WINDOW
        w1 as (partition by `group1` order by `ts` rows_range between 5s preceding and 0s preceding MAXSIZE 10),
        w2 as (partition by `group1` order by `ts` rows_range between 5s preceding and 1s preceding MAXSIZE 10);
    expect:
      columns: ["row_id int", "val1 int", "agg1 int", "agg2 int"]
      order: row_id_1
      data: |
        1, 1, 1, NULL
        2, 2, 2, 1
        3, 3, 3, 2
        4, 4, 4, 3
        5, 5, 5, 4
```

it only happens in `rows_range` window, two `rows` window works fine

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs](https://trello.com/c/h7opm5kE/45-high-priority-bugs)

**Comment by tobegit3hub** [comment]
We have the similar issue when executing `at` function for merged window. This SQL will crash in offline when enable UnsafeRowOpt.

```
select
    count(`f_cLength`) over w1,
    count(`f_cId`) over w2,
    case when !isnull(at(`f_cSrc`, 0)) over w3 then count(`f_cSrc`) over w3 else null end
from
    `t1`
window w1 as (partition by `f_requestId` order by `eventTime` rows_range between 604800999 preceding and 0s preceding),
       w2 as (partition by `f_uId` order by `eventTime` rows between 9 preceding and 0 preceding),
       w3 as (partition by `f_uId` order by `eventTime` rows_range between 604800999 preceding and 0s preceding)
```

Here is the test data.

```
    val data = Seq(
      Row(1.0, "a", "b", "c", new Timestamp(1480464000000L), "d")
    )
    val schema = StructType(List(
      StructField("f_cLength", DoubleType),
      StructField("f_cId", StringType),
      StructField("f_cSrc", StringType),
      StructField("f_requestId", StringType),
      StructField("eventTime", TimestampType),
      StructField("f_uId", StringType)))
    val df = spark.createDataFrame(spark.sparkContext.makeRDD(data), schema)
    sess.registerTable("t1", df)
```

However, we can get expected result when disabling UnsafeRowOpt.

```
+-----------------------+-------------------+--------------------------------------------------------------------------------+
|count(f_cLength)over w1|count(f_cId)over w2|case (when NOT isnull(at(f_cSrc, 0))over w3 then count(f_cSrc)over w3) else null|
+-----------------------+-------------------+--------------------------------------------------------------------------------+
|                      1|                  1|                                                                               1|
+-----------------------+-------------------+--------------------------------------------------------------------------------+
```

Refer to https://github.com/4paradigm/OpenMLDB/issues/1638 .

**Comment by aceforeverd** [comment]
> 

the case works in sql engine.

**Comment by aceforeverd** [comment]
> We have the similar issue when executing `at` function for merged window. This SQL will crash in offline when enable UnsafeRowOpt.
> 
> ```
> select
>     count(`f_cLength`) over w1,
>     count(`f_cId`) over w2,
>     case when !isnull(at(`f_cSrc`, 0)) over w3 then count(`f_cSrc`) over w3 else null end
> from
>     `t1`
> window w1 as (partition by `f_requestId` order by `eventTime` rows_range between 604800999 preceding and 0s preceding),
>        w2 as (partition by `f_uId` order by `eventTime` rows between 9 preceding and 0 preceding),
>        w3 as (partition by `f_uId` order by `eventTime` rows_range between 604800999 preceding and 0s preceding)
> ```
> 
> Here is the test data.
> 
> ```
>     val data = Seq(
>       Row(1.0, "a", "b", "c", new Timestamp(1480464000000L), "d")
>     )
>     val schema = StructType(List(
>       StructField("f_cLength", DoubleType),
>       StructField("f_cId", StringType),
>       StructField("f_cSrc", StringType),
>       StructField("f_requestId", StringType),
>       StructField("eventTime", TimestampType),
>       StructField("f_uId", StringType)))
>     val df = spark.createDataFrame(spark.sparkContext.makeRDD(data), schema)
>     sess.registerTable("t1", df)
> ```
> 
> However, we can get expected result when disabling UnsafeRowOpt.
> 
> ```
> +-----------------------+-------------------+--------------------------------------------------------------------------------+
> |count(f_cLength)over w1|count(f_cId)over w2|case (when NOT isnull(at(f_cSrc, 0))over w3 then count(f_cSrc)over w3) else null|
> +-----------------------+-------------------+--------------------------------------------------------------------------------+
> |                      1|                  1|                                                                               1|
> +-----------------------+-------------------+--------------------------------------------------------------------------------+
> ```
> 
> Refer to #1638 .

the case runs correctly in sql engine
