### ISSUE TITLE
select * will have wrong result when set partitionnum = 8 and replicanum = 3

### ISSUE THREAD

**Issue by keyu813** [4paradigm/OpenMLDB#1590]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/60570208/162188716-f4bd2c07-e8a8-409e-a2eb-98e741181fc2.png">
expect only one line but return three lines

**Comment by aceforeverd** [comment]
bacause replicanum = 3

**Comment by keyu813** [comment]
> bacause replicanum = 3

so it's valid？

**Comment by aceforeverd** [comment]
@dl239 may explain

> > bacause replicanum = 3
> 
> so it's valid？

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs](https://trello.com/c/h7opm5kE/45-high-priority-bugs)
