### ISSUE TITLE
when select table, row set disappear

### ISSUE THREAD

**Issue by KaidoWang** [4paradigm/OpenMLDB#1599]
**Bug Description**
<img width="712" alt="企业微信截图_1edd4083-e392-4555-b5de-fdfd4a60763a" src="https://user-images.githubusercontent.com/37789023/162400989-98a1759f-dc95-440d-9cd7-19c69620459b.png">

**Expected Behavior**
<img width="394" alt="image" src="https://user-images.githubusercontent.com/37789023/162401117-9c2abf28-7a82-49de-85cf-48fa9b1dda3a.png">

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by aceforeverd** [comment]
can't understand, pls describe in detail

**Comment by KaidoWang** [comment]
> 

last line,1 row in set now disappear
