### ISSUE TITLE
创建索引时，当ttl_type=latest,ttl=1d,期望返回错误信息，实际创建成功

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#161]
## Expected Behavior
返回错误信息
## Current Behavior
实际创建成功
![wecom-temp-d43053438f6714914779235a9ff8a55c](https://user-images.githubusercontent.com/18275570/126753798-a3d98299-4f85-4366-ae7e-eda573d8940e.png)

**Comment by dl239** [comment]
fixed
![Uploading WX20220106-155308.png…]()
