### ISSUE TITLE
MemTableWindowIterator::Seek will not set record_idx_ properly

### ISSUE THREAD

**Issue by Leowner** [4paradigm/OpenMLDB#1624]
**Bug Description**

In `MemTableWindowIterator::Seek` and `DiskTableRowIterator::Seek`, it doesn't set `record_idx_`. Which means it will be inaccurate in `Valid` function with latest ttltype.

**Expected Behavior**
 For `Seek`, We have to do the following to make it right:
1. `SeekToFirst`
1. `Next` until `ts == key` while checking valid

**Comment by aceforeverd** [comment]
will you fix ? @Leowner

**Comment by zhanghaohit** [comment]
> will you fix ? @Leowner

Yes. We'll fix it later.

**Comment by dl239** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.5.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-05x)
