### ISSUE TITLE
standalone python sdk,show deployment deployname, RS error

### ISSUE THREAD

**Issue by KaidoWang** [4paradigm/OpenMLDB#1630]
**Bug Description**
This result object does not return rows. It has been closed automatically.

**Expected Behavior**
return information about deployment

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by aceforeverd** [comment]
should resolved already in #1584
@KaidoWang pls provide a few testing code so we can dig more

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Python SDK enhancement](https://trello.com/c/xlXZPfTf/20-python-sdk-enhancement)

**Comment by tobegit3hub** [comment]
Thanks @aceforeverd . I have test with the latest package and this has been fixed.
