### ISSUE TITLE
recover global var failed when restart cluster

### ISSUE THREAD

**Issue by keyu813** [4paradigm/OpenMLDB#1633]
<img width="333" alt="image" src="https://user-images.githubusercontent.com/60570208/163539952-de2f4296-1c69-464f-a779-3ab5ca14767d.png">
steps：

1. start onebox, globalvar init succeed

2. stop onebox and restart onebox, global recover failed

**Comment by aceforeverd** [comment]
I got the same problem sometimes in #1641

**Comment by aceforeverd** [comment]
I got the problem when there are old files of previous tablet/nameserver data, e.g `tablet*/recycle-bin*`. 
Delete those files and start a fresh cluster won't fail. So this might related to recovery

**Comment by keyu813** [comment]
GlobalVarTable support  recover when some tablets offline, don't support recover if all tablets failed yet
<img width="831" alt="image" src="https://user-images.githubusercontent.com/60570208/164451895-cbc50b03-b03d-4d3a-bede-8bf299f51ef4.png">
<img width="366" alt="image" src="https://user-images.githubusercontent.com/60570208/164451966-e131dae0-1265-47b1-bf4e-dd4783f8cac7.png">
