### ISSUE TITLE
feat: Add a UDF function similar to Hive get_json_object

### ISSUE THREAD

**Issue by kitty-eu-org** [4paradigm/OpenMLDB#1639]
**Describe the feature you'd like**

Add a UDF function similar to hive's get_json_object function, input json string, and output the parsed string

**Additional context**

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/46663318/163578149-429859a2-44d9-42eb-8a27-7cb58bfea18e.png">

**Comment by aceforeverd** [comment]
thank you. This will be part of built-in json functions

**Comment by aceforeverd** [comment]
@hezhaozhao-git Hi, I'm adding the `get_object_function` in #3429, the main difference with hive's `get_json_object` is the second parameter, for openmldb, it is the JSON string representation from https://datatracker.ietf.org/doc/html/rfc6901.

 check it out if you're still interested :)
