### ISSUE TITLE
创建索引时，相同key和ts，需要验证一致性

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#164]
## Expected Behavior
相同的key和ts，创建索引时，创建失败并提示错误信息

## Current Behavior
可以创建成功

## Detailed Description
![image](https://user-images.githubusercontent.com/18275570/126767312-925da2dd-2cce-42b6-8627-bac386bb2899.png)

**Comment by dl239** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [make "create index" fully functional](https://trello.com/c/YGkh6XW3/12-make-create-index-fully-functional)
