### ISSUE TITLE
Fail to execute `create database if not exists` in SDK

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1646]
Now we can use `create database if not exists` but not in SDK.

Test with Java SDK and get the following error.

<img width="914" alt="Screen Shot 2022-04-14 at 6 21 28 PM" src="https://user-images.githubusercontent.com/2715000/163746832-11b042a9-9a8a-471b-a7d1-2218e75b723b.png">

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-dihao](https://trello.com/c/NcZTvHzh/16-bugfix-dihao)

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Python SDK enhancement](https://trello.com/c/xlXZPfTf/20-python-sdk-enhancement)

**Comment by tobegit3hub** [comment]
Test with latest package for Java SDK and Python SDK and it works like a charm.
