### ISSUE TITLE
build: fix the message when icu package not found

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1648]
https://github.com/4paradigm/OpenMLDB/blob/3fc54ff04164cd1bc368ad451b1ee55a1e08abc5/CMakeLists.txt#L208-L210

If we can't find icu package, we will try to find the libraries one by one.
But the message is confused, users might think it's a build error. Plz fix it.

e.g.
"ICU package Not Found" -> "ICU find_package failed, try to use find_library to find"

**Comment by lumianph** [comment]
this issue should be closed? @vagetablechicken @aceforeverd

**Comment by aceforeverd** [comment]
resolved in #1651
