### ISSUE TITLE
创建索引后，select使用window报错

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#165]
## Expected Behavior
应该正常查询
## Current Behavior
查询失败

## Possible Solution
怀疑可能新创建的索引，在window中不能别识别

## Steps to Reproduce
1. 创建表
2. 插入数据
3. 创建索引
4. 使用新索引 构造window查询

## Detailed Description
![image](https://user-images.githubusercontent.com/18275570/126768444-fe0433e0-eea9-49d9-8e66-b6deecfb3c0a.png)
![image](https://user-images.githubusercontent.com/18275570/126768510-29a31fa6-0b42-4a9a-b0d0-2d2e7933cb1d.png)

**Comment by wuyou10206** [comment]
create table t1(
c1 string,
c3 int,
c4 bigint,
c5 float,
c6 double,
c7 timestamp,
c8 date,
index(key=(c3),ts=c7))options(partitionnum=1,replicanum=1);

insert into t1 values('aa',20,30,1.1,2.1,1590738990000,'2020-05-01');
insert into t1 values('aa',21,31,1.2,2.2,1590738991000,'2020-05-02');
insert into t1 values('aa',22,32,1.3,2.3,1590738992000,'2020-05-03');
insert into t1 values('aa',23,33,1.4,2.4,1590738993000,'2020-05-04');
insert into t1 values('bb',24,34,1.5,2.5,1590738994000,'2020-05-05');

CREATE INDEX index1 ON t1 (c1) OPTIONS (ts=c7, ttl=0m, ttl_type=absolute);

SELECT c1, c3, sum(c4) OVER w1 as w1_c4_sum FROM t1 WINDOW w1 AS (PARTITION BY t1.c1 ORDER BY t1.c7 ROWS BETWEEN 2 PRECEDING AND CURRENT ROW);

**Comment by jingchen2222** [comment]
Resolved by #708
