### ISSUE TITLE
delete key in pre-aggr table when delete occur in base table

### ISSUE THREAD

**Issue by nautaa** [4paradigm/OpenMLDB#1673]
**Bug Description**
aggregator is not supported `delete` yet, base and aggregate tables should be kept consistent.

**Expected Behavior**
when delete on base table, pre-aggr table and aggregator should invalid these rows.

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by dl239** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.5.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-05x)

**Comment by lumianph** [comment]
@zhanghaohit check whether cause incorrectness
