### ISSUE TITLE
`Traverse` may get duplicate data if there are same ts records on one pk

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1696]
* `Traverse` may get duplicate data if there are same ts records on one pk
*  `Traverse` may run in endless loop if there are many same ts records on one pk

**Comment by dl239** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.5.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-05x)

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug List (0.7)](https://trello.com/c/JVdN9kkX/161-bug-list-07)
