### ISSUE TITLE
Delete `SQLClusterRouter` from nameserver

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1697]
we should use `FullTableIterator` instead  of `SQLClusterRouter` in nameserver to get all data form specific table
the following works need to do:
* delete `sr_` in src/nameserver.cc and src/nameserver.h
* use `FullTableIterator` to get all data instead of [`ExecuteSQLParameterized`](https://github.com/4paradigm/OpenMLDB/blob/main/src/nameserver/name_server_impl.cc#L10661)
* use tablet client put directly instead of [`ExecuteInsert`](https://github.com/4paradigm/OpenMLDB/blob/main/src/nameserver/name_server_impl.cc#L10703)

`FullTableIterator`  is implemented in src/catalog/distribute_iterator.h

**Comment by aceforeverd** [comment]
Might not an easy work.

BTW, does `FullTableIterator` support random access for a row e.g `deploy_stats` in `GLOBAL_VARIABLES`

**Comment by dl239** [comment]
you can seek to a specific row with `DistributeWindowIterator`

**Comment by dl239** [comment]
done #3678
