### ISSUE TITLE
query result is wrong if add ts column when add a new index

### ISSUE THREAD

**Issue by keyu813** [4paradigm/OpenMLDB#1722]
**reproduce:
standalone mode：**
1. create table：`create table t1 (id int, c1 string, c2 int, c3 timestamp, c4 timestamp, index(key=(c1),ts=c4))options(partitionnum=1, replicanum=1);`
2. insert data
<img width="580" alt="image" src="https://user-images.githubusercontent.com/60570208/165244445-27a4a92f-3cf4-43f6-8b76-4db417155e0f.png">
3. create index，if add ts column, query result is wrong. if not added ts column, query result is right：
<img width="678" alt="image" src="https://user-images.githubusercontent.com/60570208/165244679-10053433-d039-4fdc-9470-abaabc43c53e.png">
4. desc table：
<img width="459" alt="image" src="https://user-images.githubusercontent.com/60570208/165246232-cabe6d46-9b8d-412c-b9ee-1ae654b57f0f.png">
5. query,  if add ts column when create table, result is right. but if add ts column when create index, result is wrong
<img width="379" alt="image" src="https://user-images.githubusercontent.com/60570208/165247084-abb78992-1e9d-44e3-8ea8-2697a8aed15a.png">

result in cluster mode is same as in standalone mode.

**Comment by aceforeverd** [comment]
what the result of 
```sql
explain select * from t1 where c1 = 'aa' ;

or
explain select * from t1 where c2 = 1;
```
?

**Comment by keyu813** [comment]
> ```sql
> select * from t1 where c1 = 'aa' ;
> ```

cli seems don't support explain `where` statement in standalone mode <img width="829" alt="image" src="https://user-images.githubusercontent.com/60570208/165250510-c0fce6f7-4b9a-4e72-a153-8c5f19365205.png">
but if I add log in src code, the physical plan is 
<img width="498" alt="企业微信截图_37f0279a-1f4e-4437-b1a6-a626e5114d81" src="https://user-images.githubusercontent.com/60570208/165255630-aaf59057-a751-4743-8ee8-59bc8dea5977.png">
seems valid

**Comment by keyu813** [comment]
this bug doesn't exist in the latest main branch
