### ISSUE TITLE
是否可以多条件查询

### ISSUE THREAD

**Issue by zhangjun9302** [4paradigm/OpenMLDB#173]
![image](https://user-images.githubusercontent.com/87636437/126942766-270d2205-f455-4152-ac77-a3f460526758.png)
如图这样一张表，RtiDB是否可以按下面的红框里的条件多条件查询呢？我在文档里面没有找到相关API，麻烦了。

**Comment by dl239** [comment]
rtidb不支持多条件查询，只支持在某一索引上的范围查询。这些条件需要查出来之后再过滤

**Comment by imotai** [comment]
> 如图这样一张表，RtiDB是否可以按下面的红框里的条件多条件查询呢？我在文档里面没有找到相关API，麻烦了。

看不见图
