### ISSUE TITLE
abs_ttl seems won't make effect

### ISSUE THREAD

**Issue by keyu813** [4paradigm/OpenMLDB#1732]
<img width="957" alt="image" src="https://user-images.githubusercontent.com/60570208/165703912-710e1a91-141b-4490-a709-e52b587d11c6.png">
expect ttl=1min but get ttl=0min

lat_ttl doesn't have this problem

**Comment by dl239** [comment]
use `ttl`, refer [here](https://openmldb.ai/docs/zh/v0.4/reference/sql/ddl/CREATE_TABLE_STATEMENT.html)

**Comment by keyu813** [comment]
absolute ttl should use `ttl` not `abs_ttl`
