### ISSUE TITLE
Processing of Chinese special characters

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#1742]
**Bug Description**
Some Chinese special characters failed to insert into the large disk openmldb
<img width="1154" alt="wecom-temp-54a0b24c1f233d8c489a2c987cac4880" src="https://user-images.githubusercontent.com/18275570/166173923-587a8826-aeaf-4c03-bfd9-20f38fcb165f.png">

**Expected Behavior**
Insert Success

**Steps to Reproduce**
1.   String insertSql = "INSERT INTO test2 VALUES ('Ami \uD83D\uDC90',333);";

**Comment by dl239** [comment]
it seems from zetasql @aceforeverd

**Comment by aceforeverd** [comment]
> it seems from zetasql @aceforeverd 

Yes，should write in another way, will check

**Comment by aceforeverd** [comment]
surrogate(`U+d800 .. U+dfff`) is (and should) not supported by zetasql.
The `\uD83D\uDC90`, which is a utf-16 surrogate pair, should converted into UTF-8,
check the C code in the last https://unicodebook.readthedocs.io/unicode_encodings.html#utf-16-surrogate-pairs
