### ISSUE TITLE
set the constant in getSQLStateType

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1758]
https://github.com/4paradigm/OpenMLDB/blob/9389d90c260ec395c32cbae4d98a42a001183a16/java/openmldb-jdbc/src/main/java/com/_4paradigm/openmldb/jdbc/DatabaseMetaData.java#L1014-L1016

`return 0;` is not good. Change it to `sqlStateSQL99`.

**Comment by SaumyaBhushan** [comment]
I would like to help
