### ISSUE TITLE
check if null in PreparedStatement

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1759]
https://github.com/4paradigm/OpenMLDB/blob/9389d90c260ec395c32cbae4d98a42a001183a16/java/openmldb-jdbc/src/main/java/com/_4paradigm/openmldb/jdbc/PreparedStatement.java#L274-L277

`currentRow` may be null, check it before call `GetSchema`. If it's null, throw an exception.

And then, Line 279 `this.currentRow == null` below is useless. Delete it.

https://github.com/4paradigm/OpenMLDB/blob/9389d90c260ec395c32cbae4d98a42a001183a16/java/openmldb-jdbc/src/main/java/com/_4paradigm/openmldb/jdbc/PreparedStatement.java#L279-L281

**Comment by vighnesh-kadam** [comment]
Can you please assign this to me ? I need to just put the "if codeblock" from line 279 to line 275 right?

**Comment by lumianph** [comment]
@vighnesh-kadam  i have assigned to you. You can use `if` to check the null according to the description above
