### ISSUE TITLE
RTIDB数据写入的速度是否可以优化

### ISSUE THREAD

**Issue by zou0619** [4paradigm/OpenMLDB#176]
在性能测试中碰到验证TPS上不去
使用方法：
1、阶梯压测：jmeter并发控制在10-1000进行阶梯式压测
2、压测方法：单机压测、多机压测、分布式压测

阶梯压测：
多台同时机器压测tps：
	58机器tps：55
	66机器tps：52
	68机器tps：51
分布式压测tps：(施压机器二台)
	tps：190
单台压测，线程池：
	500线程池tps：230
	1000线程池tps：220
	1300线程池tps：160

**Comment by imotai** [comment]
麻烦贴一下压测的代码
