### ISSUE TITLE
remove unused code in SimpleResultSet

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1760]
https://github.com/4paradigm/OpenMLDB/blob/9389d90c260ec395c32cbae4d98a42a001183a16/java/openmldb-jdbc/src/main/java/com/_4paradigm/openmldb/jdbc/SimpleResultSet.java#L38
https://github.com/4paradigm/OpenMLDB/blob/9389d90c260ec395c32cbae4d98a42a001183a16/java/openmldb-jdbc/src/main/java/com/_4paradigm/openmldb/jdbc/SimpleResultSet.java#L60
Types is unused. And type parameter '<T>' is unused too. Delete them.

**Comment by SaumyaBhushan** [comment]
Please assign it to me.

**Comment by lumianph** [comment]
> Please assign it to me.

@SaumyaBhushan i have assigned to you, looking forward to your PR
