### ISSUE TITLE
Solve problems in SQL commands

### ISSUE THREAD

**Issue by XuanheZhou** [4paradigm/OpenMLDB#1761]
I find two problems when using the explain+sql commands via terminal

(1) Need to click the "enter" key twice before seeing the explain results:

127.0.0.1:6527/test> explain select * from test;
127.0.0.1:6527/test> 	DATA_PROVIDER(request=test)

(2) Need to split the sql with the semicolon (;) with a character (e.g., an enter key or space), otherwise it will report errors:

127.0.0.1:6527/test> select * from (select * from
                  ->  window win1 as (partition by c1 order by c2 rows_range between 172799999 preceding and 0s preceding MAXSIZE 1000),
                  -> win2 as (partition by c1 order by c2 rows_range between 172799999 preceding and 0s preceding MAXSIZE 1000))
                  -> as out0
                  ->  last join (select * from test t1 last join test t2 on t1.c2=t2.c2) as out1 on out0.c2=out1.c2; 
                  -> 
                  -> ;
Error: Syntax error: Expected end of input but got ";" [at 6:1]

127.0.0.1:6527/test> select * from (select * from
                  ->  window win1 as (partition by c1 order by c2 rows_range between 172799999 preceding and 0s preceding MAXSIZE 1000),
                  -> win2 as (partition by c1 order by c2 rows_range between 172799999 preceding and 0s preceding MAXSIZE 1000))
                  -> as out0
                  ->  last join (select * from test t1 last join test t2 on t1.c2=t2.c2) as out1 on out0.c2=out1.c2
                  -> ;
 ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- 
  c1   c2   c3   c6   c7   c1   c2   c3   c6   c7   c1   c2   c3   c6   c7  
 ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----

**Comment by aceforeverd** [comment]
what's the openmldb version are u using ?

**Comment by XuanheZhou** [comment]
> what's the openmldb version are u using ?

0.4.4 in docker (4pdosc/openmldb:0.4.4)

**Comment by lumianph** [comment]
@aceforeverd pls help reproduce and confirm this issue?

**Comment by aceforeverd** [comment]
> I find two problems when using the explain+sql commands via terminal
> 
> (1) Need to click the "enter" key twice before seeing the explain results:
> 
> 127.0.0.1:6527/test> explain select * from test; 127.0.0.1:6527/test> DATA_PROVIDER(request=test)

reproduced.

> 
> (2) Need to split the sql with the semicolon (;) with a character (e.g., an enter key or space), otherwise it will report errors:
> 
> 127.0.0.1:6527/test> select * from (select * from -> window win1 as (partition by c1 order by c2 rows_range between 172799999 preceding and 0s preceding MAXSIZE 1000), -> win2 as (partition by c1 order by c2 rows_range between 172799999 preceding and 0s preceding MAXSIZE 1000)) -> as out0 -> last join (select * from test t1 last join test t2 on t1.c2=t2.c2) as out1 on out0.c2=out1.c2; -> -> ; Error: Syntax error: Expected end of input but got ";" [at 6:1]

looks like the sql is incomplete. May you pls provide the complete sql in single line ?
I reproduced with 
```sql
SELECT * FROM ( SELECT * FROM test WINDOW win1 AS( PARTITION BY c1 ORDER BY c2 rows_range BETWEEN 172799999 PRECEDING AND 0s PRECEDING MAXSIZE 1000), win2 AS( PARTITION BY c1 ORDER BY c2 rows_range BETWEEN 172799999 PRECEDING AND 0s PRECEDING MAXSIZE 1000)) AS out0 last JOIN ( SELECT * FROM test t1 LAST JOIN test t2 ON t1.c2 = t2.c2) AS out1 ON out0.c2 = out1.c2;
```
will check the reason


> 
> 127.0.0.1:6527/test> select * from (select * from -> window win1 as (partition by c1 order by c2 rows_range between 172799999 preceding and 0s preceding MAXSIZE 1000), -> win2 as (partition by c1 order by c2 rows_range between 172799999 preceding and 0s preceding MAXSIZE 1000)) -> as out0 -> last join (select * from test t1 last join test t2 on t1.c2=t2.c2) as out1 on out0.c2=out1.c2 -> ;
> 
> c1 c2 c3 c6 c7 c1 c2 c3 c6 c7 c1 c2 c3 c6 c7
