### ISSUE TITLE
use constant instead of int in SimpleResultSet

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1762]
https://github.com/4paradigm/OpenMLDB/blob/43f2d6a46c02dc8165a92815862d87470dbf4b0f/java/openmldb-jdbc/src/main/java/com/_4paradigm/openmldb/jdbc/SimpleResultSet.java#L368-L371
set it to `FETCH_UNKNOWN`

https://github.com/4paradigm/OpenMLDB/blob/43f2d6a46c02dc8165a92815862d87470dbf4b0f/java/openmldb-jdbc/src/main/java/com/_4paradigm/openmldb/jdbc/SimpleResultSet.java#L384-L386
set it to `TYPE_FORWARD_ONLY`

https://github.com/4paradigm/OpenMLDB/blob/43f2d6a46c02dc8165a92815862d87470dbf4b0f/java/openmldb-jdbc/src/main/java/com/_4paradigm/openmldb/jdbc/SimpleResultSet.java#L389-L391
set it to `CONCUR_READ_ONLY`

**Comment by SaumyaBhushan** [comment]
How can I set it ?

**Comment by lumianph** [comment]
@SaumyaBhushan  you want to take this issue as well?

**Comment by SaumyaBhushan** [comment]
I am not sure about how can I set those values that you have recommended in the issue. Actually, I'm new to this. If you can guide I can take up this issue.

**Comment by SaumyaBhushan** [comment]
I am not sure how can I set those values that you have recommended in the issue. Actually, I'm new to this. If you can guide I can take up this issue.

**Comment by lumianph** [comment]
> I am not sure how can I set those values that you have recommended in the issue. Actually, I'm new to this. If you can guide I can take up this issue.

you just return the pre-defined constant (such as `return FETCH_UNKNOWN` in the first code block), instead of `return 0`

**Comment by SaumyaBhushan** [comment]
Thanks, @lumianph. Please assign it to me.

**Comment by SaumyaBhushan** [comment]
Hey @lumianph @vagetablechicken please review https://github.com/4paradigm/OpenMLDB/pull/1768

**Comment by lumianph** [comment]
thanks~
