### ISSUE TITLE
Fix typo of `PhysicalAggrerationNode`

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#1767]
**Bug Description**
`PhysicalAggrerationNode` in `hybridse/include/vm/physical_op.h` should be `PhysicalAggregationNode`

**Expected Behavior**
Change all occurrences of `PhysicalAggrerationNode` to `PhysicalAggregationNode`

**Comment by yclchuxue** [comment]
Can I have a try?

**Comment by tobegit3hub** [comment]
Thanks and it is resolved by https://github.com/4paradigm/OpenMLDB/pull/1779 .
