### ISSUE TITLE
是否支持批量插入

### ISSUE THREAD

**Issue by zhangjun9302** [4paradigm/OpenMLDB#177]
在文档和java api中暂未找到批量插入的，都是一条数据单独插入的（schema表put），请问RtiDB是否支持批量插入呢？如果针对批量数据插入时如何处理的呢？

**Comment by vagetablechicken** [comment]
server端是不支持batch put的，所以本质上只支持单条put。批量插入的具体需求是什么样的？单条put在哪些方面不符合你的需求呢？

**Comment by zhangjun9302** [comment]
单条put也可以，但是我想的是一般有单条插入也有批量插入吗，万一想插入大量数据，循环单条插入会不会有什么影响吗？

**Comment by imotai** [comment]
> 的是

你需要写入性能是多少？我理解即使循环写入性能也不差，如果你想做的极致，你可以用异步接口，比如每写入10条，然后检查是否写成功，再写入下10条

**Comment by zhangjun9302** [comment]
异步插入是单条put还是可以批量的呢？如果是批量的，api是多少呢？

**Comment by vagetablechicken** [comment]
异步仍是单条的，TableAsyncClient
