### ISSUE TITLE
Remove unused gflag variable

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1775]
`enable_timeseries_table` is unused currently. it need to delete from the following files:
- src/flags.cc
- src/nameserver/standalone_test.cc
- src/nameserver/name_server_test.cc
- src/nameserver/name_server_impl.cc

**Comment by bxiiiiii** [comment]
Please assign it to me.

**Comment by lumianph** [comment]
@bxiiiiii  looking forward to your PR
