### ISSUE TITLE
docs: translate the Chinese doc of upgrade.md into English

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#1791]
1. The source of the Chinese docs is here: https://github.com/4paradigm/OpenMLDB/blob/main/docs/zh/maintain/upgrade.md
2. The translated English doc should be saved under the path of docs/en/maintain/upgrade.md
3. add the page entry to the file docs/en/maintain/index.rst

**Comment by bxiiiiii** [comment]
I would like to help.

**Comment by bxiiiiii** [comment]
Please assign it to me.
