### ISSUE TITLE
docs: translate the Chinese doc of backup.md into English

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#1792]
- The source of the Chinese docs is here: https://github.com/4paradigm/OpenMLDB/blob/main/docs/zh/maintain/backup.md
- The translated English doc should be saved under the path of docs/en/maintain/backup.md
- add the page entry to the file docs/en/maintain/index.rst

**Comment by yclchuxue** [comment]
I want to do this.

**Comment by lumianph** [comment]
> I want to do this.

Thank you for the interest. I have assigned it to you. Thanks.
