### ISSUE TITLE
docs: translate the Chinese doc of scale.md into English

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#1793]
1. The source of the Chinese doc is here: https://github.com/4paradigm/OpenMLDB/blob/main/docs/zh/maintain/scale.md
2. The translated English doc should be saved under the path of docs/en/maintain/scale.md
3. add the page entry to the file docs/en/maintain/index.rst

**Comment by ZtXavier** [comment]
can I do this

**Comment by lumianph** [comment]
> can I do this

@ZtXavier sorry for the late reply, i have assigned to you, I hope you can still help this. Thanks!

**Comment by ZtXavier** [comment]
I have finish it
