### ISSUE TITLE
docs: translate the Chinese doc of monitoring.md into English

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#1794]
1. The source of the Chinese doc is here: https://github.com/4paradigm/OpenMLDB/blob/main/docs/zh/maintain/monitoring.md
2. The translated English doc should be saved under the path of docs/en/maintain/monitoring.md
3. Add the page entry to the file docs/en/maintain/index.rst

**Comment by Albertchamberlain** [comment]
Please assign it to me.😀

**Comment by Albertchamberlain** [comment]
@jmoldyvan has done the job #1815

**Comment by lumianph** [comment]
@Albertchamberlain yes, you may try another issue :-)
