### ISSUE TITLE
docs: translate the Chinese doc of faq.md into English

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#1796]
1. The source of the Chinese doc is here: https://github.com/4paradigm/OpenMLDB/blob/main/docs/zh/maintain/faq.md
2. The translated English doc should be saved under the path of docs/en/maintain/faq.md
3. Add the page entry to the file docs/en/maintain/index.rst

**Comment by IZUMI-Zu** [comment]
Hello, I would like to work on this issue. Can I have a try?

**Comment by lumianph** [comment]
@IZUMI-Zu since another contributor has already submitted a PR to this issue, you are suggested to choose another translation task. Anyway, thank you for your interest very much.
