### ISSUE TITLE
可以获取schema插入报错

### ISSUE THREAD

**Issue by zhangjun9302** [4paradigm/OpenMLDB#180]
![image](https://user-images.githubusercontent.com/87636437/127088707-4825899d-4336-4b8b-b88a-7ad514bdec14.png)

可以获取到RtiDB表的schema，但插入数据说却报错table is not exist，请问这会是什么原因呢？

![image](https://user-images.githubusercontent.com/87636437/127088972-4ee513bb-37c6-4e2e-9de8-9b8b4433600b.png)

**Comment by vagetablechicken** [comment]
rtidb版本是多少？

**Comment by zhangjun9302** [comment]
用的1.6.1.0得，服务端重启了一下，表删了重建一下又好了，不清楚怎么回事。

**Comment by imotai** [comment]
> 用的1.6.1.0得，服务端重启了一下，表删了重建一下又好了，不清楚怎么回事。

如果是通过java sdk创建的表，创建完成最好做一下sleep，目前创建是一个异步过程，tablet上面可能还没创建好，这个时候直接写入就会出现表不存在问题
