### ISSUE TITLE
Rename `procedure` to `deployment`

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1804]
Rename `procedure` to `deployment` in src/name_server_impl.cc

https://github.com/4paradigm/OpenMLDB/blob/main/src/nameserver/name_server_impl.cc#L3006
https://github.com/4paradigm/OpenMLDB/blob/main/src/nameserver/name_server_impl.cc#L3017

**Comment by Mount-Blanc** [comment]
Hello, I would like to work on this issue.
