### ISSUE TITLE
Support db in `insert` statement

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1808]
`insert into test.t3 values('b',1122);`

**Comment by dl239** [comment]
- rm db check in https://github.com/4paradigm/OpenMLDB/blob/main/src/sdk/sql_cluster_router.cc#L2322-L2326
- add test case to src/cmd/sql_cmd_test.cc

**Comment by nautaa** [comment]
pr #1173 has fixed this problem, it is reverted?

**Comment by nautaa** [comment]
https://github.com/4paradigm/OpenMLDB/pull/1173#discussion_r871955805

**Comment by dl239** [comment]
> #1173

there have some validation in sdk. https://github.com/4paradigm/OpenMLDB/blob/main/src/sdk/sql_cluster_router.cc#L2322-L2326

**Comment by dl239** [comment]
hi @nautaa, this pr has been assigned to @xuduling , she is woking for this. thank you
