### ISSUE TITLE
docs: question: is there an architectural doc of the storage engine

### ISSUE THREAD

**Issue by emaxerrno** [4paradigm/OpenMLDB#182]
Trying to understand how https://github.com/4paradigm/OpenMLDB/blob/main/src/zk/zk_client.h - zk is used in the architecture. I didn't see an overview diagram of the actual storage engine.

very cool project, great work.

**Comment by emaxerrno** [comment]
reason for asking thinking we (https://github.com/vectorizedio/redpanda) should expose a locking service of sorts. :) was my motivation for asking.

**Comment by imotai** [comment]
hi @senior7515  
1. OpenMLDB uses zookeeper as a distributed lock (https://github.com/4paradigm/OpenMLDB/blob/main/src/zk/dist_lock.h) and meta storage 
2.  the online storage is an in-memory and double-layered  skiplist, you can see the architecture
![image](https://user-images.githubusercontent.com/8623385/127266412-40fbb76a-9352-455a-9a5e-325884c44409.png)

**Comment by emaxerrno** [comment]
ah awesome, that's what I thought, but wnated to confirm. 

so is really:

1. zookeeper ensemble
2. mldb worker nodes? 


is the binlog replicated among mdldb nodes or how is the data actually replicated. if you have docs, I'd be happy to read them too.

**Comment by vagetablechicken** [comment]
Sorry to reply so late to you. 
Zookeeper ensemble is preferred, to ensure meta data is not lost. 
What do you mean 'mldb worker nodes'?
We use https://github.com/4paradigm/OpenMLDB/blob/8242cb6e4cb77ac6bf67b2e9e43655942c6ffa8a/src/replica/log_replicator.h#L51
to do binlog replication. 
No docs now, will add later.

**Comment by emaxerrno** [comment]
thanks!
