### ISSUE TITLE
Delete unused code about `ShowTp`

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1823]
the following code should be clean:
- delete `ShowTp` function from src/client/tablet_client.cc and src/client/tablet_client.h
- delete `enable_show_tp` from src/flags.cc and src/client/tablet_client.cc
- delete `percentile_`  from src/client/tablet_client.h

**Comment by frazie** [comment]
can I have this task assigned to me?

**Comment by frazie** [comment]
can I have this task assigned to me?

**Comment by lumianph** [comment]
@frazie I have assigned to you, looking forward to your contribution.
