### ISSUE TITLE
Resolve compiling warnings

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1826]
resolve the following compiling warnings:

1 src/nameserver/name_server_test.cc
<img width="789" alt="WX20220516-215239@2x" src="https://user-images.githubusercontent.com/6183996/168608516-1e323a7a-91b5-43cf-92b6-d5e3b7603753.png">

2 src/tablet/tablet_impl_multi_path_test.cc
<img width="783" alt="WX20220516-215402@2x" src="https://user-images.githubusercontent.com/6183996/168608786-2934f244-82e1-4954-a363-2403735cfd3d.png">

3 src/tablet/tablet_impl_projection_test.cc
<img width="776" alt="WX20220516-215628@2x" src="https://user-images.githubusercontent.com/6183996/168609350-61eff8b1-68dd-43fc-854d-8484020204b5.png">

**Comment by aceforeverd** [comment]
just reference here, should turn those flags into error #1528

**Comment by Ivyee17** [comment]
I want to help with this issue!WeOpen Star

**Comment by lumianph** [comment]
> I want to help with this issue!WeOpen Star

I have assigned to you, looking forward to your PR

**Comment by Ivyee17** [comment]
> > I want to help with this issue!WeOpen Star
> 
> I have assigned to you, looking forward to your PR

I've issued a pr https://github.com/4paradigm/OpenMLDB/pull/1862 here for this bug. thx.
