### ISSUE TITLE
Duplicate records in PRE_AGG_META_INFO

### ISSUE THREAD

**Issue by nautaa** [4paradigm/OpenMLDB#1850]
**Bug Description**
Duplicate records in PRE_AGG_META_INFO
<img width="1154" alt="wecom-temp-c2acb780ad574ad0c0a6cbf931da878c" src="https://user-images.githubusercontent.com/25190284/169455023-eb0785a0-d967-4321-96ab-68e9b7256cea.png">

**Expected Behavior**

we check the long window meta info exists before inserting meta and creating pre-aggr table. The same meta info should only be inserted once in the meta info table.

need more info to reproduce.

**Steps to Reproduce**
1. 
2. 
3. 
4.

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs (0.5.x)](https://trello.com/c/WhbjlRN2/69-bugs-05x)

**Comment by zhanghaohit** [comment]
The problem still exists. See [select * from __INTERNAL_DB.PRE_AGG_META_INFO](https://github.com/4paradigm/OpenMLDB/issues/2464#issuecomment-1254596836) in #2464
