### ISSUE TITLE
python: use db bug

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1852]
If create_engine without db, we will pass default db as "".
So code like this below can't pass.

```
create_engine without db
execute("use db")
execute("select * from t1;")
```

The bug is around `self.sdk.ExecuteSQL`, cause it will use the db in parameter list as the default db.

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs (0.5.x)](https://trello.com/c/WhbjlRN2/69-bugs-05x)
