### ISSUE TITLE
docs: more detail in contribution guide

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1859]
In [guide](https://github.com/4paradigm/OpenMLDB/blob/461d5201ae398155fb0e83c281aa73c926780341/CONTRIBUTING.md#code-contribution-workflow), we should add info about:
1. pr title, a lot of contributors write the wrong title.
2. cicd: some workflow can be x, but some must be passed.

And we should put the contribution-workflow in a more prominent position, first contributors need it.

**Comment by aceforeverd** [comment]
like this #1811 ?

**Comment by vagetablechicken** [comment]
> 

Yep. Let's merge the two issues. I've searched `contribution`, missed this issue.
Pr title and cicd are important. Got these questions many times.
