### ISSUE TITLE
Delete `inline` keywords from the declaration of `GetRecordByteSize` 

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1865]
Delete `inline` keyword from the declaration of `GetRecordByteSize`  in following files:
- src/storage/table.h
- src/storage/mem_table.h
- src/storage/disk_table.h

**Comment by mangoGoForward** [comment]
[WeOpen Star]I would like to help

**Comment by dl239** [comment]
> [WeOpen Star]I would like to help

thank you
