### ISSUE TITLE
Rename `RtidbSchema` to `PBSchema`

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1866]
Rename `RtidbSchema` to `PBSchema` in the following files:
- src/sdk/sql_cluster_router.h
- src/sdk/sql_cluster_router.cc
- src/sdk/sql_sdk_test.h
- src/sdk/sql_router_test.cc
- src/sdk/mini_cluster_batch_bm.cc
- src/sdk/mini_cluster_bm.cc

**Comment by mangoGoForward** [comment]
[WeOpen Star]I would like to help

**Comment by dl239** [comment]
> [WeOpen Star]I would like to help

looking forward your pr, thank you

**Comment by mangoGoForward** [comment]
> looking forward your pr, thank you

Hi @dl239,  Can we replace all files which contains `RtidbSchema` keyword to `PBSchema` in `src/sdk` directory?
Thanks!

**Comment by dl239** [comment]
> > looking forward your pr, thank you
> 
> Hi @dl239, Can we replace all files which contains `RtidbSchema` keyword to `PBSchema` in `src/sdk` directory? Thanks!

take the notice that the name is `RtiDBSchema` is some files. you should replace `RtidbSchema` and `RtiDBSchema` to `PBSchema` in `src/sdk`  dir

**Comment by mangoGoForward** [comment]
> take the notice that the name is `RtiDBSchema` is some files. you should replace `RtidbSchema` and `RtiDBSchema` to `PBSchema` in `src/sdk` dir

Ok, thanks
