### ISSUE TITLE
typo method name from `DataHandler` abstract method

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#1874]
https://github.com/4paradigm/OpenMLDB/blob/6f993f3dea4b0b1aa12c487eb110f8b42ff4e5db/hybridse/include/vm/catalog.h#L89-L89

should be `GetHandlerType`.

To fix this, you need change the method name for both abstract class and inherit classes, like:
+ https://github.com/4paradigm/OpenMLDB/blob/f83616596240bef0f30ba0e0d9069ed45f42ebde/hybridse/include/vm/catalog.h#L170
+ https://github.com/4paradigm/OpenMLDB/blob/f83616596240bef0f30ba0e0d9069ed45f42ebde/hybridse/include/vm/catalog.h#L232

then update callee names elsewhere as well

**Comment by lumianph** [comment]
can set this as good first issue?

**Comment by aceforeverd** [comment]
> can set this as good first issue?

Can be, but need a bit more guide
