### ISSUE TITLE
Remove `sscan` and `sget` command in tablet client

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1881]
`sscan` and `sget` command is unused currently. we should delete it from src/cmd/openmldb.cc file.
- delete `HandleClientSScan` and  `HandleClientSGet` function and relavent code in src/cmd/openmldb.cc
- delete `sscan` and `sget` usage guide in `HandleClientHelp` function

**Comment by frazie** [comment]
kindly assign this task to me

Thanks.

**Comment by dl239** [comment]
> kindly assign this task to me
> 
> Thanks.

have assigned to you, thank you

**Comment by frazie** [comment]
It was amazing working on this project, thanks!!
