### ISSUE TITLE
Display `YYYY-MM-DD HH-MM-SS` format in the result of  `Show Components` command

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1888]
The result of `Connect_time` is not convenient to debug
![WX20220526-111212](https://user-images.githubusercontent.com/6183996/170409787-672e9a5e-401a-4305-a4fa-81afda5a3f41.png)

**Comment by aceforeverd** [comment]
refer #1456 
MakeResultSet only support string as data type
