### ISSUE TITLE
创建表时，ttl=(3650m),ttl_type=absolute，表创建成功

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#189]
## Expected Behavior
创建失败，提示原因

## Current Behavior
创建成功

## Possible Solution
sql：
create table auto_KuLFyGom (c1 string NOT NULL,c2 int,c3 timestamp, c4 timestamp,index(key=(c1),ts=c4,ttl=(3650m),ttl_type=absolute));

**Comment by dl239** [comment]
这个ttl和ttltype是有啥问题吗

**Comment by dl239** [comment]
https://github.com/4paradigm/OpenMLDB/blob/main/cases/function/ddl/test_ttl.yaml#L41 case 6 create success but case 7 create failed

**Comment by dl239** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bug-denglong](https://trello.com/c/sdJl9Vdl/2-bug-denglong)

**Comment by dl239** [comment]
> https://github.com/4paradigm/OpenMLDB/blob/main/cases/function/ddl/test_ttl.yaml#L41 case 6 create success but case 7 create failed

this case execute failed because latest ttl is large than 1000
