### ISSUE TITLE
`Tablet` has not save `ttl` when updating the `ttl` of index

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1904]
`Tablet` has not save `ttl` to `table_meta.txt` when updating the `ttl` of index

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs (0.5.x)](https://trello.com/c/WhbjlRN2/69-bugs-05x)

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.5.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-05x)

**Comment by dl239** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.5.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-05x)
