### ISSUE TITLE
java sdk: `Statement::execute` return false always because it do not have resultset returned

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#1905]
**Bug Description**

https://github.com/4paradigm/OpenMLDB/blob/555077f7869f0cdffab2674e38a9bee1f09090da/java/openmldb-jdbc/src/main/java/com/_4paradigm/openmldb/jdbc/Statement.java#L31

https://github.com/4paradigm/OpenMLDB/blob/555077f7869f0cdffab2674e38a9bee1f09090da/src/sdk/sql_cluster_router.cc#L2339

**Expected Behavior**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by dl239** [comment]
https://github.com/4paradigm/OpenMLDB/blob/main/java/openmldb-jdbc/src/test/java/com/_4paradigm/openmldb/jdbc/StatementTest.java#L41

**Comment by aceforeverd** [comment]
> https://github.com/4paradigm/OpenMLDB/blob/main/java/openmldb-jdbc/src/test/java/com/_4paradigm/openmldb/jdbc/StatementTest.java#L41

what does this mean ? I found the deploy test always expect ret code to be false: https://github.com/4paradigm/OpenMLDB/blob/main/java/openmldb-jdbc/src/test/java/com/_4paradigm/openmldb/jdbc/StatementTest.java#L84

**Comment by dl239** [comment]
> true if the first result is a ResultSet object; false if it is an update count or there are no results
https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#execute(java.lang.String)

**Comment by aceforeverd** [comment]
> > true if the first result is a ResultSet object; false if it is an update count or there are no results
> > https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#execute(java.lang.String)

cool
