### ISSUE TITLE
Fail to catch UnsupportedHybridSeException and fallback to SparkSQL with OpenMLDB Spark distribution

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1906]
Fail to fallback to SparkSQL with OpenMLDB Spark distribution. It is the issue of UnsupportedHybridSeException which may not be thrown correctly.

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs (0.5.x)](https://trello.com/c/WhbjlRN2/69-bugs-05x)

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [不支持函数 fallback, from fangrong](https://trello.com/c/0j36fmVm/72-%E4%B8%8D%E6%94%AF%E6%8C%81%E5%87%BD%E6%95%B0-fallback-from-fangrong)
