### ISSUE TITLE
Delete the `Get` function in tablet_client

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1907]
`Get` function with `ts_name` in tablet_client is not used now. We should delete it from src/client/tablet_client.h and src/client/tablet_client.cc

- delete declaration in [header file](
https://github.com/4paradigm/OpenMLDB/blob/main/src/client/tablet_client.h#L104)
- delete the implement in [tablet_client.cc](https://github.com/4paradigm/OpenMLDB/blob/main/src/client/tablet_client.cc#L823)
-  don't pass `ts_name` in `HandleNSGet` function https://github.com/4paradigm/OpenMLDB/blob/main/src/cmd/openmldb.cc#L1486 https://github.com/4paradigm/OpenMLDB/blob/main/src/cmd/openmldb.cc#L1500

**Comment by mangoGoForward** [comment]
[WeOpen Star]I would like to help

**Comment by dl239** [comment]
> [WeOpen Star]I would like to help

have assigned to you, thanks

**Comment by dl239** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.5.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-05x)
