### ISSUE TITLE
Delete `INVALID_TID` from tablet_client

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1910]
Delete `INVALID_TID` from [tablet_client](https://github.com/4paradigm/OpenMLDB/blob/main/src/client/tablet_client.h#L45)

**Comment by frazie** [comment]
kindly assign this task to me

**Comment by lumianph** [comment]
> kindly assign this task to me

i have assigned to you, looking forward to your PR

**Comment by frazie** [comment]
@lumianph thank you

> > kindly assign this task to me
> 
> i have assigned to you, looking forward to your PR
