### ISSUE TITLE
Procedure call failed, error: Request server error

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#1918]
**Bug Description**

Procedure call failed, error: java.sql.SQLException: call procedure fail, msg: request server error
![image](https://user-images.githubusercontent.com/18275570/171770982-8b47487b-48a8-4848-945c-2ca6345d894c.png)

**Expected Behavior**

Procedure call success

** Env Info **

1.   openmldb-ns-1/bin/openmldb --zk_cluster=172.24.4.55:30008 --zk_root_path=/openmldb --role=sql_client
2.  dbName: diff12
3.  deployName:  deploy_36931328

After deploy is successfully created, show deployments is not displayed and show deployment deploy_36931328 is displayed

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs (0.5.x)](https://trello.com/c/WhbjlRN2/69-bugs-05x)

**Comment by aceforeverd** [comment]
any tablet server log ?

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.5.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-05x)

**Comment by dl239** [comment]
there are some core files in @wuyou10206 's env, the same problem as #1892
@wuyou10206  run well with the bin compiled under the latest code.
