### ISSUE TITLE
refactor: rename zk session_timeout in db sdk

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#1940]
https://github.com/4paradigm/OpenMLDB/blob/5e242cf6568dbde344285a943687a56b5de3d03a/src/sdk/db_sdk.h#L40-L43
session_timeout is used for zookeeper, it's better to rename it to `zk_session_timeout`.

Only rename this class. No need to change the`session_timeout` in `BasicRouterOptions`.

**Comment by mangoGoForward** [comment]
[WeOpen Star]I would like to help

**Comment by mangoGoForward** [comment]
Hi @auula , noticed that you have already finish this coding, please go ahead to push it and no worry.

**Comment by auula** [comment]
> Hi @auula , noticed that you have already finish this coding, please go ahead to push it and no worry.

I don't know c++, I can only try, I fail and give up

**Comment by auula** [comment]
> Hi @auula , noticed that you have already finish this coding, please go ahead to push it and no worry.

This problem is still recommended to be solved by you, I have given up this task, thank you

**Comment by mangoGoForward** [comment]
> This problem is still recommended to be solved by you, I have given up this task, thank you

OK, if you have some advice, also can share with me, thanks.
