### ISSUE TITLE
"SQL上线规范和要求 | Online Serving下LAST JOIN的使用规范" example is not correct

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#1948]
**Bug Description**
Now the doc looks like this: 

### Online Serving下LAST JOIN的使用规范

- Join type仅支持`LAST JOIN`类型
- 至少有一个JOIN条件是形如`left_table.column=right_table.column`的EQUAL条件，并且`rgith_table.column`列需要命中右表的索引
- 带排序LAST JOIN的情况下，`ORDER BY`只能支持列表达式，并且列需要命中右表索引的时间列

#### Example: 支持上线的简单SELECT查询语句范例

```sql
CREATE DATABASE db1;

USE db1;
CREATE TABLE t1 (col0 STRING, col1 int, std_time TIMESTAMP, INDEX(KEY=col1, TS=std_time, TTL_TYPE=absolute, TTL=30d));
-- SUCCEED: Create successfully

desc t1;
 --- ---------- ----------- ------ --------- 
  #   Field      Type        Null   Default  
 --- ---------- ----------- ------ --------- 
  1   col0       Varchar     YES             
  2   col1       Int         YES             
  3   std_time   Timestamp   YES             
 --- ---------- ----------- ------ --------- 
 --- -------------------- ------ ---------- ---------- --------------- 
  #   name                 keys   ts         ttl        ttl_type       
 --- -------------------- ------ ---------- ---------- --------------- 
  1   INDEX_0_1639524729   col1   std_time   43200min   kAbsoluteTime  
 --- -------------------- ------ ---------- ---------- --------------- 
```

**Expected Behavior**
The example should be for the `LAST JOIN` example. Not the `create table` example.

**Comment by aceforeverd** [comment]
https://github.com/4paradigm/OpenMLDB/blob/607f32b9f20d6610dddee35080ca987225adfb83/docs/zh/reference/sql/deployment_manage/ONLINE_SERVING_REQUIREMENTS.md#L9

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.5.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-05x)

**Comment by aceforeverd** [comment]
fix by #2195
