### ISSUE TITLE
增加试用运行环境到readme里

### ISSUE THREAD

**Issue by xuman2019** [4paradigm/OpenMLDB#196]
目前通过docker来使用的方式还是比较麻烦，希望能进一步降低用户使用门槛。以下两个demo是我在openaios上维护的两个试用demo运行环境，环境由我来维护，希望能放到readme里：

## 硬件故障预测demo: 
1. 打开 http://apps.openaios.io:31773/
2. 输入token: 123456
3. 打开develop_ml_application_tour_rul.ipynb
4. 按照jupyter文件指示操作

## 出租车行程耗时推理应用demo：
1. 打开 http://apps.openaios.io:30756/
2. 输入token: 123456
3. 打开 develop_ml_application_tour_taxi.ipynb
4. 按照jupyter文件指示操作

**Comment by imotai** [comment]
这个demo应该没发被多人操作吧

**Comment by xuman2019** [comment]
是，多人同时用的话，notebook上会有进程busy的提示；如果同时试用的人不多，demo勉强可以对付下
