### ISSUE TITLE
Remove the code of setting LANG and LC_ALL in TaskManager

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1962]
Now we do not need to set `LANG` and `LC_ALL` in TaskManager, which was previously used to avoid the bug of brpc error code in Chinese (the bug has been fixed).

Here is the source code in `SparkJobManager.scala` which can be removed now.

https://github.com/4paradigm/OpenMLDB/blob/06255ca9620adf0e0033411984081dab6906a79f/java/openmldb-taskmanager/src/main/scala/com/_4paradigm/openmldb/taskmanager/spark/SparkJobManager.scala#L87-L90

**Comment by harshlancer** [comment]
I'd like to contribute to this issue, please allow me to and guide me.
