### ISSUE TITLE
test: add coverage report for python sdk

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#1971]
**Describe the feature you'd like**

The [python sdk](https://github.com/4paradigm/OpenMLDB/tree/main/python) has unit tests already, but do not have the facility to produce coverage report based on that. 

Mainly two tasks: 

-  [ ] find a coverage library that can produce coverage report and add to the python sdk project
-  [ ] use the `codecov-action` to upload coverage results in `.github/workflows/sdk.yml`

**Additional context**

**Comment by mangoGoForward** [comment]
[WeOpen Star]I would like to help

I found an article about how to get [python code coverage using GitHub Actions and Codecov](https://about.codecov.io/blog/python-code-coverage-using-github-actions-and-codecov/), Could we also follow this to implement?

**Comment by aceforeverd** [comment]
> [WeOpen Star]I would like to help
> 
> I found an article about how to get [python code coverage using GitHub Actions and Codecov](https://about.codecov.io/blog/python-code-coverage-using-github-actions-and-codecov/), Could we also follow this to implement?

looks good, feel free to have a try~
