### ISSUE TITLE
Remove `Count` function from tablet client

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1974]
`Count` function with `ts_name` is unused now. We should delete it from src/client/tablet_client.h and src/client/tablet_client.cc
- delete declaration in [header file](https://github.com/4paradigm/OpenMLDB/blob/main/src/client/tablet_client.h#L101)
- delete the implement in [tablet_client.cc](https://github.com/4paradigm/OpenMLDB/blob/main/src/client/tablet_client.cc#L782)
- do not pass `ts_name` when calling `Count` function in /src/cmd/openmldb.cc

**Comment by TAldridgeAO** [comment]
I can handle this.

**Comment by dl239** [comment]
@0sirusD3m0n have assigned to you, looking forward your pr. thanks
