### ISSUE TITLE
Use int value to record string length instead of Map in `InsertPreparedStatementImpl `

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1979]
Use int value to record string length instead of Map in [`InsertPreparedStatementImpl `](https://github.com/4paradigm/OpenMLDB/blob/main/java/openmldb-jdbc/src/main/java/com/_4paradigm/openmldb/sdk/impl/InsertPreparedStatementImpl.java#L55)

**Comment by TAldridgeAO** [comment]
I'll take a look at this one tomorrow.

**Comment by lumianph** [comment]
> 

shall we assign to you?

**Comment by mangoGoForward** [comment]
[WeOpen Star]I would like to help

**Comment by mangoGoForward** [comment]
Hi, @dl239 Use map can implement multi set and save the value of last set, but use int can't implement it.

**Comment by lumianph** [comment]
i have assigned this task to you @mangoGoForward
