### ISSUE TITLE
Delete `enable_show_tp` from flags.cc

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1980]
`enable_show_tp` is unused now. It need to  from src/flags.cc

**Comment by frazie** [comment]
hello, I would like to work on this task.
Kindly assign it to me.

**Comment by lumianph** [comment]
> hello, I would like to work on this task. Kindly assign it to me.

Hello @frazie , we suggest you first finish the issue that have been already assigned to you, then we will assign other issues that you are interested in to you one by one. Thanks for your contribution.

**Comment by frazie** [comment]
hello, @lumianph if this task is not yet taken can I have it assigned to me?

**Comment by lumianph** [comment]
> hello, @lumianph if this task is not yet taken can I have it assigned to me?

@frazie sure, i have assigned this task to you
