### ISSUE TITLE
Remove unnecessary declaration in nameserver/name_server_impl.h

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1985]
The below declaration is unnecessary, please delete it
https://github.com/4paradigm/OpenMLDB/blob/main/src/nameserver/name_server_impl.h#L123-L124

**Comment by frazie** [comment]
hello, I would like to work on this task.
Kindly assign it to me.

**Comment by lumianph** [comment]
Hello @frazie , we suggest you first finish the issue that have been already assigned to you, then we will assign other issues that you are interested in to you one by one. Thanks for your contribution.

**Comment by frazie** [comment]
> Hello @frazie , we suggest you first finish the issue that have been already assigned to you, then we will assign other issues that you are interested in to you one by one. Thanks for your contribution.

Hello @lumianph , I completed the previous issue and I would love for this to be assigned to me..Thank you
