### ISSUE TITLE
Move the implement of function from src/catalog/tablet_catalog.h to src/catalog/tablet_catalog.cc

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1987]
Please move the implement of following functions in `TabletSegmentHandler` class to src/catalog/tablet_catalog.cc in 
- GetIterator
- GetRawIterator
- GetCount

**Comment by mangoGoForward** [comment]
[WeOpen Star]I would like to help

**Comment by dl239** [comment]
have assigned to you, thank you @mangoGoForward
