### ISSUE TITLE
Remove unnecessary declaration in src/sdk/mini_cluster_bm.cc

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1988]
Remove the following declaration in src/sdk/mini_cluster_bm.cc
- `DECLARE_bool(enable_distsql)`
- `DECLARE_bool(enable_localtablet)`
- `typedef ::google::protobuf::RepeatedPtrField<::openmldb::common::ColumnKey> RtiDBIndex`

**Comment by frazie** [comment]
hello, I would like to work on this task.
Kindly assign it to me.

**Comment by lumianph** [comment]
> 

Hello @frazie , we suggest you first finish the issue that have been already assigned to you, then we will assign other issues that you are interested in to you one by one. Thanks for your contribution.

**Comment by frazie** [comment]
@lumianph Hello, I just submitted the preciously assigned task

**Comment by lumianph** [comment]
> @lumianph Hello, I just submitted the preciously assigned task

sure, i have assigned this task to you. thank you for the contribution~
