### ISSUE TITLE
Rename `RtiDBIndex` to `PBIndex` in src/catalog/sdk_catalog_test.cc

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1989]
Rename `RtiDBIndex` to `PBIndex` in src/catalog/sdk_catalog_test.cc

**Comment by frazie** [comment]
hello, I would like to work on this task.
Kindly assign it to me.

**Comment by dl239** [comment]
> hello, I would like to work on this task. Kindly assign it to me.

have assigned to you, thank you
