### ISSUE TITLE
Remove `PackValue` and `Convert` functions from src/codec/field_codec.h

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1992]
- remove `PackValue` and `Convert` functions from src/codec/field_codec.h
- remove GetXXX functions from src/codec/field_codec.h
- remote `#include "codec/memcomparable_format.h"`  from src/codec/field_codec.h

delete the following files:
- src/codec/memcomparable_format.h
- src/codec/memcomparable_format_test.cc
- src/codec/field_codec_test.cc

**Comment by frazie** [comment]
hello, I would like to work on this task.
Kindly assign it to me.

**Comment by dl239** [comment]
> hello, I would like to work on this task. Kindly assign it to me.

assigned to you, looking forward your pr
