### ISSUE TITLE
Fail to load SQL file for BatchJob in yarn-cluster mode

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1993]
We get file not found exception for yarn-cluster mode.

<img width="1601" alt="image" src="https://user-images.githubusercontent.com/2715000/174282392-83cbe005-1fae-4b80-a11a-73a6f94993e5.png">

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.6.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-06x)
