### ISSUE TITLE
Support executing sql in `APIServer`

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2002]
Currently, our Java and Python SDK are able to call the API to execute any `SELECT` and `ISNERT` SQL statements. However, the APIServer cannot support such an API. We need to make the APIServer to support this functionality.
1. The related code of APIServer you need to update is `xxx`
2. The underlying C++ API to support executing a SQL is `xxx`

**Comment by longranger2** [comment]
Please assign this task to me

**Comment by lumianph** [comment]
@longranger2 i have assignd it to you. thanks.

**Comment by longranger2** [comment]
Hi @lumianph ,Sorry about that I don't know how to solved this issue.It is my first time to participate in open source collaboration, Can you provide me with some help? Or please unassigned to me, and others want to contribute, please go on

**Comment by aceforeverd** [comment]
@dl239 @vagetablechicken maybe we need some detailed notes about the gap between the new feature and current implementation

**Comment by vagetablechicken** [comment]
> @dl239 @vagetablechicken maybe we need some detailed notes about the gap between the new feature and current implementation

@aceforeverd What about the apiserver support for go sdk? Will it cover this issue?

**Comment by aceforeverd** [comment]
> > @dl239 @vagetablechicken maybe we need some detailed notes about the gap between the new feature and current implementation
> 
> @aceforeverd What about the apiserver support for go sdk? Will it cover this issue?

Mostly supported after #2277 , any other features ? @vagetablechicken @dl239
