### ISSUE TITLE
comment about the time units of zk

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2021]
e.g.

https://github.com/4paradigm/OpenMLDB/blob/79b34500d16c56cc68d5defb3f17092b08fa41b1/src/flags.cc#L21
https://github.com/4paradigm/OpenMLDB/blob/79b34500d16c56cc68d5defb3f17092b08fa41b1/src/flags.cc#L28

We should add the time unit, all milliseconds.
And add it in user doc too.

**Comment by aceforeverd** [comment]
@vagetablechicken  good first issue ?

**Comment by liuceyi** [comment]
Hi, may I work on this issue?
