### ISSUE TITLE
SSD table addreplica is failure

### ISSUE THREAD

**Issue by KaidoWang** [4paradigm/OpenMLDB#2026]
**Bug Description**
<img width="1155" alt="企业微信截图_f6e68606-ac4f-43b8-b7ff-c5811129f5bf" src="https://user-images.githubusercontent.com/37789023/175244729-3d1fc3f3-86ee-4dc1-8368-952dc8d7e01e.png">
![Uploading 企业微信截图_1298304e-19a5-46bd-bdee-2417358ebdb8.png…]()
<img width="1200" alt="企业微信截图_89024caa-2020-429c-aadf-4c36806c1547" src="https://user-images.githubusercontent.com/37789023/175244828-3c837a59-c958-46c3-864d-a72ba61d4104.png">

**Expected Behavior**
SSD table addreplica is success.

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by zhanghaohit** [comment]
Potential cause:
-  `FileSender::WriteData` failed to add the `storage_mode` in `SendDataRequest` when `SendData`

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.6.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-06x)
