### ISSUE TITLE
a friendly tool for scale-out

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#2038]
Currently, the scale-out process consists of quite a few steps (refer to https://openmldb.ai/docs/zh/main/maintain/scale.html), and is error-prone. We need a friendly tool to help to do the scale-out (maybe also scale-in), it should have the functions:
- one command line to finish the startup of a new tablet, and migrate a specific partition to the new tablet
- an auto-rebalancing strategy that automatically migrates suitable partitions to the new tablet

**Comment by dl239** [comment]
done in #2736
