### ISSUE TITLE
a friendly tool for deployment

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#2039]
Currently we are using a set of commands for the deployment (refer to https://openmldb.ai/docs/zh/main/deploy/install_deploy.html). For ease of use, we should provide a friendly tool that is able to simplify the deployment. Ideally, the tool is able to automatically deploy all necessary components on all nodes based on a given configuration file only.

**Comment by aceforeverd** [comment]
supported with the `deploy-all.sh` toolsets: https://github.com/4paradigm/OpenMLDB/blob/2b6e63075f39c7e57397eb0da5112ccfde234d01/release/sbin/deploy-all.sh
