### ISSUE TITLE
add the Chinese doc of the talkingdata demo

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#2047]
We have an English version about this demo: https://github.com/4paradigm/OpenMLDB/tree/main/demo/talkingdata-adtracking-fraud-detection

Please translate this doc to Chinese, and save it as: `docs/zh/use_case/talkingdata.md`, please don't forget to update the file `docs/zh/use_case/index.rst`

**Comment by redundan3y** [comment]
Please assign this task to me.

**Comment by lumianph** [comment]
> Please assign this task to me.

i have assigned to you

**Comment by redundan3y** [comment]
> 

Hi, I have finished the translation, can you review it please? Thanks!!

**Comment by lumianph** [comment]
> 

noted with thanks
