### ISSUE TITLE
Delete `AppendXXX` functions from codec/codec.h

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2057]
`AppendXXX` functions in `v1` namespace is unused now. Please delete it from codec/codec.h

https://github.com/4paradigm/OpenMLDB/blob/main/src/codec/codec.h#L224-L266

**Comment by WUBBBB** [comment]
Please assign this task to me

**Comment by dl239** [comment]
> Please assign this task to me

have assigned to you. thank you
