### ISSUE TITLE
Delete `Int64ToString` from  codec/codec.h

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2058]
- delete `Int64ToString` function from  codec/codec.h
https://github.com/4paradigm/OpenMLDB/blob/main/src/codec/codec.h#L313
- delete `#include <sstream>` from codec/codec.h

**Comment by Light347** [comment]
Please assign this task to me

**Comment by dl239** [comment]
> Please assign this task to me

have assigned to you, looking forward your pr

**Comment by dl239** [comment]
hi @Light347, would you like to finish this task?
