### ISSUE TITLE
bug: SQLInsertRow should be consistent with insert sql(custom column order)

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2059]
`SQLInsertRow` will do pack data(row build), so we should append data in schema order. But above this class, e.g. `InsertPreparedStatementImpl`, we'll store the current data and then build the `SQLInsertRow`, it can keep the order with insert sql.
For example:
```
table1(c1,c2,c3)
insert into table1(c3,c2,c1) values(?,?,?)
```
We should let `SQLInsertRow` the right order(c3,c2,c1), not the current `GetHoleIdx`(monotonically increasing). 
So `InsertPreparedStatementImpl` can get it, and we can do `set(1, c3_value)`, ...

I'll add a new `GetHoleIdx`(it's only used by python/java sdk), the order is consistent with insert sql.
Then make `InsertPreparedStatementImpl` get the right order.

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [kafka connector bugfix](https://trello.com/c/u7eKwIBq/123-kafka-connector-bugfix)

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.6.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-06x)
