### ISSUE TITLE
remove the `explicit` keyword for copy-constructor in `list_iterator_codec.h`

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#2061]
two place:
- https://github.com/4paradigm/OpenMLDB/blob/3cc6a64f4e41323b5090753cf22ac219b5b30b32/hybridse/include/codec/list_iterator_codec.h#L263
- https://github.com/4paradigm/OpenMLDB/blob/3cc6a64f4e41323b5090753cf22ac219b5b30b32/hybridse/include/codec/list_iterator_codec.h#L200

**Comment by Shigm1026** [comment]
Please assign this task to me

**Comment by lumianph** [comment]
@nj-sgm  noted, assigned to you

**Comment by Shigm1026** [comment]
> @nj-sgm noted, assigned to you


HiI have already removed the explicit keyword, could you please review it? thank you
