### ISSUE TITLE
ut: avoid using "_" in test name in "client_manager_test"

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2066]
https://github.com/4paradigm/OpenMLDB/blob/99500356447a16d79404496133746841f62d1a5d/src/catalog/client_manager_test.cc#L26
use UpperCamelCase, `client_manager_test` to `NormalTest`, or other test name.

**Comment by PrajwalBorkar** [comment]
I like to work on this issue, can you suggest a test name because ClientManagerTest is already used there.

**Comment by dl239** [comment]
> I like to work on this issue, can you suggest a test name because ClientManagerTest is already used there.

you can use `NormalTest`
