### ISSUE TITLE
fix typos in Chinese docs

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#2074]
two typos:
1. https://github.com/4paradigm/OpenMLDB/blob/99500356447a16d79404496133746841f62d1a5d/README_cn.md?plain=1#L53
（2）具备毫秒级延迟的的高性能**实时 SQL 引擎**；=> （2）具备毫秒级延迟的高性能**实时 SQL 引擎**；
remove a duplicate "的"
2. https://github.com/4paradigm/OpenMLDB/blob/99500356447a16d79404496133746841f62d1a5d/docs/zh/about/intro.md?plain=1#L25
the same as the first typo

**Comment by tiammomo** [comment]
Please assign this task to me

**Comment by lumianph** [comment]
> Please assign this task to me

assigned to you
