### ISSUE TITLE
Remove unnecessary `DECLARE` in cmd/sql_cmd_test.cc

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2090]
Remove unnecessary `DECLARE` in cmd/sql_cmd_test.cc
`DECLARE_bool(interactive);`
https://github.com/4paradigm/OpenMLDB/blob/main/src/cmd/sql_cmd_test.cc#L39

**Comment by Harshvardhantomar** [comment]
I would like to try to solve this issue. Can u open it for me?

**Comment by dl239** [comment]
> I would like to try to solve this issue. Can u open it for me?

have assigned to you, thank you
