### ISSUE TITLE
Engine status message enbale/disable trace info

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#210]
**Is your feature request related to a problem? Please describe.**
![企业微信截图_4ec58310-46d5-4982-88b4-44dad6244227](https://user-images.githubusercontent.com/6291173/128548440-69750d75-3960-42f8-8abe-548a144ef347.png)

The error message is complex and unreadable.

**Describe the solution you'd like**
The compile error info can be simplified if users choose to ignore trace information.
**Describe alternatives you've considered**

**Additional context**

**Comment by aceforeverd** [comment]
use `set @@enable_trace = 'false'`
