### ISSUE TITLE
Resolve the compiling warning about `comparison of integer expressions of different signedness`

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2109]
![WX20220706-202737](https://user-images.githubusercontent.com/6183996/177550064-fce7e99d-fe6d-4a5f-af2e-34cdb12eed49.png)

https://github.com/4paradigm/OpenMLDB/blob/main/hybridse/examples/toydb/src/sdk/tablet_sdk.cc#L300

**Comment by wxltxdy** [comment]
I would like to help

**Comment by dl239** [comment]
> I would like to help

@wxltxdy  thank you, looking forward your pr

**Comment by marandabui** [comment]
Hi! I would like to help. Is it still open?

**Comment by lumianph** [comment]
> Hi! I would like to help. Is it still open?

@marandabui I have assigned to you.

**Comment by marandabui** [comment]
Hi! I just submitted a pull request for this issue and can you please give feedback? thank you so much!
