### ISSUE TITLE
After a tablet stop, many prompts appear in the CLI

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2117]
**Bug Description**
After a tablet stop, many prompts appear in the CLI, affecting the user's use
![企业微信截图_fdb3fdec-7cb1-4d6c-8ab7-bb32c19d1b2d](https://user-images.githubusercontent.com/18275570/177673243-26c8d7c8-821d-44de-88bc-ed3f83b2ffbd.png)

**Expected Behavior**
Without these tips

**Comment by aceforeverd** [comment]
should fixed by #1938, what's the openmldb version ?

**Comment by wuyou10206** [comment]
> 应该由#1938修复，openmldb 版本是多少？

v0.5.2

**Comment by aceforeverd** [comment]
fixed after v0.5.2, try latest openmldb package 

> > 应该由#1938修复，openmldb 版本是多少？
> 
> v0.5.2

**Comment by aceforeverd** [comment]
the default configuration need update, keep following

**Comment by vagetablechicken** [comment]
it’s glog printed by openmldb(zk client ), not the log printed by zk. So haven’t fixed yet

**Comment by vagetablechicken** [comment]
Similar issues #426 #656
