### ISSUE TITLE
The command showopstatus shows the OPS of all tables, and does not show the dbname

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2119]
**Bug Description**
The command showopstatus shows the OPS of all tables and does not show dbname, so it is difficult to distinguish which table it is

**Expected Behavior**
1. Show dbname
2. Only show the op under the current library

**Comment by aceforeverd** [comment]
does `show table status` meet your requirements ?

**Comment by wuyou10206** [comment]
> `show table status`符合您的要求吗？

Show table status cannot meet the requirements
