### ISSUE TITLE
The result of select from offline is incorrect  when contain  chinese characters

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2120]
![WX20220707-161709](https://user-images.githubusercontent.com/6183996/177725942-5a9b2132-dcec-438c-8579-67b3da61ebcb.png)

if use `select into xxx`, the result is ok

![WX20220707-161801](https://user-images.githubusercontent.com/6183996/177726126-a183b52f-5c73-4a8e-b0df-494722fefdbf.png)

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.6.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-06x)

**Comment by tobegit3hub** [comment]
It is the issue of encoding of Operating System. If the OS only supports English and we want to support UTF-8 for Spark jobs, we need to pass the configurations to Spark jobs.

Here is the example to set encoding for Spark jobs and make sure the Chinese and show correctly.

Add the ini file in `/work/openmldb/bin/spark.conf`.

```
[Spark]
spark.driver.extraJavaOptions=-Dfile.encoding=utf-8
spark.executor.extraJavaOptions=-Dfile.encoding=utf-8
```

Run the SQL command-line client with the following command.

```
./openmldb/bin/openmldb --zk_cluster=127.0.0.1:2181 --zk_root_path=/openmldb --role=sql_client --spark_conf=/work/openmldb/bin/spark.conf
```

Then the offline jobs will use the Spark configuration and make sure the Chinese can be shown correctly.

**Comment by tobegit3hub** [comment]
More docs in https://openmldb.ai/docs/zh/main/maintain/faq.html#id4 .
