### ISSUE TITLE
script: rm /tmp/* is not good and zk cleanup does not work

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2121]
https://github.com/4paradigm/OpenMLDB/blob/e4354c44956a973356f86d97b111fc1a41802c17/demo/init.sh#L29

Only rm /tmp/openmldb_offline_storage/ here.

And rm /tmp/zookeeper then restart zookeeper won't clean meta data. rm /tmp/zookeeper will rm the pid file, zookeeper won't be killed.

So we need to `stop zk && rm /tmp/zookeeper && start zk`

**Comment by mangoGoForward** [comment]
I'd like to tackle it
