### ISSUE TITLE
Remove `NOLINT` from some include statement

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2125]
Remove `NOLINT` from the `#include "common/timer.h` statement in following files:
- src/storage/disk_table_test.cc
- src/storage/disk_table.h

update `#include "common/timer.h"  // NOLINT` as below:
`#include "common/timer.h" `

**Comment by lodenrogue** [comment]
What was the original reason behind adding // NOLINT? Do we still need that functionality?

**Comment by dl239** [comment]
> What was the original reason behind adding // NOLINT? Do we still need that functionality?

if the include file do not contain dir name like `#include "timer.h"`,  `cpplint` warning will be reported. so we can add `NOLINT` to avoid warnings.
