### ISSUE TITLE
cpplint: convert all non-const ref `job_info` to pointer in sql_cluster_router.h

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2135]
https://github.com/4paradigm/OpenMLDB/blob/c748d5887a0409433f0d68b43fc8792bcde69d89/src/sdk/sql_cluster_router.h#L266

We use `JobInfo& job_info` to be the output, it's not good. We should convert it to a pointer.
Contains:
`ImportOnlineData`, `ImportOfflineData`, `ExportOfflineData`, `ExecuteOfflineQueryAsync`, `ExecuteOfflineQueryGetOutput`

**Comment by aceforeverd** [comment]
need code change in caller side ?

**Comment by jiang1997** [comment]
Hi, I'm interested in fixing this issue.
As I understand, I am supposed to modify the classes of ``TaskManagerClient`` and ``SQLClusterRouter`` for this issue. Am I Right?

**Comment by vagetablechicken** [comment]
> need code change in caller side ?

Nope, the 5 methods are not the override methods, just for SQLClusterRouter internal and TaskManagerClient

**Comment by vagetablechicken** [comment]
> Hi, I'm interested in fixing this issue. As I understand, I am supposed to modify the classes of `TaskManagerClient` and `SQLClusterRouter` for this issue. Am I Right?

Yes. Just the 5 methods in TaskManagerClient and SQLClusterRouter.  If you don't mind, you can change `ShowJobs` and other methods in TaskManagerClient too.
Assigned, waiting for your pr~ If you need help, just ask for it.

**Comment by jiang1997** [comment]
> 

I get it.

**Comment by jiang1997** [comment]
> > Hi, I'm interested in fixing this issue. As I understand, I am supposed to modify the classes of `TaskManagerClient` and `SQLClusterRouter` for this issue. Am I Right?
> 
> Yes. Just the 5 methods in TaskManagerClient and SQLClusterRouter. If you don't mind, you can change `ShowJobs` and other methods in TaskManagerClient too. Assigned, waiting for your pr~ If you need help, just ask for it.

I get it.
