### ISSUE TITLE
For a single node cluster, the disk table kreloadtableop fails after the tablet is restarted

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2166]
**Bug Description**
For a single node cluster, restart the tablet after making a snapshot, and the disk table kreloadtableop fails

According to the log, it is roughly estimated that rename failed when making snapshot
![企业微信截图_510b990f-6fd5-4028-a36c-0149be92905f](https://user-images.githubusercontent.com/18275570/178727882-8fc3d293-c17f-4413-9dcf-89bc259289c4.png)
![企业微信截图_5a0e6617-def3-4e5c-8069-11299d2411bd](https://user-images.githubusercontent.com/18275570/178727972-2e1363ea-3396-4a48-8094-205bd18b84df.png)

**Expected Behavior**
The status of kreloadtableop is kdone

**Steps to Reproduce**
1. Deploy a single node cluster with only one ns and one tablet
2. Create SSD and HDD tables and insert 100 pieces of data
3. Execute make snapshot operation
4. Restart tablet
5. showopstatus

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.6.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-06x)
