### ISSUE TITLE
docs: the introduction of data type timestamp is not compeleted

### ISSUE THREAD

**Issue by michelle-qinqin** [4paradigm/OpenMLDB#2172]
https://openmldb.ai/docs/en/main/reference/sql/data_types/date_and_time_types.html
https://openmldb.ai/docs/zh/main/reference/sql/data_types/date_and_time_types.html

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.6.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-06x)
