### ISSUE TITLE
Support `delete` in kafka connector

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2193]
Support `delete` in kafka connector
- support `delete` sql in hybridse and sdk
- add `DeletePreparedStatement` to jdbc
- tackle `DELETE` op_type and list data filed

**Comment by vagetablechicken** [comment]
It's not a common case, so I think kafka connector which support delete should not be merged into main branch. We should create a branch for it.
The delete support of OpenMLDB should be merged into main branch.

**Comment by dl239** [comment]
It's better to design a JsonAdapter to adapt most of custom json data.
