### ISSUE TITLE
taskmanager log will print to the console

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2203]
https://github.com/4paradigm/OpenMLDB/blob/239ada3fb49a58222d8e2f0fa49d42a531bd01ac/release/bin/start.sh#L95

**Comment by vagetablechicken** [comment]
@dl239 shall we `sh ./taskmanager.sh > /dev/null 2>&1 & ` or print zk&openmldb cxx logs to another file?

**Comment by dl239** [comment]
![3ff56ffba2af2182c1bc9dd74](https://user-images.githubusercontent.com/6183996/183808698-9bc48f76-473f-4dd7-90c3-54c681f3df4b.png)
