### ISSUE TITLE
table is not exist when deploying sql by apiserver

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2204]
**Bug Description**
nameserver.log:
```
 W0719 10:59:58.622728 85835776 name_server_impl.cc:9040] table[example_table] is not exist!
 W0719 11:01:36.975375 82079744 name_server_impl.cc:9040] table[example_table] is not exist!
 W0719 11:03:21.363699 79933440 name_server_impl.cc:9040] table[example_table] is not exist!
```

**Expected Behavior**
The root cause is no db info when we deploying sql by apiserver. We can deploy in CLI, cuz we do use db, ns_client::db_ has set. But in apiserver, db_ is empty.

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.6.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-06x)
