### ISSUE TITLE
Show table status display error

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2216]
**Bug Description**
The following two kinds of SQL create tables. Show table status shows that partition is wrong
+ sql1
```sql
create table t3 (c1 string NOT NULL,c2 int,c3 timestamp,c4 timestamp,index(key=(c1),ts=c4,ttl=0m))
options (
partitionnum = 0,
replicanum = 3,
distribution = [ ('172.24.4.55:30001', [ '172.24.4.55:30002','172.24.4.55:30003' ])]
);
```
The actual partition of sql1 is 1, but the show table status is 0.
![609ddd5291d29f9c6456e3023af64d98](https://user-images.githubusercontent.com/18275570/180205194-0a4e3387-d2f7-4f90-bdc5-21bd53299c53.png)
![32d3c987923bd5e392d9f93103edf237](https://user-images.githubusercontent.com/18275570/180205211-c8ae85fb-d103-4926-8983-21ed3741b529.png)
+ sql2
```sql
create table t4 (c1 string NOT NULL,c2 int,c3 timestamp,c4 timestamp,index(key=(c1),ts=c4,ttl=0m))
options (
partitionnum = 0,
replicanum = 3
);
```
The actual partition of SQL2 is 1, but the show table status is 8
![a23b6a2dcdd3ea7d17b8dbc8a1f32ab0](https://user-images.githubusercontent.com/18275570/180205301-c416d992-b339-44c4-a3bf-d153bb984255.png)
![ac3fab2926c5354a3d1525a880362824](https://user-images.githubusercontent.com/18275570/180205315-f5f9f635-5583-46ce-8e3b-aadb32a2608b.png)

**Expected Behavior**

The partition of both tables should show 1.

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by aceforeverd** [comment]
why sql2 is 1 ?

**Comment by aceforeverd** [comment]
partition default to `FLAGS_partition_num`
https://github.com/4paradigm/OpenMLDB/blob/652a4ea169ca7e273d9e12175e867e16fcb396d5/src/nameserver/name_server_impl.cc#L2201-L2206
