### ISSUE TITLE
After the nameserver restarts, use the apiserver (and other clients) access interface to prompt an error

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2234]
**Bug Description**
After the nameserver restarts, use the apiserver access interface to prompt an error
<img width="678" alt="99c7ab9f50e8293f073b789c209595f6" src="https://user-images.githubusercontent.com/18275570/180693617-13c888e8-57a1-4879-b2b2-abf0726ebcfc.png">

**Expected Behavior**
Can be accessed normally

**Steps to Reproduce**

1.  Deploy a cluster environment with at least two nameservers
2.  Restart one of the nameservers
3.  Call apiserver interface
4.

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.6.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-06x)

**Comment by vagetablechicken** [comment]
Fixed by ab8f2bb. But 05x doesn't contain the commit.

**Comment by aceforeverd** [comment]
@wuyou10206 Pls recheck from the main branch 

> Fixed by [ab8f2bb](https://github.com/4paradigm/OpenMLDB/commit/ab8f2bb2215ef73b78c511d231321aab79785dfb). But 05x doesn't contain the commit.

**Comment by lumianph** [comment]
@wuyou10206 can you help confirm whether it is fixed in 0.6.0?
