### ISSUE TITLE
sql: support like predicate

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#224]
**Is your feature request related to a problem? Please describe.**

Currently, OpenMLDB doesn't support the some basic SQL syntaxes like `HAVING` clause and `LIKE` operator. There abilities are required by data scientis for data analysis.
> A **`HAVING`** clause in [SQL](https://en.wikipedia.org/wiki/SQL) specifies that an SQL `SELECT` statement must only return rows where aggregate values meet the specified conditions.

Generally, the `HAVING` clause is used in conjunction with aggregate functions and the GROUP BY clause to control which groups are selected.

## Support `LIKE` operator

The LIKE operator supports these wildcard characters in the quoted string.

#### Syntax

```
[ NOT ] { LIKE search_pattern [ ESCAPE esc_char ] }
```

#### Parameters

- **search_pattern**

  Specifies a string pattern to be searched by the `LIKE` clause. It can contain special pattern-matching characters:

  - `%` matches zero or more characters.
  - `_` matches exactly one character.

- **esc_char**

  Specifies the escape character. The default escape character is `\`.

- **regex_pattern**

  Specifies a regular expression search pattern to be searched by the `RLIKE` clause.

### Examples:

```SQL
CREATE TABLE person (id INT, name STRING, age INT);
INSERT INTO person VALUES
    (100, 'John', 30),
    (200, 'Mary', NULL),
    (300, 'Mike', 80),
    (400, 'Dan',  50),
    (500, 'Evan_w', 16);

SELECT * FROM person WHERE name LIKE 'M%';
+---+----+----+
| id|name| age|
+---+----+----+
|300|Mike|  80|
|200|Mary|null|
+---+----+----+

SELECT * FROM person WHERE name LIKE 'M_ry';
+---+----+----+
| id|name| age|
+---+----+----+
|200|Mary|null|
+---+----+----+

SELECT * FROM person WHERE name NOT LIKE 'M_ry';
+---+------+---+
| id|  name|age|
+---+------+---+
|500|Evan_W| 16|
|300|  Mike| 80|
|100|  John| 30|
|400|   Dan| 50|
+---+------+---+


SELECT * FROM person WHERE name LIKE '%\_%';
+---+------+---+
| id|  name|age|
+---+------+---+
|500|Evan_W| 16|
+---+------+---+

SELECT * FROM person WHERE name LIKE '%$_%' ESCAPE '$';
+---+------+---+
| id|  name|age|
+---+------+---+
|500|Evan_W| 16|
+---+------+---+
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [sql support for HAVING and LIKE](https://trello.com/c/CNiD1A3Q/9-sql-support-for-having-and-like)

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [sql support for LIKE](https://trello.com/c/ZgAcOGCw/26-sql-support-for-like)

**Comment by aceforeverd** [comment]
# Detailed rules

## Like predicate

```
<like predicate> := <character match expression> [NOT] (LIKE | ILIKE) <pattern expression> [ ESCAPE <escape character> ]
```

## Like Operator
- `LIKE` case sensitive, `ILIKE` case insensitive

## Nullable
- any of `<match expression> or <pattern expression>` is null, return null. Else return true or false

## Escape character
- <escape character> is string literal, size must <= 1, or raise: data exception, invalid escape character
- if `ESCAPE` not given, default to backslash(`\`), in sql, should write as `\\`
- if `ESCAPE` is specified as empty string, disable escape feature (same as postgre extension: It effectively disables the escape mechanism, which makes it impossible to turn off the special meaning of underscore and percent signs in the pattern.)

## Pattern Expression
- string literal or any expression evaluated to string
- data exception: invalid escape sequence
    - **strictly, the following character of <escape character> is not underscore(`_`), percent(`%`), <escape character>, is considered as invalid escape sequence**
    - currently, we do not implement this limitation, instead we try to match invalid escape character as well.

## like udf
- `like_match(nullable<string>, nullable<string>, nullable<string>)`
- `like_match(nullable<string>, nullable<string>)`
- `ilike_match(nullable<string>, nullable<string>, nullable<string>)`
- `ilike_match(nullable<string>, nullable<string>)`

    same rules as like operator, with one addition:
    - nullable: any of `<match>, <pattern>, <escape>` is null, return null
