### ISSUE TITLE
fix comment of getJobLog

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2251]
https://github.com/4paradigm/OpenMLDB/blob/165034f973006d11b0cb3c97565ceef288ca6120/java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java#L366-L369

'show batch version' is wrong.

**Comment by lukeAyin** [comment]
Please assign this task to me

**Comment by hv789** [comment]
I did a PR but it failed in 2 checks. Can someone plz suggest what went wrong.
PR #2310
