### ISSUE TITLE
When there is expired data in the time window, the results of request mode and batch mode are inconsistent.

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2256]
**Bug Description**

+ When the current row data expires, the results of batch mode and request mode are different.
+ When there is expired data in the main table, the window calculation is carried out. The result of request mode is different from that of batch mode.

**Expected Behavior**
The calculation structure of request mode is consistent with that of batch mode

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by aceforeverd** [comment]
@dl239 I'm not sure, need help

**Comment by aceforeverd** [comment]
@wuyou10206 can u give a reproduced case?

**Comment by aceforeverd** [comment]
can't reproduce
