### ISSUE TITLE
Support Java SDK 10 and above version

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#2258]
Now we can not compile the java modules with JDK 10 and above version.

Here is the error message.

<img width="1792" alt="Screen Shot 2022-07-28 at 11 58 16" src="https://user-images.githubusercontent.com/2715000/181458208-9e78c470-af48-4b20-b0d9-c580d20077f4.png">

And the root cause is the version of `lombok`.  Refer to https://stackoverflow.com/questions/50315508/errorjava-java-lang-exceptionininitializererror-intellij .

**Comment by aceforeverd** [comment]
dup #1094
