### ISSUE TITLE
Coredump or killed by OOM when enabling UnsafeRowOpt for Criteo dataset

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#2269]
Now we have some bugs which occurs coredump or killed by OOM when enabling UnsafeRowOpt for Criteo dataset.

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.6.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-06x)

**Comment by tobegit3hub** [comment]
Resolved by https://github.com/4paradigm/OpenMLDB/pull/2273 .
