### ISSUE TITLE
The deleted column is not an index and cannot run successfully. The table does not delete data

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2272]
**Bug Description**
The deleted column is not an index and cannot run successfully. The table does not delete data.

**Expected Behavior**
Prompt error message.

**Steps to Reproduce**

1.  
```
create table auto_GRaFKeEv(
c1 string,
c2 smallint,
c3 int,
c4 bigint,
c5 float,
c6 double,
c7 timestamp,
c8 date,
c9 bool,
index(key=(c1),ts=c7))options(partitionnum=1,replicanum=1);
```
2. 
```
delete from auto_GRaFKeEv where c2=1;
```
3. 
4.

**Comment by dl239** [comment]
has error msg as below:
![WX20220829-175825](https://user-images.githubusercontent.com/6183996/187176216-3c1ed117-8290-43fb-a109-f1a472d82da7.png)
