### ISSUE TITLE
filter_key is not added into the dimension key

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#2307]
**Bug Description**
The index of pre-aggr table is <key, filter_key>. However, in `aggregator`, the dimension key is `key` only, which is not consistent with the index definition.

Two possible solutions:
- add the `filter_key` to the dimension key (problem: cannot easily delete if base table deletes)
- change the index to <key> (problem: there will be multiple entries for the  same <key, ts>. It is not feasible for disk table).

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pre-aggregate support xxx_where](https://trello.com/c/qFWsyu8b/66-pre-aggregate-support-xxxwhere)
