### ISSUE TITLE
feat: add CONTRIBUTING.md

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#232]
have a look at
+ https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md
+ https://github.com/neovim/neovim/blob/master/MAINTAIN.md

**Comment by imotai** [comment]
Can we covert this issue to discussion called "How to make contribution to Hybridse"

**Comment by aceforeverd** [comment]
Should add those two file.

**Comment by aceforeverd** [comment]
We might need a place to discuss things related to all repos. Eg, coding style, contribution. 

Create a discuss repo or some other way.
