### ISSUE TITLE
Some bugs of diagnostic tools

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2322]
**Bug Description**
1. When the version of the tablet is inconsistent with that of the NS, there is no prompt for check version failed
![209c9ac73f414ee7889173ad94b4147c](https://user-images.githubusercontent.com/18275570/183587953-c6a86805-e1d9-43cb-b7f3-8136fd8107e7.png)
2. When ZK in tablet is not configured, the diagnostic tool has an error
![dac5ed51fe891fa913de6d33c3f75b34](https://user-images.githubusercontent.com/18275570/183588095-eb6ac0e8-d9e9-4c62-a937-2739e3e26eff.png)
3. When there are no logs under taskmanager / bin / logs /, the diagnostic tool has an error
![7d00eedfc9a05a3f0e580ddfa97f6da3](https://user-images.githubusercontent.com/18275570/183588262-0399f779-bc06-483a-a146-349b3755028e.png)

**Expected Behavior**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by wuyou10206** [comment]
4. Some info level logs in the taskmanager logs are also printed out
![image](https://user-images.githubusercontent.com/18275570/183594618-e4f4ba0d-4d6f-4420-9113-a53089fcd9b3.png)

**Comment by wuyou10206** [comment]
5. When data_dir When the directory of dir does not exist, executing check = SQL alone will not create an error
![3243eef46d46617dbff935e604f8b91e](https://user-images.githubusercontent.com/18275570/183598487-02cc2593-3795-477b-adc4-194a9e996977.png)

**Comment by wuyou10206** [comment]
6. There is a problem with the log output in taskmanager / bin / logs
![image](https://user-images.githubusercontent.com/18275570/183603493-17e138de-f8d8-4206-9f46-8749699356d3.png)
![image](https://user-images.githubusercontent.com/18275570/183603700-59c84b2d-4919-491e-a9b6-fafd0267303a.png)

**Comment by wuyou10206** [comment]
7. The version of taskmanager is incorrect, and the obtained version is inconsistent with the actual version
![f662632688c04e47f17b0b8b091849ce](https://user-images.githubusercontent.com/18275570/183797342-c70e95f6-8c3d-43eb-b3cf-69bae8714741.png)

**Comment by wuyou10206** [comment]
8. Prompt an error each time
![2dcac7b3d2c785c808df4f4babaef8d3](https://user-images.githubusercontent.com/18275570/183797813-f8f04a0d-f31c-4632-bdd8-824932c90a54.png)

**Comment by wuyou10206** [comment]
9. Execute check = SQL immediately after tablet stop, and an error message will appear
![07547b2e3177b0c58a610641e4dd9d81](https://user-images.githubusercontent.com/18275570/183798049-836de2b7-c2b1-485b-8bdf-77e03ae4ee80.png)

**Comment by wuyou10206** [comment]
The following problems have been fixed:
1. When the version of the tablet is inconsistent with that of the NS, there is no prompt for check version failed 
4. Some info level logs in the taskmanager logs are also printed out
5. When data_dir When the directory of dir does not exist, executing check = SQL alone will not create an error

**Comment by vagetablechicken** [comment]
refacted later.
