### ISSUE TITLE
add docs for new built-in functions

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#2353]
In v0.6.0, we have quite a few new built-in functions contributed by our community, but I found there is no docs for them. We should add docs (we may also need to double check any other missing docs for built-in functions)

The existing built-in function doc: https://openmldb.ai/docs/zh/main/reference/sql/functions_and_operators/Files/udfs_8h.html

v0.6.0: new built-in functions char(int), char_length, character_length, radians, hex, median

**Comment by michelle-qinqin** [comment]
there are no docs for :  char(int),hex, median

**Comment by aceforeverd** [comment]
Depends on second task in #1707 
udf docs is generated by code.

**Comment by lumianph** [comment]
@aceforeverd but we still need to fix the invalid (like at/lag) and missing built-in functions asap, maybe we directly revise that doc first?

**Comment by aceforeverd** [comment]
> @aceforeverd but we still need to fix the invalid (like at/lag) and missing built-in functions asap, maybe we directly revise that doc first?

Yes, we may fix doc manually first. 

I'll doc the steps to generate udf document later. Meanwhile, the missing doc of linked udfs like `at -> lag` is a source code problem.

**Comment by aceforeverd** [comment]
refer #2379

**Comment by aceforeverd** [comment]
resolved
