### ISSUE TITLE
docs: window clause

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2362]
http://openmldb.ai/docs/zh/main/reference/sql/dql/WINDOW_CLAUSE.html?highlight=window#sql

make rows_rage and rows clear

**Comment by vagetablechicken** [comment]
row_range not only 1s,2s... If no timeunit ,is ms

**Comment by aceforeverd** [comment]
When there is no unit for frame bound, it is just value range, ms is default to ttl colum ?

**Comment by vagetablechicken** [comment]
> When there is no unit for frame bound, it is just value range, ms is default to ttl colum ?

I think so, I'll check it.

**Comment by vagetablechicken** [comment]
Already has it in docs. Maybe it's hard to find. I'll write a quickstart for it.
