### ISSUE TITLE
window: the right border can't work?

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2365]
We have this example:
```
            Example:

            |c1|c2|
            |--|--|
            |0 | 1|
            |1 | 1|
            |2 | 2|
            |3 | 2|
            |4 | 2|

SELECT at(c1, 1) over w as co from t1 window w as(partition by c2 order by c1 rows between unbounded preceding and current row);
                -- output
                -- | co |
                -- |----|
                -- |NULL|
                -- |0   |
                -- |NULL|
                -- |2   |
                -- |3   |
```

But run `SELECT at(c1, 1) over w as co from t1 window w as(partition by c2 order by c1 rows between unbounded preceding and 1000 preceding);` is the same result. Why?

**Comment by aceforeverd** [comment]
`lag/lead` or the old `at` function, is always relative to current row, window frame bound do not take any real meaning to the SQL engine. 

Both SQL is equivalent to  `select at(c1, 1) over (partition by c2 order by c1) from t1`.
 
`at over ( .... between A and B)` is allowed just for backward compatibility. Also to mention, it is not allowed in Spark SQL

**Comment by aceforeverd** [comment]
more discussion here #1554

**Comment by vagetablechicken** [comment]
Added more info in udf docs, close this issue
