### ISSUE TITLE
docs: invalid link in chinese docs

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#2369]
Here is the docs https://openmldb.ai/docs/zh/main/maintain/backup.html and the link of `修改openmldb包中tools目录里的env.sh` is invalid now.

<img width="1265" alt="Screen Shot 2022-08-18 at 11 28 09" src="https://user-images.githubusercontent.com/2715000/185286820-bd55f1f6-29cc-422e-ae47-df03c5cf11ce.png">

**Comment by dl239** [comment]
fixed
