### ISSUE TITLE
Remove duplicated `compile_proto` from `src/CMakeLists.txt`

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2389]
compiling `name_server` proto in Line94 is duplicated with L91, we should delete one.
https://github.com/4paradigm/OpenMLDB/blob/main/src/CMakeLists.txt#L94

**Comment by wang-jiahua** [comment]
please assign this task to me.

**Comment by dl239** [comment]
> please assign this task to me.

looking forward your pr
