### ISSUE TITLE
doc: error in the documentation example

### ISSUE THREAD

**Issue by MichaelYin1994** [4paradigm/OpenMLDB#2399]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/22712917/186399835-b7d4b68e-2cb0-42eb-9ee2-1ecc353a5317.png">

In the above documentation and SQL script, it says the intermediate SQL execution results are sorted by the attribute c6 in ascending order. However the order of execution results are random. Thus it leads to the error of the final SQL execution result.

**Comment by lumianph** [comment]
thank you for the feedback!
