### ISSUE TITLE
Remove `Get` method from `Segment` class

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2404]
`Get` is unused now, we should remove it from `Segment` class
https://github.com/4paradigm/OpenMLDB/blob/main/src/storage/segment.h#L165-L169
https://github.com/4paradigm/OpenMLDB/blob/main/src/storage/segment.cc#L273-L303
https://github.com/4paradigm/OpenMLDB/blob/main/src/storage/segment_test.cc#L54-L68
https://github.com/4paradigm/OpenMLDB/blob/main/src/storage/segment_test.cc#L388-L409

**Comment by wang-jiahua** [comment]
I would like to help

**Comment by bit-dance** [comment]
please assign this task for me
