### ISSUE TITLE
Ns_client stuck in infinite loop while Interactive set false

### ISSUE THREAD

**Issue by lqy222** [4paradigm/OpenMLDB#2429]
**Bug Description**
while using ns_client or sql_client to execute a  command with Interactive set as true(default), it will stuck in an infinite loop

**Expected Behavior**
cmd result
end

**Steps to Reproduce**
```
/openmldb --role=ns_client  --cmd show components
```
it will cause an infinite loop
```
/openmldb --role=ns_client --interactive=false --cmd show components
```
it works well

**Comment by aceforeverd** [comment]
same with `--role=sql_client`:
- when you write `--interactive false` instead `--interactive=false`
```
/openmldb --role=ns_client --interactive false --cmd='show components;'
```

**Comment by lqy222** [comment]
right, and the actually issue is --interactive must be set as false , otherwise the --cmd will cause infinite loop
