### ISSUE TITLE
After the tablet process is restarted, the following error message is displayed, and the data in the 16 columns (32 columns) after deployment is null

### ISSUE THREAD

**Issue by uttinie** [4paradigm/OpenMLDB#2453]
**Bug Description**

![image](https://user-images.githubusercontent.com/18255088/189123871-0bdb6237-137a-4117-94d9-3e07b63b874f.png)

**Expected Behavior**

1

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by uttinie** [comment]
`{
    "code": 0,
    "msg": "ok",
    "data": {
        "data": [
            [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                12,
                433,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            ]
        ]
    }
}`

**Comment by aceforeverd** [comment]
@dl239 help checkout

**Comment by dl239** [comment]
`auto_failover` has been disabled
