### ISSUE TITLE
`top_n_key_*_cate_where` did not output the one with the largest value at first

### ISSUE THREAD

**Issue by uttinie** [4paradigm/OpenMLDB#2479]
**Bug Description**
```
10.97.152.110:6527/tutorial> SELECT id,
                          -> top_n_key_count_cate_where(trans_amt, label, uid, 5) over w30d as w30d_count_trans_amt
                          -> FROM t1 
                          -> window w30d as (PARTITION BY label ORDER BY trans_time ROWS_RANGE BETWEEN 30d PRECEDING AND CURRENT ROW);
+---+--------------------+
| id|w30d_count_trans_amt|
+---+--------------------+
|  2|             UserB:1|
|  1|     UserB:1,UserA:1|
|  3|     UserB:1,UserA:2|
|  5|     UserB:2,UserA:2|
|  4|     UserB:2,UserA:3|
|  7|     UserB:3,UserA:3|
|  6|     UserB:3,UserA:4|
|  8|     UserB:3,UserA:5|
| 10|     UserB:4,UserA:5|
|  9|     UserB:4,UserA:6|
+---+--------------------+

10.97.152.110:6527/tutorial> SELECT id,
                          -> top_n_key_count_cate_where(trans_amt, label, uid, 1) over w30d as w30d_count_trans_amt
                          -> FROM t1 
                          -> window w30d as (PARTITION BY label ORDER BY trans_time ROWS_RANGE BETWEEN 30d PRECEDING AND CURRENT ROW);
+---+--------------------+
| id|w30d_count_trans_amt|
+---+--------------------+
|  2|             UserB:1|
|  1|             UserB:1|
|  3|             UserB:1|
|  5|             UserB:2|
|  4|             UserB:2|
|  7|             UserB:3|
|  6|             UserB:3|
|  8|             UserB:3|
| 10|             UserB:4|
|  9|             UserB:4|
+---+--------------------+

10.97.152.110:6527/tutorial> select * from t1;
+---+-----+---+-------+-------------------+---------+----------+--------+--------+-----+
| id|  uid|mid| cardno|         trans_time|trans_amt|trans_type|province|    city|label|
+---+-----+---+-------+-------------------+---------+----------+--------+--------+-----+
|  1|UserA| M1|1111111|2022-02-02 10:00:00|     10.0|      CASH|      SH|ShangHai| true|
|  3|UserA| M2|1111111|2022-02-03 11:00:00|     20.0|       POS|      SH|ShangHai| true|
|  4|UserA| M3|1111111|2022-02-07 11:00:00|     15.0|       POS|      SH|ShangHai| true|
|  6|UserA| M1|1111111|2022-02-07 13:00:00|     20.0|      CASH|      BJ| BeiJing| true|
|  8|UserA| M2|1111111|2022-02-08 11:00:00|     50.0|      CASH|      BJ| BeiJing| true|
|  9|UserA| M3|1111111|2022-02-08 12:00:00|    100.0|       POS|      BJ| BeiJing| true|
|  2|UserB| M3|2222222|2022-02-01 11:30:00|     10.0|       POS|      SH|ShangHai| true|
|  5|UserB| M1|2222222|2022-02-07 10:00:00|     20.0|       POS|      SH|ShangHai| true|
|  7|UserB| M2|2222222|2022-02-07 12:00:00|     30.0|       POS|      SH|ShangHai| true|
| 10|UserB| M5|2222222|2022-02-08 11:00:00|     10.0|       POS|      SH|ShangHai| true|
+---+-----+---+-------+-------------------+---------+----------+--------+--------+-----+


```
**Expected Behavior**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by aceforeverd** [comment]
1. `TopkCountCateWhere` container is wrong: https://github.com/4paradigm/OpenMLDB/blob/75e3ec231009c55a8bd4c00ac79efa106df0324d/hybridse/src/udf/default_defs/count_by_category_def.cc#L143. It is `std::map<K, V, std::less<K>>`, ordered by key, here we wish the map is ordered by value. 

2. `Update` step delete map entries too early  which might produce wrong results for `top_n_key_*_cate_where`: https://github.com/4paradigm/OpenMLDB/blob/75e3ec231009c55a8bd4c00ac79efa106df0324d/hybridse/src/udf/default_defs/count_by_category_def.cc#L174-L184. e.g input order is `[( key, category)]` as `(1, 1), (2, 2), (3, 3), (1, 1), (2, 2)`, for `top_n_key_count_cate_where(key, true, category, 2)`, map entry for `1` will be deleted during `(3, 3)` insert

**Comment by aceforeverd** [comment]
Same issue should apply to all `top_n_key_*_cate_where` udaf functions

**Comment by aceforeverd** [comment]
> 1. `TopkCountCateWhere` container is wrong: https://github.com/4paradigm/OpenMLDB/blob/75e3ec231009c55a8bd4c00ac79efa106df0324d/hybridse/src/udf/default_defs/count_by_category_def.cc#L143
>    . It is `std::map<K, V, std::less<K>>`, ordered by key, here we wish the map is ordered by value.
> 2. `Update` step delete map entries too early  which might produce wrong results for `top_n_key_*_cate_where`: https://github.com/4paradigm/OpenMLDB/blob/75e3ec231009c55a8bd4c00ac79efa106df0324d/hybridse/src/udf/default_defs/count_by_category_def.cc#L174-L184
>    . e.g input order is `[( key, category)]` as `(1, 1), (2, 2), (3, 3), (1, 1), (2, 2)`, for `top_n_key_count_cate_where(key, true, category, 2)`, map entry for `1` will be deleted during `(3, 3)` insert

Update:

I'm wrong, the udf is `top_n_key_...`, so output is order by key. 
We may need the udaf `top_n_value_....` ?

**Comment by aceforeverd** [comment]
Another note: tests may not enough for those udafs, we should improve coverage
