### ISSUE TITLE
add detail error msg for jdbc insert

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2506]
https://github.com/4paradigm/OpenMLDB/blob/053c4e3d885b237711d3719be7bf0c1905c5197e/java/openmldb-jdbc/src/main/java/com/_4paradigm/openmldb/sdk/impl/InsertPreparedStatementImpl.java#L353-L359

For example, `append failed on ${currentDataIdx}(${curType}), current data ${data}`

"build insert row failed(str size init!=actual)"

**Comment by selectbook** [comment]
I would like to contribute. Please assign it to me
