### ISSUE TITLE
add sha256sum for release pkg

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2507]
Users may download incomplete released pkgs(low download speed or interrupt ...), we should add sha256sum for them. Users can check the pkgs easily.

**Comment by aceforeverd** [comment]
ref this job https://github.com/4paradigm/hybridsql-asserts/blob/main/.github/workflows/build.yml#L162-L184

**Comment by try-agaaain** [comment]
Is it to create a shell file to check the integrity of the file?

**Comment by try-agaaain** [comment]
I want to give it a try, please assign this task to me.
