### ISSUE TITLE
fix the different signedness cmp

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2508]
https://github.com/4paradigm/OpenMLDB/blob/fdfd1f29c6b0ed46a822afdd459ea17f567ccd66/hybridse/src/vm/runner.cc#L3031
https://github.com/4paradigm/OpenMLDB/blob/fdfd1f29c6b0ed46a822afdd459ea17f567ccd66/hybridse/src/vm/runner.cc#L3061

`GetKey()` returns const uint64_t, not int64_t. You can change it to `const uint64_t` or `const auto`

**Comment by kstrifonoff** [comment]
I will do that
