### ISSUE TITLE
remove unused import in SQLRouterSmokeTest.java

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2509]
https://github.com/4paradigm/OpenMLDB/blob/5c06b0ff21199fcd8daf23399248ff39f7b3ff61/java/openmldb-jdbc/src/test/java/com/_4paradigm/openmldb/jdbc/SQLRouterSmokeTest.java#L25
https://github.com/4paradigm/OpenMLDB/blob/5c06b0ff21199fcd8daf23399248ff39f7b3ff61/java/openmldb-jdbc/src/test/java/com/_4paradigm/openmldb/jdbc/SQLRouterSmokeTest.java#L42

`SqlException` & `Random` is unused.

**Comment by kstrifonoff** [comment]
I will do that
