### ISSUE TITLE
remove unused import in StatementTest

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2511]
https://github.com/4paradigm/OpenMLDB/blob/00e229acdc79184f0a209f205d269e0ee0dca7f9/java/openmldb-jdbc/src/test/java/com/_4paradigm/openmldb/jdbc/StatementTest.java#L5

DeletePreparedStatementImpl is unused, remove it.

**Comment by haseeb-xd** [comment]
I will work on this too.

**Comment by vagetablechicken** [comment]
> I will work on this too.

Assigned
