### ISSUE TITLE
use 'empty' instead of `size()>0` in dist_lock

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2512]
https://github.com/4paradigm/OpenMLDB/blob/5c06b0ff21199fcd8daf23399248ff39f7b3ff61/src/zk/dist_lock.cc#L87

The 'empty' method should be used to check for emptiness instead of 'size'.

**Comment by haseeb-xd** [comment]
I want to work on this issue.

**Comment by vagetablechicken** [comment]
> I want to work on this issue.

Assigned
