### ISSUE TITLE
do not use declarations in the global namespace

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2513]
https://github.com/4paradigm/OpenMLDB/blob/5c06b0ff21199fcd8daf23399248ff39f7b3ff61/src/zk/dist_lock.h#L29-L30

 Using declarations in the global namespace in headers are prohibited.
Move `ThreadPool` to `openmldb::zk` space. 
`using ::openmldb::zk::ZkClient; ` is useless, remove it.

**Comment by NevilleMthw** [comment]
Is this issue being worked on? If not, do you want something like this: ```::openmldb::zk::ThreadPool;``` with line 30 removed?

**Comment by vagetablechicken** [comment]
> Is this issue being worked on? If not, do you want something like this: `::openmldb::zk::ThreadPool;` with line 30 removed?

Nope, just move line  29 in openmldb::zk space, e.g. move to line 34
https://github.com/4paradigm/OpenMLDB/blob/5c06b0ff21199fcd8daf23399248ff39f7b3ff61/src/zk/dist_lock.h#L32-L34
in the namespace, not the global namespace
