### ISSUE TITLE
Update the version  in some files to the latest version 

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2519]
Update the version to 0.6.2 in the following files:

- https://github.com/4paradigm/OpenMLDB/blob/main/benchmark/pom.xml#L30
- https://github.com/4paradigm/OpenMLDB/blob/main/benchmark/pom.xml#L35
- https://github.com/4paradigm/OpenMLDB/blob/main/demo/Dockerfile#L17

**Comment by ighmaZ** [comment]
@dl239 ! ill do this!
