### ISSUE TITLE
Reslove spelling error in nameserver

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2532]
`da_name` -> `db_name`
https://github.com/4paradigm/OpenMLDB/blob/main/src/nameserver/name_server_impl.h#L829

**Comment by NevilleMthw** [comment]
If anyone is not working on this issue, I can work on it. Thanks.

**Comment by dl239** [comment]
> If anyone is not working on this issue, I can work on it. Thanks.

thankyou, looking forward your pr
