### ISSUE TITLE
[docs] add time ordering restriction on long_windows deployment

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#2534]
**Bug Description**

Add the restriction on the [long window deployment docs](https://github.com/4paradigm/OpenMLDB/blob/main/docs/zh/reference/sql/deployment_manage/DEPLOY_STATEMENT.md#%E9%99%90%E5%88%B6%E6%9D%A1%E4%BB%B6):
- It requires the data is loaded in the order of `timestamp` column in order to get the best performance boost

**Comment by Jake-00** [comment]
Coz work was done, maybe we can close this issue.
