### ISSUE TITLE
[docs] add more common configs for `spark.conf`

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#2545]
**Describe the feature you'd like**
In [client_spark_config.md](https://github.com/4paradigm/OpenMLDB/blob/main/docs/zh/reference/client_config/client_spark_config.md),
add more general configures from spark, say
```
[Spark]
spark.driver.extraJavaOptions=-Dfile.encoding=utf-8
spark.executor.extraJavaOptions=-Dfile.encoding=utf-8
spark.executor.cores=1
spark.default.parallelism=1
spark.executor.memory=4g
```

and add a reference link to the official spark configuration page: https://spark.apache.org/docs/latest/configuration.html

**Comment by Jake-00** [comment]
Hi, there! Can you assign this issue to me?

**Comment by zhanghaohit** [comment]
> Hi, there! Can you assign this issue to me?

Sure. Thanks for your interest.
