### ISSUE TITLE
Clean unused code 

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2551]
https://github.com/4paradigm/OpenMLDB/blob/main/src/client/client.h#L29-L30
https://github.com/4paradigm/OpenMLDB/blob/main/src/client/tablet_client.h#L35-L37

**Comment by gokullan** [comment]
Hi, there! Can you assign this issue to me?

**Comment by dl239** [comment]
> Hi, there! Can you assign this issue to me?

assigned to you, looking forward your pr
