### ISSUE TITLE
Fix memory leak in tablet_impl_test

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2579]
https://github.com/4paradigm/OpenMLDB/blob/v0.6.2/src/tablet/tablet_impl_test.cc#L3576
https://github.com/4paradigm/OpenMLDB/blob/v0.6.2/src/tablet/tablet_impl_test.cc#L3624

fix as below:
```
::openmldb::api::TraverseResponse srp;
tablet.Traverse(NULL, &sr, &srp, &closure);
ASSERT_EQ(0, srp.code());
ASSERT_EQ(100, (signed)srp.count());
```

**Comment by haseeb-xd** [comment]
Can i make this change?
