### ISSUE TITLE
correct the doc of built-in function `RADIANS(90)`

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#2587]
**Bug Description**

<img width="607" alt="image" src="https://user-images.githubusercontent.com/7508922/192755054-0cee4efc-9669-436d-99b3-12e73fb51809.png">

The example `SELECT RADIANS(90);` cannot execute successfully. This is because integers are not supported in `RADIANS`. It should be ``SELECT RADIANS(90.0);`` 

**Note that, you should not revise the doc directly, as it is generated from the code. You should change the comments in the code file https://github.com/4paradigm/OpenMLDB/blob/411b1a265586f8329b8627b237c459082ec51cd6/hybridse/src/udf/default_udf_library.cc#L1613**

**Comment by aceforeverd** [comment]
part 2 is not good first

**Comment by auula** [comment]
I would like to try this task, but I am not familiar with C++ language, please I some guidance advice, thanks 🙏
