### ISSUE TITLE
Remove unused code from sql_cluster_availability_test

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2588]
remove the following code:
https://github.com/4paradigm/OpenMLDB/blob/main/src/tablet/sql_cluster_availability_test.cc#L38-L39
https://github.com/4paradigm/OpenMLDB/blob/main/src/tablet/sql_cluster_availability_test.cc#L44
https://github.com/4paradigm/OpenMLDB/blob/main/src/tablet/sql_cluster_availability_test.cc#L53-L59

**Comment by lbartyczak** [comment]
Hello! I would like to work on this as my first open source contribution, can you please assign this to me?

**Comment by dl239** [comment]
> Hello! I would like to work on this as my first open source contribution, can you please assign this to me?

assigned to you, thank you
