### ISSUE TITLE
Replace `__INTERNAL_DB` with `openmldb::nameserver::INTERNAL_DB` in sql_cluster_router

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2593]
https://github.com/4paradigm/OpenMLDB/blob/v0.6.2/src/sdk/sql_cluster_router.cc#L1875
https://github.com/4paradigm/OpenMLDB/blob/v0.6.2/src/sdk/sql_cluster_router.cc#L1894
modify as below:
```
std::string db = openmldb::nameserver::INTERNAL_DB;
```

**Comment by shivamgupta-sg** [comment]
Please assign this to me

**Comment by dl239** [comment]
> Please assign this to me

assigned to you, looking forward your pr
