### ISSUE TITLE
OpenMLDB use the same docker and thirdparty with hybridse

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#261]
**Is your feature request related to a problem? Please describe.**

Now that OpenMLDB are using hybridsql:0.3.0 while hybridse are using hybridsql:0.4.0.
**Describe the solution you'd like**

OpenMLDB should share the same version docker environment and third-party libraries with hybridse
 
**Describe alternatives you've considered**

**Additional context**

**Comment by aceforeverd** [comment]
#271 resolve using the same thirdparty
