### ISSUE TITLE
unit test output to file by default

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#2619]
**Bug Description**
Now ut test's output is directed to `logs` files rather than to the screen as previously. Not easy to debug especially when in cicd. We may need to revert to the previous behaviour?

**Expected Behavior**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by aceforeverd** [comment]
should resolved by #2539 for all tests in `src/sdk`

**Comment by zhanghaohit** [comment]
fixed in #2539
