### ISSUE TITLE
merge the two versions of `ScanIndex` in `tablet_impl.cc`

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#2632]
**Describe the feature you'd like**

Most of the logics of the two `ScanIndex` are the same, except the `output` buffer. We'd better merge these two.

```
int32_t TabletImpl::ScanIndex(const ::openmldb::api::ScanRequest* request, const ::openmldb::api::TableMeta& meta,
                              const std::map<int32_t, std::shared_ptr<Schema>>& vers_schema,
                              CombineIterator* combine_it, std::string* pairs, uint32_t* count, bool* is_finish);
int32_t TabletImpl::ScanIndex(const ::openmldb::api::ScanRequest* request, const ::openmldb::api::TableMeta& meta,
                              const std::map<int32_t, std::shared_ptr<Schema>>& vers_schema,
                              CombineIterator* combine_it, butil::IOBuf* io_buf, uint32_t* count, bool* is_finish);
```

**Comment by jkpjkpjkp** [comment]
Though 2 `ScanIndex` functions have 40ish identical lines, I see no obvious way to elegantly merge them together, lest using a global `define`, since their common lines are mainly declarations of local variables.

**Comment by try-agaaain** [comment]
I am interested in this task, can it be assigned to me?

**Comment by zhanghaohit** [comment]
> I am interested in this task, can it be assigned to me?

Thanks for your interest. I've assigned this task to you.

**Comment by try-agaaain** [comment]
In order to merge these two ScanIndex functions, I have set up the compilation environment and compiled tablet_impl_test for debugging. However, because I do not know the business logic, I cannot clearly understand the implementation process of the two ScanIndex functions. Could you please give me some suggestions?

**Comment by dl239** [comment]
another function deleted in #3572
