### ISSUE TITLE
Adding indexes in another database failed

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2644]
**Bug Description**
Add an index in another database, and the prompt does not exist.

Deleting an index may have the same problem.

![image](https://user-images.githubusercontent.com/18275570/195311446-784d7667-f744-4480-bd1c-e1be31fe4291.png)

**Expected Behavior**
Success
**Relation Caser**
test_delete_index.yaml  id:1

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by dl239** [comment]
done in #2720
