### ISSUE TITLE
Some bugs in online batch mode

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2681]
**Bug Description**

1. Order by refers to int and smallint, which are expected to fail but actually succeed，case：error_window.yaml，id：33/34

**Expected Behavior**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by zhanghaohit** [comment]
> Order by refers to int and smallint, which are expected to fail but actually succeed，case：error_window.yaml，id：33/34

These two cases are not due to their types `int` or `smallint`. They failed due to
```
Isn't partition provider
```

For batch mode, there is no requirements on the index.

**Comment by aceforeverd** [comment]
@wuyou10206 Pls pay attention to issue title, `Some bugs in online batch mode` is not informative

**Comment by aceforeverd** [comment]
for batch mode, order by column can be `intxxx or timestamp`, this is expected
