### ISSUE TITLE
Error adding and deleting indexes on other databases

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2690]
**Bug Description**
Error adding and deleting indexes on other databases
It is possible to add and delete indexes on the database where the table is located

![image](https://user-images.githubusercontent.com/18275570/196672539-84954c6e-fe26-4ea4-be3d-94d68a326965.png)

**Expected Behavior**

**Relation Case**
test_delete_index.yaml  id：1-1

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by aceforeverd** [comment]
`db_name` not handled 
https://github.com/4paradigm/OpenMLDB/blob/8c430fae68aa9a6a85b227d54ce362808f60962e/src/client/ns_client.cc#L884
