### ISSUE TITLE
Memory is not released after executing SQL in online environment batch mode

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#2713]
**Bug Description**
Memory is not released after executing SQL in online environment batch mode.

data:1000w=10 key*100w , Ts Repeat

Execute SQL Before(10:31):
![df913a18963ca71c86ba0404d3b110d4](https://user-images.githubusercontent.com/18275570/197302829-39751c92-92ab-4b7b-bdfa-d8ab993a58c0.png)
In process(17:52):
![d2d02fdfa361195c00dfa93153952a65](https://user-images.githubusercontent.com/18275570/197302944-f35edfb1-4014-4cc6-990d-346e55d7691b.png)
end(22:00):
![37e227923010d95011ee01f6c1d77b7d](https://user-images.githubusercontent.com/18275570/197303107-a1f641f6-d420-4d92-bfa0-55d750342ead.png)
The next day(7:02):
![image](https://user-images.githubusercontent.com/18275570/197303139-4927a1d2-9765-4fbc-ac95-9453f0d2e326.png)

**Expected Behavior**

**Relation Case**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by dl239** [comment]
has not reproduced
