### ISSUE TITLE
`show job` without `jobid` causes segment fault

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#2771]
**Bug Description**
As described in the title. It should raise an error rather than `segment fault`

**Expected Behavior**

**Relation Case**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by aceforeverd** [comment]
Primarily expecting this error will reported by zetasql. But not

**Comment by aceforeverd** [comment]
`JOB` is not a reserved keyword, so `show job` apply to this rule too. 

https://github.com/4paradigm/zetasql/blob/96dca44615c45c932b51a9f4be09f06a88e5731f/zetasql/parser/bison_parser.y#L3574

This also affect to `JOBLOG`, `DEPLOYMENT`

**Comment by aceforeverd** [comment]
```
SHOW JOB;
--
ShowStatement [0-8]
  Identifier(JOB) [5-8]
```
