### ISSUE TITLE
studio.4.2.0安装的rtidb启动coredump

### ISSUE THREAD

**Issue by liudan182** [4paradigm/OpenMLDB#278]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

## Expected Behavior
通过studio 4.2.0的包 部署rtidb程序 1.6.3.0
启动报core dump
客户环境 虚拟机 centos7.7.1908
已升级至4.14的内核
<img width="1197" alt="企业微信截图_2dff714d-47ab-4f2b-b51c-d6bef8659822" src="https://user-images.githubusercontent.com/40648991/129999073-4105a046-f088-40ce-a12c-44804216ca46.png">
<img width="1180" alt="企业微信截图_059f6c46-b50d-4bd5-a22d-9eae05dcd40d" src="https://user-images.githubusercontent.com/40648991/129999094-89097af0-ff75-49de-b9c6-f40cbabe5f96.png">
<img width="1176" alt="企业微信截图_5885ea2a-06f6-497e-af6d-55fdd7d13da4" src="https://user-images.githubusercontent.com/40648991/129999109-7d77e38c-6d1e-418d-804c-8a1f139073e4.png">

## Steps to Reproduce

1.
2.
3.
4.

**Comment by dl239** [comment]
是环境缺少某些cpu指令集如avx2。
部署环境是虚拟机吧，配置虚拟机的cpu指令集和物理机的一样一般就能解决
