### ISSUE TITLE
Remove the config of `namenode.uri` in TaskManager

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#2787]
We may support reading HDFS without setting `namenode.uri`.

**Comment by vagetablechicken** [comment]
relat issue #1266

**Comment by vagetablechicken** [comment]
Drop table will be failed on delete deep-copied hdfs path, cuz namenode.uri is empty. It should be fixed in high priority.

**Comment by vagetablechicken** [comment]
Find a new delete way to delete hdfs path, it should read configs from hadoop conf dir
