### ISSUE TITLE
`select xxx into outfile` execute failed if table is empty in offline mode

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2790]
![WX20221115-183719](https://user-images.githubusercontent.com/6183996/201898595-68e070ac-98ca-4e1c-8644-e851b3b39703.png)

**Comment by vagetablechicken** [comment]
If select result is empty, users often think that the cluster is wrong, and we must know the result is empty from the log. So if result is empty, the job will be marked as failed
