### ISSUE TITLE
The example of function date_format is incorrect

### ISSUE THREAD

**Issue by aiwtb** [4paradigm/OpenMLDB#2803]
**Bug Description**

The example of function date_format is incorrect.

**Expected Behavior**

Modify the example to "select date_format(date(timestamp(1590115420000)),"%Y-%m-%d");".

**Relation Case**

select date_format(date(1590115420000),"%Y-%m-%d");

**Steps to Reproduce**

1. set @@execute_mode="online";
2. select date_format(date(1590115420000),"%Y-%m-%d");

**Comment by aiwtb** [comment]
The page URL is https://openmldb.ai/docs/zh/main/reference/sql/functions_and_operators/Files/udfs_8h.html#function-date-format

**Comment by aceforeverd** [comment]
Thanks. PRs welcome ~

**Comment by AdvancedUno** [comment]
Hello @aceforeverd  , is this issue still open? If so, I would like to work on it!
