### ISSUE TITLE
style: enforece cpp style convention in hybridse

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#286]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

**background**
cpp code should follow our style guide: https://github.com/4paradigm/rfcs/blob/main/style-guide/code-convention.md

**task**
some api in `hybridse::vm::EngineOptions` do not follow Google Style
https://github.com/4paradigm/HybridSE/blob/main/include/vm/engine.h#L50

include and not limit to 
- [x] `SQLNode`, `PhysicalOpNode` 's `getter`/`setter` name
- [x] `EngineOptions`

**hint**
you may give a summary of which part of code will tweaked first. And only focus on cpp code in `hybridse` subdirectory currently

**Comment by FrankSzn** [comment]
Is there any doc about the local test related to EngineOptions, SQLNode, PhysicalNode to verify it work correctly after change the style to google cpp style ? Like, for example, toydb_engine_test.cc, it is a test which used EngineOptions, I want to check whether it work correctly, but I'm not clear how to test it locally . Or is there a test framework to verify the commit code? Thanks for your reply!

**Comment by jingchen2222** [comment]
> Is there any doc about the local test related to EngineOptions, SQLNode, PhysicalNode to verify it work correctly after change the style to google cpp style ? Like, for example, toydb_engine_test.cc, it is a test which used EngineOptions, I want to check whether it work correctly, but I'm not clear how to test it locally . Or is there a test framework to verify the commit code? Thanks for your reply!

Thanks @FrankSzn . You can compile and test plan and engine locally by the following steps:
1. setup the env: install third-party and create symbol link. Check [setup_thirdparty.sh](https://github.com/4paradigm/OpenMLDB/blob/main/steps/setup_thirdparty.sh).
2. compile & test (check [hybridse_core_test](https://github.com/4paradigm/OpenMLDB/blob/main/hybridse/tools/hybridse_core_test.sh)).
```shell
> cd YOUR_PROJECT_ROOT/OpenMLDB/hybridse/
> mkdir build && cd build
> cmake .. 
> make 
> SQL_CASE_BASE_DIR=YOUR_PROJECT_ROOT/OpenMLDB make test
```

If you just want to run spefic test file (e.g., toydb_engine_test), find the path of the test and run it.
```shell
> cd YOUR_PROJECT_ROOT/OpenMLDB/
> cd hybridse/build

> SQL_CASE_BASE_DIR=YOUR_PROJECT_ROOT/OpenMLDB ./example/toydb/src/testing/toydb_engine_test
```
Hope this answer can help. :)

**Comment by FrankSzn** [comment]
Thanks for your clear guide!

**Comment by aceforeverd** [comment]
similar issues https://github.com/4paradigm/OpenMLDB/pull/609/files#r740130601
