### ISSUE TITLE
Resolve comparison of integer expressions compiling warning

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2869]
```
/openmldb/src/sdk/sql_cluster_router.cc: In member function ‘bool openmldb::sdk::SQLClusterRouter::CheckTableStatus(const string&, const string&, uint32_t, const openmldb::nameserver::TablePartition&, uint32_t, const TableStatusMap&, std::string*)’:
/openmldb/src/sdk/sql_cluster_router.cc:4081:50: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::unordered_map<std::basic_string<char>, openmldb::api::TableStatus>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
         if (partition_info.partition_meta_size() != partition_statuses.size()) {
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

https://github.com/4paradigm/OpenMLDB/blob/v0.6.9/src/sdk/sql_cluster_router.cc#L4081

**Comment by ryuusama09** [comment]
https://github.com/ryuusama09/OpenMLDB/pull/1
Linking the pull request here @dl239 , do let me know if you still find the same issue

**Comment by dl239** [comment]
> [ryuusama09#1](https://github.com/ryuusama09/OpenMLDB/pull/1) Linking the pull request here @dl239 , do let me know if you still find the same issue

@ryuusama09 base repository should be 4paradigm as below:
<img width="846" alt="WX20221220-090813@2x" src="https://user-images.githubusercontent.com/6183996/208557761-04e4454e-c85e-49ea-8716-6c40e6ec5a1f.png">

**Comment by debasis9658** [comment]
Hey @dl239 I would like to work on this issue. It would be great if I can be assigned to this project. Thank You
