### ISSUE TITLE
udf doc of count_cate_where is incorrect

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#2882]
**original**

`count_cate_where(category, value, condition)`

**correct**

`count_cate_where(value, condition, category)`

**Comment by aceforeverd** [comment]
another note:

`count_cate` or `count_cate_where` should support value type like `string, timestamp, date` as well

**Comment by lumianph** [comment]
pls help fix the doc asap. the second note can be a separate issue
