### ISSUE TITLE
docs: demo in c++ doc needs to be improved

### ISSUE THREAD

**Issue by selenachenjingxin** [4paradigm/OpenMLDB#2911]
**Bug Description**

demo in c++ doc needs to be improved

**Expected Behavior**

**Relation Case**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by vagetablechicken** [comment]
demo connect cluster, not standalone

**Comment by vagetablechicken** [comment]
c++ doc has already fixed
