### ISSUE TITLE
missing `disk table` configs in the english version of `conf.md`

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#2918]
**Bug Description**
The following example configs should also be added to the `docs/en/deploy/conf.md`
```
#
# HDD表数据文件路径（可选，默认为空）
# 配置数据目录，多个磁盘使用英文符号, 隔开
--hdd_root_path=./db_hdd
# 配置数据回收站目录，drop表的数据就会放在这里
--recycle_bin_hdd_root_path=./recycle_hdd
#
# SSD表数据文件路径（可选，默认为空）
# 配置数据目录，多个磁盘使用英文符号, 隔开
--ssd_root_path=./db_ssd
# 配置数据回收站目录，drop表的数据就会放在这里
--recycle_bin_ssd_root_path=./recycle_ssd
```

**Expected Behavior**

**Relation Case**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by harishbit** [comment]
Should we add  above example config to under ``## The Configuration File for Tablet: conf/tablet.flags`` ?
