### ISSUE TITLE
_*_cate output different result

### ISSUE THREAD

**Issue by lqy222** [4paradigm/OpenMLDB#2931]
**Bug Description**
while partition setting = 2,
*_cate may get different answer

**Expected Behavior**
one true result

**Relation Case**
CREATE TABLE mt ( col_s0 string,col_s1 string,col_s2 string,col_s3 string,col_s4 string,col_s5 string,col_s6 string,col_s7 string,col_s8 string,col_s9 string,col_s10 string,col_s11 string,col_s12 string,col_s13 string,col_s14 string,col_d0 double,col_d1 double,col_d2 double,col_d3 double,col_d4 double,col_t0 timestamp,col_t1 timestamp,col_t2 timestamp,col_t3 timestamp,col_t4 timestamp,col_i0 bigint,col_i1 bigint,col_i2 bigint,col_i3 bigint,col_i4 bigint,index(key = col_s0, ttl=0m, ttl_type=absolute, ts = col_t0),index(key = col_s1, ttl=0m, ttl_type=absolute, ts = col_t0),) OPTIONS (REPLICANUM = 1,PARTITIONNUM=2);

insert into mt values('4','val1','val1','val1','val1','val1','val1','val1','val1','val1','val1','val1','val1','val1000000','val1000000',1.500000,1.400000,1.400000,1.400000,1.400000,1667130000000,1652321552000,1652321552000,1652321552000,1652321552000,25,26,27,28,29);
insert into mt values('3','val2','val1','val1','val1','val1','val1','val1','val1','val1','val1','val1','val1','val1000000','val1000000',1.500000,1.400000,1.400000,1.400000,1.400000,1667130000000,1652321552000,1652321552000,1652321552000,1652321552000,25,26,27,28,29);
insert into mt values('3','val2','val1','val1','val1','val1','val1','val1','val1','val1','val1','val1','val1','val1000000','val1000000',1.400000,1.400000,1.400000,1.400000,1.400000,1667130000000,1652321552000,1652321552000,1652321552000,1652321552000,25,26,27,28,29);
insert into mt values('3','val1','val1','val1','val1','val1','val1','val1','val1','val1','val1','val1','val1','val1000000','val1000000',1.400000,1.400000,1.400000,1.400000,1.400000,1667130000000,1652321552000,1652321552000,1652321552000,1652321552000,25,26,27,28,29);
insert into mt values('5','val2','val1','val1','val1','val1','val1','val1','val1','val1','val1','val1','val1','val1000000','val1000000',1.600000,1.400000,1.400000,1.400000,1.400000,1667130000000,1652321552000,1652321552000,1652321552000,1652321552000,25,26,27,28,29);
**Steps to Reproduce**

1. SELECT count_cate(col_d0,col_s1) from mt;
 ----------------------------
  count_cate(col_d0, col_s1)
 ----------------------------
  :1,val2:2,val2:2
 ----------------------------
 ----------------------------
  count_cate(col_d0, col_s1)
 ----------------------------
  val1:2,val2:3
 ----------------------------

2.  SELECT max_cate(col_d0,col_s1) from mt;
 -----------------------------
  max_cate(col_d0, col_s1)
 -----------------------------
  val1:1.500000,val2:1.600000
 -----------------------------
 -------------------------------------------
  max_cate(col_d0, col_s1)
 -------------------------------------------
  :1.500000,val2:1.500000,val2:1.600000
 -------------------------------------------

**Comment by zhanghaohit** [comment]
seems the data is released in the DistributeIterator
