### ISSUE TITLE
functions in `src/test/util.h` not inlined

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#2957]
bad practise for non-member function definition in header file not inlined

**Comment by lumianph** [comment]
can be a good first issue?

**Comment by aceforeverd** [comment]
> can be a good first issue?

No problem for current code base. So I'd prefer refactor codes `src/test`

- move impls to cpp files
- and write a `CMakeLists.txt` file for the directory 

Maybe call-for-contributors ?

**Comment by aceforeverd** [comment]
well, fails in my PR: https://github.com/4paradigm/OpenMLDB/actions/runs/3895093785/jobs/6649966391#step:7:1112
