### ISSUE TITLE
Some problems  in `showtablestatus` tool

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#2969]
`showtablestatus` command in ops-tool cannot  detect some errors now.
There are some things to do as below:
- need to check partition in tablet (`gettablestatus` cmd in tablet client)
- need to check leader/follower connection (`getfollowers` cmd in tablet client)

**Comment by vagetablechicken** [comment]
`showtablestatus` will call https://github.com/4paradigm/OpenMLDB/blob/52eb49728804a66977a5268ff9d94475a1c65a3c/src/sdk/sql_cluster_router.cc#L4093

`partition_statuse` is got from tablet server, so it's the logic of check partitions in tablet server.

The 2rd one: check leader/follower connection, ref cmd `getfollower`.
We get table info from ns, the field `table_partition` shows the distribution. Check every partition leader in tablet server, leader should give us the same followers.
https://github.com/4paradigm/OpenMLDB/blob/52eb49728804a66977a5268ff9d94475a1c65a3c/src/sdk/sql_cluster_router.cc#L4156-L4162
