### ISSUE TITLE
SQL query offline: Fail to setup row builder, maybe row buf is currupted

### ISSUE THREAD

**Issue by firewolffff** [4paradigm/OpenMLDB#2983]
**Bug Description**
test data:
select "A" as name , 98 as score, '01' as class ,1 as ts
union all 
select "B" as name , 96 as score, '01' as class  ,2 as ts
union all 
select "C" as name , 92 as score, '01' as class  ,3 as ts
union all 
select "D" as name , 91 as score, '01' as class  ,4 as ts
union all 
select "E" as name , 90 as score, '01' as class  ,5 as ts

sql:

```sql
select 
score,
class,
ts,
sum(case when score>(first_value(score) over w1) then 1 else 0 end) over w1 as cnt_f,
count(score) over w1 as cnt 
from t1 
window w1 as (PARTITION BY class ORDER BY ts desc ROWS_RANGE BETWEEN  3 PRECEDING AND CURRENT ROW);
```

**Expected Behavior**
![a7e267feeeb27962d90b61fe1903faf1](https://user-images.githubusercontent.com/46313753/213121202-ee69c6e2-3fbb-46f2-a7ff-356d666d203f.jpg)

**Relation Case**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by aceforeverd** [comment]
`desc` not supported

Error message from the debug build of openmldb
![image](https://user-images.githubusercontent.com/11715200/215260964-56510eaa-bd70-49c9-9b45-d5126c1c1ac4.png)

**Comment by firewolffff** [comment]
您好，邮件已收到，我会尽快回复。
