### ISSUE TITLE
improve setup_openmldb.sh and the release package names in the mirror site

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#2986]
the name of release packages in the download mirror site is informal https://openmldb.ai/download/v0.7.1/
![image](https://user-images.githubusercontent.com/3725932/213348313-5743b6a6-204e-4ffd-b91e-d3fdaac6ee9d.png)

we need to keep the original names from the GitHub release pages. Accordingly, the script of demo/setup_openmlkdb.sh needs to be changed.

**Comment by vagetablechicken** [comment]
First fix setup_openmldb.sh, skip_download should work fine.
And then fix mirror script, check docs and rename all tar in mirror site
