### ISSUE TITLE
The result of monitor is negative 

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#3001]
<img width="573" alt="WX20230130-193022@2x" src="https://user-images.githubusercontent.com/6183996/215467356-d26d8ebc-1133-4eaf-8d1a-98ca67754615.png">
<img width="904" alt="WX20230130-193454@2x" src="https://user-images.githubusercontent.com/6183996/215467397-5a03d838-80d9-4798-b4da-24399e585770.png">

**Comment by aceforeverd** [comment]
what the content of table `information_schema.deploy_response_time` ?

**Comment by dl239** [comment]
> what the content of table `information_schema.deploy_response_time` ?

<img width="1130" alt="WX20230131-094357@2x" src="https://user-images.githubusercontent.com/6183996/215638162-c539501a-adb1-4614-8c4b-f6788293800a.png">

**Comment by lumianph** [comment]
still negative for table memory consumption, and also need to check other components

**Comment by aceforeverd** [comment]
TODO: wait a new release of openmldb exporter

**Comment by aceforeverd** [comment]
https://github.com/4paradigm/OpenMLDB/pull/3003#discussion_r1186611818 
the fix in python is not correct, it may require a mocked unit test for component memory reaches 32G
