### ISSUE TITLE
`at(col1, x)` cause segmentation fault for `full table`

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#3010]
**Bug Description**

`select at(col1, 1) from t1;` will cause `segmentation fault`

**Expected Behavior**

**Relation Case**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by aceforeverd** [comment]
`at`, as navigation functions, is subset of window function. should not used in full table

**Comment by aceforeverd** [comment]
This can be a enhancement to category aggregate function function for window functions and others

**Comment by aceforeverd** [comment]
https://github.com/4paradigm/OpenMLDB/blob/2197046324b3806979a0e5b96aaf7207e8bb320e/hybridse/src/plan/planner.cc#L1178 
where `GetFrame()` returns null

**Comment by aceforeverd** [comment]
fixed in #3298. Now `at` is not supported in full table aggregation.
