### ISSUE TITLE
while creating index fail, result is SUCCESS

### ISSUE THREAD

**Issue by lqy222** [4paradigm/OpenMLDB#3040]
**Bug Description**
```
  #   inputs:
  #     -
  #       columns : ["c1 string","c2 int","c3 timestamp","c4 timestamp"]
  #       indexs: ["index1:c1:c4"]
  #       rows:
  #         - [aa,1,1590738990000,1590738989000]
```

**Expected Behavior**
 success: false

**Relation Case**
```
 CREATE INDEX index1 ON auto_HmmNapdm (c1) OPTIONS (ts=c4, ttl=100m, ttl_type=absolute);
# W0209   3676 sql_cluster_router.cc:2506] Status: [0] ns add index failed--ok
# SUCCEED: ns add index failed--ok
```
**Steps to Reproduce**

1.  CREATE INDEX index1 ON {0} (c1) OPTIONS (ts=c4, ttl=100m, ttl_type=absolute);
2. 
3. 
4.

**Comment by dl239** [comment]
it has not set status if execute failed since #2749 @vagetablechicken

**Comment by vagetablechicken** [comment]
It won't change base_status when AddIndex failed. Fix now.

https://github.com/4paradigm/OpenMLDB/blob/92363dbc46366642b33a172a7ae39edc6ede7dbc/src/sdk/sql_cluster_router.cc#L2503-L2507
