### ISSUE TITLE
After deployment, some inserts instatement will fail cause by new index

### ISSUE THREAD

**Issue by lqy222** [4paradigm/OpenMLDB#3073]
**Bug Description**

**Expected Behavior**

**Relation Case**

**Steps to Reproduce**

1. CREATE TABLE demo_table1(c1 string, c2 int, c3 bigint, c4 float, c5 double, c6 timestamp, c7 date);
2. insert into demo_table1(c1) values("mm"); -- success 
3. DEPLOY demo_deploy SELECT c1, c2, sum(c3) OVER w1 AS w1_c3_sum FROM demo_table1 WINDOW w1 AS (PARTITION BY demo_table1.c1 ORDER BY demo_table1.c6 ROWS BETWEEN 2 PRECEDING AND CURRENT ROW);
4.  insert into demo_table1(c1) values("mm"); fail  error message :  insert values 1 failed, failed rows peek: 0

**Comment by aceforeverd** [comment]
Have we supported deploy when table is not cleared @dl239

**Comment by aceforeverd** [comment]
still WIP #2603, this may not a bug

**Comment by dl239** [comment]
post the error/warning messages in the tablet log @lqy222

**Comment by dl239** [comment]
`c6` will add as `ts` column automatically after deploy the SQL.  currently, insert will return failed if the value of ts column is `null`. refer https://github.com/4paradigm/OpenMLDB/blob/v0.7.1/src/sdk/sql_insert_row.cc#L288
