### ISSUE TITLE
add error msg when GetJobResultSet failed

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#3078]
https://github.com/4paradigm/OpenMLDB/blob/4045757cdfd19dc8d01c1f6e9b7dd6511160ebbc/src/sdk/sql_cluster_router.cc#L4194-L4208

If query job status failed(e.g. job table is broken...), we can't know, GetJobResultSet just return an empty resultset.

**Comment by tobegit3hub** [comment]
The underlying status is ignored and return the empty result set. We should return the status as well and handle the status when calling this method.
