### ISSUE TITLE
show error when create table failed on tablet

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#3103]
Only a boolean status now. We should check the tablet log to know the error reason.

https://github.com/4paradigm/OpenMLDB/blob/242ad026f8bbd370dfc669896d493d85e29d7dbd/src/client/tablet_client.cc#L202-L209

https://github.com/4paradigm/OpenMLDB/blob/242ad026f8bbd370dfc669896d493d85e29d7dbd/src/client/tablet_client.cc#L218-L221

**Comment by dl239** [comment]
done in #3434
