### ISSUE TITLE
Can team provide a better demo experience without mixing jupyter notebook & terminal command ?

### ISSUE THREAD

**Issue by eusdenrogers** [4paradigm/OpenMLDB#311]
Look into taxi demo,  feel confused to switch between jupyter and terminal.   

Is Jupyter notebook really a required dependency for finishing the demo, and can team provide a better experience for users that haven't use Jupyter before?

**Comment by dl239** [comment]
we can use docker to run taxi demo. refer https://openmldb.ai/docs/en/main/use_case/lightgbm_demo.html
