### ISSUE TITLE
add more status badges to README

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#313]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

try add extra badges in our `README.md` & `README-zh.md`
- [x] java packages from maven central
- [x] python packages from pypi
- [x] coverage info from codecov
- [x] latest release
- [x] license
- [x] Gitee link

you can use https://shields.io/

**Describe alternatives you've considered**

**Additional context**

**Comment by ashish-patwal** [comment]
Hey @aceforeverd , i would like to work on this issue .

**Comment by aceforeverd** [comment]
> Hey @aceforeverd , i would like to work on this issue .

feel free to send a pr :)

**Comment by ashish-patwal** [comment]
Thanks ! I'll start working on it .

**Comment by ashish-patwal** [comment]
Hey @aceforeverd , some doubts here . I cannot seem to find the link to gitee even with grep . Can you tell me about the gitee link ? Also what data do you want to display with packages from maven and pypi ?

**Comment by aceforeverd** [comment]
> Hey @aceforeverd , some doubts here . I cannot seem to find the link to gitee even with grep . Can you tell me about the gitee link ? Also what data do you want to display with packages from maven and pypi ?

Gitee link: https://gitee.com/paradigm4/OpenMLDB, just a faster mirror for people in china
Normally, we publish a few packages to maven central & pypi,  I just pick the important one: 
- https://mvnrepository.com/artifact/com.4paradigm.openmldb/openmldb-batch
- https://mvnrepository.com/artifact/com.4paradigm.openmldb/openmldb-jdbc
- https://pypi.org/project/openmldb/
