### ISSUE TITLE
`CREATE TABLE LIKE HIVE` should return failed when database is not found

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#3149]
0.7.2
```
localhost:7527/> CREATE TABLE demo_db.t2 LIKE HIVE 'hive://db.t2';
W0317 03:36:49.967428  2767 sql_cluster_router.cc:1973] CREATE TABLE LIKE will run in offline job, please wait.
```
We don't use database here, and actually no database in cluster. But it send a hive job.

**Comment by dl239** [comment]
should check whether the database exists if there is database name in `CREATE TABLE  ... LIKE HIVE ...` statement
