### ISSUE TITLE
show sorted jobs

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#3173]
`openmldb_tool inspect offline ls` 可以获得排序后的jobs列表，不检查具体job，检查其中的failed job仍然用`openmldb_tool inspect offline`

`pip show openmldb-tool`获得`Location: <path>`，替换`<path>/diagnostic_tool/diagnose.py`为新版https://gist.github.com/vagetablechicken/f6f0a6a6ec0a4b18b0547dff21ad3618

- [ ] pr

**Comment by lumianph** [comment]
we should fix it from the root cause (c++ sql router), the default order is the "id"
