### ISSUE TITLE
Feature request: support for user-defined aggregate functions (UDAFs)

### ISSUE THREAD

**Issue by sumeetmehra-dev** [4paradigm/OpenMLDB#3191]
UDAFs are commonly used in SQL queries to perform complex calculations on groups of rows. Adding support for UDAFs to HybridSE would make it a more powerful and flexible tool for data processing and analysis. 
'feature request'

**Comment by aceforeverd** [comment]
@sumeet21428 There is a simple udaf framework for developers since 0.7.3. Check out https://openmldb.ai/docs/zh/main/tutorial/udf_develop_guide.html#id8. Let us know if you got any problem .

**Comment by lumianph** [comment]
btw, i will move this udf doc onto the section of OpenMLDB SQL, the current position is not good

**Comment by lumianph** [comment]
@sumeet21428 the doc has been moved to this updated url: https://openmldb.ai/docs/zh/main/openmldb_sql/udf_develop_guide.html
