### ISSUE TITLE
string like "1900-01-00" in func datediff,unix_timestamp will make tablet crash

### ISSUE THREAD

**Issue by lqy222** [4paradigm/OpenMLDB#3194]
**Bug Description**

datediff and unix_timestamp func that convert string to date extract "1900-01-00" fail 

**Expected Behavior**

**Relation Case**
    inputs:
      - columns: ["id int64", "c1 string", "c2 string", "c3 date", "c4 date", "c5 timestamp"]
        indexs: ["index1: id: c5"]
        rows:
          - [5, "1900-01-01", "1900-01-00", "9999-12-31", "1900-01-01", 1590738991300]
    sql: select id ,datediff(c1,c2) as svs,datediff(c1,c3) as svd,datediff(c3,c1) as dvs,datediff(c3,c4) as dvd from {0};

   inputs:
      - columns: ["id int64", "c1 string", "c2 timestamp"]
        indexs: ["index1: id: c2"]
        rows:
          - [1, 1900-01-00, 1590738991000] 
       sql: select id ,unix_timestamp(c1) as unix_timestamp from {0};

___
This is a example problem of #926, null value returned by e.g `timestamp(-1)` become `UndefValue` for `timestamp_to_date`

**Comment by aceforeverd** [comment]
@lqy222 what's the executing environment ? online or offline. Provide the core dump trace info ?

**Comment by lqy222** [comment]
It's online env.
cli log
select c0,datediff(c1,c2) as svs,datediff(c1,c3) as svd,datediff(c3,c1) as dvs,datediff(c3,c4) as dvd from t2;

W0406 01:33:21.178077 23237 rpc_client.h:122] request error. [E1014]Got EOF of Socket{id=2 fd=13 addr=10.100.121.245:30003:47162} (0x0x671e400) [R1][E112]Not connected to 10.100.121.245:30003 yet, server_id=2 [R2][E112]Not connected to 10.100.121.245:30003 yet, server_id=2 [R3][E112]Not connected to 10.100.121.245:30003 yet, server_id=2
W0406 01:33:21.178284 23237 tablet_client.cc:94] send rpc request failed
W0406 01:33:21.178313 23237 sql_cluster_router.cc:1249] Status: [1500] Query rpc failed--[E1014]Got EOF of Socket{id=2 fd=13 addr=10.100.121.245:30003:47162} (0x0x671e400) [R1][E112]Not connected to 10.100.121.245:30003 yet, server_id=2 [R2][E112]Not connected to 10.100.121.245:30003 yet, server_id=2 [R3][E112]Not connected to 10.100.121.245:30003 yet, server_id=2--ReturnCode[0]--
Error: [1500] Query rpc failed--[E1014]Got EOF of Socket{id=2 fd=13 addr=10.100.121.245:30003:47162} (0x0x671e400) [R1][E112]Not connected to 10.100.121.245:30003 yet, server_id=2 [R2][E112]Not connected to 10.100.121.245:30003 yet, server_id=2 [R3][E112]Not connected to 10.100.121.245:30003 yet, server_id=2--ReturnCode[0]--

 journalctl error log
 localhost kernel: openmldb[14011]: segfault at 7fd50f865008 ip 00007fd5defe5841 sp 00007fd50f9697c0 error 4 in libgcc_s-4.8.5-20150702.so.1[7fd5defd5000+15000]

no tablet log recorded

**Comment by aceforeverd** [comment]
can't reproduce in sql engine. I'll add a feature enhance for string to timestamp/date conversion, it seems problematic for many edge cases.

**Comment by aceforeverd** [comment]
Failed cases:
- `select datediff(Date(timestamp(2177481600)), Date("2021-05-01"));`
- `select datediff(Date(timestamp(-1)), Date("2021-05-01"));`

Fixed:
- "1900-01-00" in datadiff, by #3499
