### ISSUE TITLE
diag: show tablet data distribution

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#3209]
ref https://gist.github.com/vagetablechicken/06522732096dd253e542f0f0139c5d9a

**Comment by vagetablechicken** [comment]
show offline job sorted in `offline inspect` is good before job info sorted fixed

**Comment by zhangziheng01233** [comment]
show all databases and tables?(include system databases and tables?)

**Comment by vagetablechicken** [comment]
> show all databases and tables?(include system databases and tables?)

system tables are small, won't effect too much. Just user tables.

**Comment by zhangziheng01233** [comment]
plot in terminal:
- thermograph: a python commend-line tool
- matplotlib_iterm2: in ipython
- termplotlib(need numpy): support hist, barh, plot
