### ISSUE TITLE
Not able to find out SQL syntax docs from readme. 

### ISSUE THREAD

**Issue by eusdenrogers** [4paradigm/OpenMLDB#321]
**Is your feature request related to a problem? Please describe.**
Try to build SQL script but struggled finding out SQL syntax docs. 

**Describe the solution you'd like**
A clear user guide with a link from readme would be helpful.

**Describe alternatives you've considered**

**Additional context**

**Comment by jingchen2222** [comment]
So sorry. Please check here https://docs.fedb.io/hybridse/user-manual/reference for SQL usage.
