### ISSUE TITLE
Does online batch mode support group by?

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#3222]
https://github.com/4paradigm/OpenMLDB/blob/2e2997223b6f1d4a6f7d7c89d07574c90ea9952b/docs/zh/openmldb_sql/dql/GROUP_BY_CLAUSE.md?plain=1#L21

**Comment by lumianph** [comment]
@aceforeverd to double confirm

**Comment by aceforeverd** [comment]
For group by in cluster, it is basically available, means that a simple `select count(val) as cnt from t1 group by ...` should work, but may not production ready.

**Comment by aceforeverd** [comment]
doc fixed by #3308, group by supported since  v0.6.4
