### ISSUE TITLE
build cxx binary/so for lower glibc version or other os

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#3302]
If released binary/so runs on lower glibc host, it'll get error:
```
libstdc++.so.6: version `GLIBCXX_3.4.19' not found
```

- [ ] it's better to fix the exception throw in LibraryLoader, so that we can see the better error msg.

We check the host system lib by script
```
#!/bin/bash
set -x
cat /etc/redhat-release
ldd --version
strings /lib64/libc.so.6 | grep ^GLIBC_
strings /usr/lib64/libstdc++.so.6 |grep ^GLIBC
```

For example, if we want run binary/so on glibc 2.12 and libstdc++.so.6.0.13(GLIBCXX_3.4.13), we can build it on a old centos image.

Build steps:
1. use old image, `ghcr.io/4paradigm/centos6_gcc7_hybridsql`
2. yum install -y bison bison-devel byacc cppunit-devel patchdevtoolset-8-gcc devtoolset-8-gcc-c++, install build tools.
3. create `/etc/os-release` for zetasql
4. rocksdb don't build sst_dump&ldb, or add -lrt
5. Download https://github.com/sub-mod/bazel-builds/releases for zetasql, build_zetasql_parser.sh直接关了bazel test? add -lrt
6. add func in script(centos6 coreutils doesn't have `realpath`)
```
realpath () { 
[[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}" 
}
```
Better to add a new Dockerfile? The repo is private and we should modify zetasql build scripts, so add a script for patch is better. If we want a new Dockerfile, thirdparty build scripts need update.

We can test the built files, e.g. `strings libsql_jsdk.so | grep ^GLIBC`

**Comment by aceforeverd** [comment]
OpenMLDB uses features in c++17, gcc should >= 8.3

**Comment by vagetablechicken** [comment]
> OpenMLDB uses features in c++17, gcc should >= 8.3

Yep, I forget to write it, added.
