### ISSUE TITLE
Deploy SQL with database name will throw error message

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#3304]
**Bug Description**

Now if we try to deploy the SQL which contain database name, it will print error message but it create the deployment successful.

<img width="1792" alt="Screenshot 2023-06-05 at 16 45 33" src="https://github.com/4paradigm/OpenMLDB/assets/2715000/10b205e2-5da3-4eda-bf79-ac89b3b98e51">

**Expected Behavior**

Do not print error message.

**Relation Case**

None.

**Steps to Reproduce**

1. CREATE DATABASE demo_db;
2. use demo_db;
3. CREATE TABLE demo_table1(c1 string, c2 int, c3 bigint, c4 float, c5 double, c6 timestamp, c7 date);
4. set @@SESSION.execute_mode='online';
5. DEPLOY demo_data_service SELECT c1, c2, sum(c3) OVER w1 AS w1_c3_sum FROM demo_db.demo_table1 WINDOW w1 AS (PARTITION BY demo_table1.c1 ORDER BY demo_table1.c6 ROWS BETWEEN 2 PRECEDING AND CURRENT ROW);

It will success if deploy without database.

**Comment by vagetablechicken** [comment]
- [x] support multi db in parse index
- [x] support multi db in genOutputSchema
