### ISSUE TITLE
deployment failed with func substr/dayofweek/day/hour

### ISSUE THREAD

**Issue by uttinie** [4paradigm/OpenMLDB#3309]
**Bug Description**
test with [https://openmldb.ai/docs/zh/main/tutorial/tutorial_sql_2.html](url)
```
deploy demo_test_0012 OPTIONS (SKIP_INDEX_CHECK="TRUE") select id, sum(f_purchase_time) OVER w1 as w1_f_purchase_time from (SELECT 
  -- 列直取
  id,
  t1.mid as mid,
  trans_time,
  substr(cardno, 1, 4),
  
  -- 副表特征
  t2.purchase_time as f_purchase_time, 
  t2.purchase_amt as f_purchase_amt, 
  t2.purchase_type as f_purchase_type
  
  FROM t1 LAST JOIN t2 ORDER BY t2.purchase_time ON t1.mid = t2.mid) 
  
  WINDOW w1 AS (PARTITION BY mid ORDER BY trans_time ROWS_RANGE BETWEEN 10s PRECEDING AND CURRENT ROW);
```

substr(cardno, 1, 4)  will cause the deployment to fail

**Expected Behavior**

**Relation Case**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by aceforeverd** [comment]
Substr cause the subquery as RowProject, which is not supported by window.

**Comment by aceforeverd** [comment]
You can simplify without subquery, like this https://github.com/4paradigm/OpenMLDB/blob/1b3e561c7c5c595e4d0426270ca9c1c356631cf5/cases/query/last_join_window_query.yaml#L60
