### ISSUE TITLE
Fail to validate SQL with db name and "SELECT 100"

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#3311]
The SQLs like "SELECT 100" will fail to validate.

![b58d4feeff1d98fb7a3531bc0a48a898](https://github.com/4paradigm/OpenMLDB/assets/2715000/4922e5de-39be-4c93-bdc6-14df52d9d37b)

The SQL without db name like "SELECT * from entities" may work but "SELECT * from SYSTEM_FEATURE_PLATFORM.entities" does not.

**Comment by vagetablechicken** [comment]
can reproduce by `explain select 100;` in sql_client

@aceforeverd can we run `select 100` in request mode? or we should fix planer check logic?

**Comment by aceforeverd** [comment]
#2759 not supported, yet
