### ISSUE TITLE
Enable UnsafeRowOpt by default and resolve the related issues

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#336]
Currently UnsafeRowOpt can not fit for all scenarios because of the bugs which may crash the task.

We should address and resolve the related issues to enable UnsafeRowOpt by default.

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fix UnsafeRowOpt issue](https://trello.com/c/ZdhBp9ba/18-fix-unsaferowopt-issue)

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [performance optimization for offline processing](https://trello.com/c/IkCOLr7m/8-performance-optimization-for-offline-processing)

**Comment by lumianph** [comment]
@tobegit3hub shall we close this?

**Comment by tobegit3hub** [comment]
Since it requires extra off-heap memory of Spark jobs, it may be enabled by users instead of by default.
