### ISSUE TITLE
Execute create index successfully but do not add index

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#3363]
**Bug Description**

Now we can create a table and execute `CREATE INDEX` to add index later. But it may fail while the command is successful.

<img width="1365" alt="75d5b4e4478ff7944af28e502e073c97" src="https://github.com/4paradigm/OpenMLDB/assets/2715000/8f5db11b-15fe-40f5-8d9d-051fd4a63387">

**Expected Behavior**

Describe table may display new index.

**Relation Case**

None.

**Steps to Reproduce**

```
CREATE DATABASE IF NOT EXISTS db1;

USE db1;

CREATE TABLE IF NOT EXISTS db1.request (usercode string, adid string, ts timestamp);

DESC request;

CREATE INDEX request_index2 ON db1.request (adid) OPTIONS (ts=ts, ttl_type=absolute, ttl=7d);

DESC request;
```

**Comment by vagetablechicken** [comment]
create index will create op so it's not finished when create sql returned, https://github.com/4paradigm/OpenMLDB/blob/eb148739ae975e8ac7646fb678acca9cad365132/src/nameserver/name_server_impl.cc#L8528

**Comment by tobegit3hub** [comment]
It has been resolve in 0.8.1.
