### ISSUE TITLE
Kafka-connecto-jdbc download url not update

### ISSUE THREAD

**Issue by lqy222** [4paradigm/OpenMLDB#3364]
**Bug Description**

[kafka-connect-jdbc.tgz](http://openmldb.ai/download/kafka-connector/kafka-connect-jdbc.tgz) 
The download url on https://openmldb.ai/docs/zh/main/integration/online_datasources/kafka_connector_demo.html directs to the old version rather than main version

**Expected Behavior**

**Comment by vagetablechicken** [comment]
after #3365 merged, I'll upload the new package

**Comment by vagetablechicken** [comment]
uploaded
