### ISSUE TITLE
Remove unused scripts

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#337]
remove the following files:
- steps/package_fedb_pysdk.sh
- steps/simple_compile.sh
- steps/fesql_auto_test.sh
- steps/simple_compile_mac.sh
- steps/settings.xml
- steps/integration_test_on_ramdir.sh
- steps/fesql_auto_gen_test_by_fedb.sh
- steps/fesql_auto_gen_test.sh

**Comment by aceforeverd** [comment]
also `cpplint.py`

**Comment by RhnSharma** [comment]
I would like to take this one.
