### ISSUE TITLE
Enable the unit test of TestWindowUnion 

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#339]
The unit test of TestWindowUnion is ignored because of https://github.com/4paradigm/OpenMLDB/issues/122 .

Once the bug has been fixed, we should enable this unit test to ensure the functionality.

It is a low-hanging fruit and we just need to uncomment the code in `TestWindowUnion.scala` to enable the unit test.

**Comment by ashish-patwal** [comment]
can i work on this ?

**Comment by tobegit3hub** [comment]
Any contribution is welcome and thanks for the pull-requests.
