### ISSUE TITLE
Replace `rtidb` to `openmldb` in some files

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#340]
* src/CMakeLists.txt
* docs/cn/deploy.md
* python/test/sql_smoke_test.py
* src/codec/codec_bench_test.cc

**Comment by PuneetDabral** [comment]
sir i am new at open source this is my first time to open source. so can i solve this issue.

**Comment by dl239** [comment]
> sir i am new at open source this is my first time to open source. so can i solve this issue.

thank you. Looking forward to your pr

**Comment by PuneetDabral** [comment]
i need your support in my first contribution ....can you plz give me any simple issue which i can resolve easily . so i can motivate my self

**Comment by dl239** [comment]
well, you can select any issue which you can solve after complete this.
