### ISSUE TITLE
openmldb-tool-test: fails eaily 

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#3406]
I run in latest main, fails easily, https://github.com/4paradigm/OpenMLDB/actions/runs/5691660219/job/15427258786

**Comment by vagetablechicken** [comment]
@lqy222 has checked about it, is it easy to fix?

**Comment by lqy222** [comment]
fixed in  https://github.com/4paradigm/OpenMLDB/pull/3283 , caused by wrong assert
