### ISSUE TITLE
can kafka write data with python?

### ISSUE THREAD

**Issue by EEControl** [4paradigm/OpenMLDB#3526]
Dear author:
I started kafka with openmldb refer to https://openmldb.ai/docs/zh/v0.6/use_case/kafka_connector_demo.html#kafka-topic and I can write data into openmldb.
then I tried kafka-python to write data and my code is below:
import json
from kafka import KafkaProducer
import random
SERVER = '127.0.0.1:9092'
TOPIC = 'topic1'
producer = KafkaProducer(bootstrap_servers=SERVER, value_serializer=lambda m: json.dumps(m).encode())
N = 100
for i in range(N):
    data = {"c1_int16":i+100,"c2_int32":2,"c3_int64":3,"c4_float":4.4,"c5_double":5.555,"c6_boolean":random.choice([True, False]),"c7_string":"c77777","c8_date":19109,"c9_timestamp":1651051906000}
    producer.send(TOPIC, data)
##########################################################################################
But I didn't got new data in openmldb, and the code didn't throw any errors.
What's wrong with the python code, forward to your relpay, thank you!
##########################################################################################
PS. my openmldb version is 0.6.8 with cluster on one machine

**Comment by vagetablechicken** [comment]
It's just writing to kafka, no matter what way. Check https://openmldb.ai/docs/zh/main/integration/online_datasources/kafka_connector_demo.html#id12, get logs. If you can't handle it, plz paste it in here.

**Comment by EEControl** [comment]
> It's just writing to kafka, no matter what way. Check https://openmldb.ai/docs/zh/main/integration/online_datasources/kafka_connector_demo.html#id12, get logs. If you can't handle it, plz paste it in here.

OK,I will check it, thank you very much!

**Comment by vagetablechicken** [comment]
I've seen you just send data e.g. `{"c1":1,"c2":2}`, no schema in message. Check https://openmldb.ai/docs/zh/main/integration/online_datasources/kafka_connector_demo.html#id10, if you use `org.apache.kafka.connect.json.JsonConverter` without extra config, you should send msg `schema`&`payload`, otherwise, you should set `auto.schema=true` in connector config.

**Comment by vagetablechicken** [comment]
solved
