### ISSUE TITLE
高潜用户购买意向预测demo咨询

### ISSUE THREAD

**Issue by EEControl** [4paradigm/OpenMLDB#3532]
作者您好：
      有个问题需要咨询下，一个个性化在线预测流程应该是某个在线用户有浏览行为之后，后台会抽取该用户的离线和在线特征，然后调模型预测并返回预测结果。因为每个在线用户的历史特征和实时特征都是不一样的，为了实现个性化推荐和预测，在openmldb里面该如何实现？另外该如何区分不同用户的行为和特征呢？我看高潜用户购买意向预测demo里也没有针对某个用户的预测，能详细说明下吗，非常感谢

**Comment by aceforeverd** [comment]
@vagetablechicken call for help

**Comment by vagetablechicken** [comment]
针对某个用户的预测在 https://openmldb.ai/docs/zh/main/use_case/JD_recommendation.html#id21 ，传入某用户的当前行为（一般数据内就会有用户ID），然后OpenMLDB计算实时特征，再特征+模型进行预测。
其他案例中的“预测”都是指这个。

区分不同的用户，这是表设计的问题。通常来讲，表有USER ID列，实时请求中有USER ID，然后SQL特征中都是partition by user id，或join on user id等筛选，就是在“只选择该用户的数据”。

你说的历史特征和实时特征的问题，从OpenMLDB的架构来讲，一般是有慢更新的表（比如，天级别、小时级别更新），它们可以存储历史特征，但其实它们也是在线表。通常是历史特征部分join实时特征部分，组合成完整特征。

如果你的场景更加特殊，可以再交流。

**Comment by EEControl** [comment]
好的收到，这里主要是担心多个用户并发请求时无法区分预测结果是属于哪个用户，这里我再测试下，非常感谢

**Comment by lumianph** [comment]
> 好的收到，这里主要是担心多个用户并发请求时无法区分预测结果是属于哪个用户，这里我再测试下，非常感谢

也欢迎加入我们的微信讨论群，可以进行实时讨论，https://github.com/4paradigm/OpenMLDB#11-community

如果需要，也可以单独加我 mian_lu ，感谢
