### ISSUE TITLE
how to modify the apiserver configuration to bind the pod ip 

### ISSUE THREAD

**Issue by ICESDHR** [4paradigm/OpenMLDB#3563]
I followed the tutorial to send an http request outside of the pod and get Connection refused.

I changed 2 files(apiserver.flags, apiserver.flags.template) from localhost to 0.0.0.0, but every time i run /work/init.sh, 0.0.0.0 in apiserver.flags will revert to localhost, then apiserver run on localhost:9080, not bind podIP, and I can't access it properly

My reference is as follows, plz help
https://openmldb.ai/docs/zh/v0.8/reference/ip_tips.html#id2
![image](https://github.com/4paradigm/OpenMLDB/assets/30169832/bfdcba2c-c6a2-4b94-80de-d0b04fc97872)
https://openmldb.ai/docs/zh/v0.8/deploy/conf.html#apiserver-conf-apiserver-flags
![image](https://github.com/4paradigm/OpenMLDB/assets/30169832/f7de0f08-5f38-4a43-89b3-c9528aec6dfb)

**Comment by vagetablechicken** [comment]
init.sh use `sbin/deploy.sh`, all ip are from `sbin/conf/hosts`, https://github.com/4paradigm/OpenMLDB/blob/main/release/conf/hosts

BTW, `init.sh` is a quickstart way, it's inflexible.
Deploy will do scp if the host is not localhost/127.0.0.1. If 0.0.0.0 deploy failed, you'd better to modify `conf/apiserver.flags` and call `bin/start.sh start apiserver`, see https://openmldb.ai/docs/zh/main/deploy/install_deploy.html#apiserver

**Comment by ICESDHR** [comment]
@vagetablechicken It worked. thx :)
