### ISSUE TITLE
bug: cicd build failed but report ok

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#357]
e.g. sql_router_test build is failed in main branch https://github.com/4paradigm/OpenMLDB/runs/3491805413

**Comment by aceforeverd** [comment]
the status is ok now.

**Comment by vagetablechicken** [comment]
![image](https://user-images.githubusercontent.com/24697960/131993703-f9707e58-cad5-4d9d-a67d-52a267d16774.png)

**Comment by aceforeverd** [comment]
TODO: https://github.com/4paradigm/OpenMLDB/pull/493/files#r724812660
