### ISSUE TITLE
Fail to run benchmark after compiling hybridsql:0.8.4

### ISSUE THREAD

**Issue by Cha465** [4paradigm/OpenMLDB#3679]
**Bug Description**

Thanks for the manuals and open-source code!  After I followed the manual  **Compile and Use in Docker Container** and got the executable, I still failed to run the benchmarks. It seems that the dependencies like zookeeper are not packed in the image (hybridsql:0.8.4).
Here is my output after running `/work/openmldb/bin/openmldb --zk_cluster=127.0.0.1:2181 --zk_root_path=/openmldb --role=sql_client --interactive=false`:
`W1214 11:53:12.484856 36462 zk_client.cc:141] fail to init zk handler with hosts 127.0.0.1:2181, session_timeout 2000
W1214 11:53:12.485138 36462 db_sdk.cc:216] fail to init zk client with zk options [cluster:127.0.0.1:2181, path:/openmldb, zk_session_timeout:2000, log_level:0, log_file:, zk_auth_schema:digest, zk_cert:]
ERROR: Failed to connect to db`
**Expected Behavior**
`/work/openmldb/bin/openmldb --zk_cluster=127.0.0.1:2181 --zk_root_path=/openmldb --role=sql_client --interactive=false` would enter cli

**Steps to Reproduce**

1. docker pull and run hybridsql:0.8.4
2. make && make install
3. copy directory openmldb to /work; configure zookeeper according to the manual (connection is ok)
4. `/work/openmldb/bin/openmldb --zk_cluster=127.0.0.1:2181 --zk_root_path=/openmldb --role=sql_client --interactive=false`

**Comment by aceforeverd** [comment]
you should follow https://openmldb.ai/docs/zh/main/deploy/install_deploy.html on how to setup openmldb cluster

**Comment by Cha465** [comment]
Thank you, so after I setup this cluster, how should I run benchmarks? I guess simply following README.md in benchmark/ will be ok?

**Comment by aceforeverd** [comment]
> Thank you, so after I setup this cluster, how should I run benchmarks? I guess simply following README.md in benchmark/ will be ok?

Yes. Let me know if you got any problem

**Comment by lumianph** [comment]
hi @Cha465 thank you for your interest, in order to have prompt reply from our developers, you can also join our slack: 
https://join.slack.com/t/openmldb/shared_invite/zt-ozu3llie-K~hn9Ss1GZcFW2~K_L5sMg

**Comment by lumianph** [comment]
> Thank you, so after I setup this cluster, how should I run benchmarks? I guess simply following README.md in benchmark/ will be ok?

the English doc version is this: https://openmldb.ai/docs/en/main/deploy/install_deploy.html

**Comment by Cha465** [comment]
One-click deployment works for me, and I can run the benchmark now. Thanks for answering!
