### ISSUE TITLE
Unrecognized VM option 'MaxPermSize=2048m' when executing scalatest-maven-plugin:1.0:test (test) @ openmldb-spark-connector

### ISSUE THREAD

**Issue by yangwucheng** [4paradigm/OpenMLDB#3755]
**Bug Description**
when run mvn install of openmldb,  scalatest-maven-plugin failed with message
```text
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ openmldb-spark-connector ---
Unrecognized VM option 'MaxPermSize=2048m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
Java Version: `jdk1.8.0_351.jdk`
mvn install cmd:
```bash
/Library/Java/JavaVirtualMachines/jdk1.8.0_351.jdk/Contents/Home/bin/java -Dmaven.multiModuleProjectDirectory=/DIR/OpenMLDB/java -Dmaven.home=/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3 -Dclassworlds.conf=/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/bin/m2.conf -Dmaven.ext.class.path=/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven-event-listener.jar -javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=59104:/Applications/IntelliJ IDEA CE.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds.license:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar org.codehaus.classworlds.Launcher -Didea.version=2022.1.4 -s /DIR/.m2.openmldb/settings.xml -Dmaven.repo.local=/DIR/.m2.openmldb/repository -DskipTests=true install -Dgpg.skip -DskipTests=true -Dwagon.skip=true -Dmaven.test.skip=true
```

**Expected Behavior**
mvn install success

**Relation Case**

**Steps to Reproduce**

1. edit mvn install of openmldb runtime config
```bash
install -Dgpg.skip -DskipTests=true -Dwagon.skip=true -Dmaven.test.skip=true -f pom.xml
```
2.  run mvn install of openmldb
3. failed when testing openmldb-spark-connector, error message
```log
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ openmldb-spark-connector ---
Unrecognized VM option 'MaxPermSize=2048m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by aceforeverd** [comment]
MaxPermSIze won't be issue with jdk8, maybe you should recheck the JDK version you are using

**Comment by vagetablechicken** [comment]
`/Library/Java/JavaVirtualMachines/jdk1.8.0_351.jdk/Contents/Home/bin/java`, it's 1.8, but not openjdk? e.g. `Java HotSpot(TM)`

**Comment by yangwucheng** [comment]
> `/Library/Java/JavaVirtualMachines/jdk1.8.0_351.jdk/Contents/Home/bin/java`, it's 1.8, but not openjdk? e.g. `Java HotSpot(TM)`

java version "1.8.0_351"
Java(TM) SE Runtime Environment (build 1.8.0_351-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.351-b10, mixed mode)

**Comment by vagetablechicken** [comment]
https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html#removed-java-options
```
-XX:MaxPermSize=size
Sets the maximum permanent generation space size (in bytes). This option was deprecated in JDK 8 and superseded by the -XX:MaxMetaspaceSize option.
```

Shall we use MaxMetaspaceSize for jdk >=1.8?

**Comment by vagetablechicken** [comment]
@yangwucheng has tested on his env, MaxMetaspaceSize works fine. So let's replace it.

And openmldb-batchjob `maven.compiler.source` is 1.7, other modules are all 1.8, it can be set to 1.8 too.
