### ISSUE TITLE
字段含义

### ISSUE THREAD

**Issue by zhangjun9302** [4paradigm/OpenMLDB#378]
![image](https://user-images.githubusercontent.com/87636437/132286435-0c8d51a0-c3db-4c66-9dc4-c36cca8f1730.png)

请问图中这结果字段代表什么含义呢？

**Comment by zhangjun9302** [comment]
请问showtable是否有对应的java sdk呢，如果通过java是否可以获取到这些信息呢？我在文档中没有找到相关信息，请问有较全的文档吗？

**Comment by dl239** [comment]
`recored_cnt` 第一个索引的数据条数
`memused` 内存占用
`diskused` 磁盘占用

java sdk中有个showTable的接口，返回TableInfo的结构，table_partition字段里有对应的值_

**Comment by zhangjun9302** [comment]
你好，这个rtidb不是内存数据库吗？请问这个磁盘存储的是什么数据呢？难道schema存储在磁盘上的吗？
