### ISSUE TITLE
invitation link to slack

### ISSUE THREAD

**Issue by ghost** [4paradigm/OpenMLDB#38]
Hi guys,

Hope you are all well !

I was wondering where to find the slack invitation link ? I have some questions about your project.

Cheers,
Luc Michalski

**Comment by aceforeverd** [comment]
slack link on README
https://hybridsql-ws.slack.com/archives/C01R7L7AL3W

**Comment by ghost** [comment]
does not work for me, it asks for a 4paradigm.com email address.

<img width="464" alt="Screenshot 2021-04-15 at 11 34 52" src="https://user-images.githubusercontent.com/1963546/114848037-9ac78680-9dde-11eb-9bcf-b08769ed2fd8.png">

**Comment by imotai** [comment]
@lucmichalski  Please try again .

**Comment by ghost** [comment]
this time I have no link to register

**Comment by imotai** [comment]
> this time I have no link to register

Sorry , I should add this link `https://join.slack.com/t/hybridsql-ws/shared_invite/zt-ozu3llie-K~hn9Ss1GZcFW2~K_L5sMg`  to our readme, You can try it
