### ISSUE TITLE
rtidb磁盘占用

### ISSUE THREAD

**Issue by zhangjun9302** [4paradigm/OpenMLDB#389]
![image](https://user-images.githubusercontent.com/87636437/132326588-51986e1f-f848-4212-87f2-80a735b43d26.png)
你好，请问
1.rtidb不是内存数据库吗？为什么会有磁盘占用呢？
2.rtidb是否有持久化呢？
3.rtidb的过期策略是怎样的呢？不是内存数据库吗？为什么linux系统重启了，数据还在呢？
![image](https://user-images.githubusercontent.com/87636437/132330999-3aba97c5-3b88-4f8e-b842-db0b4c90fde4.png)

**Comment by dl239** [comment]
是内存数据库，为了防止数据丢失会持久化数据到磁盘中。节点重启后可以从磁盘中恢复数据
过期策略有按时间过期和按条数过期以及这两种的混合
