### ISSUE TITLE
No need to build with java for python cicd process

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#3895]
**Bug Description**

Now cicd of openmldb-test-python will compile openmldb with java support which is wrong.

https://github.com/4paradigm/OpenMLDB/actions/runs/8826613502/job/24232581981?pr=3892

<img width="1649" alt="image" src="https://github.com/4paradigm/OpenMLDB/assets/2715000/900d63e8-93f9-4027-b5c2-b166c5e9d4a6">

**Comment by aceforeverd** [comment]
by design

**Comment by tobegit3hub** [comment]
This is used for deploy cluster with taskmanager. Close and won't fix.
