### ISSUE TITLE
feat:  api server support parameterized query

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#397]
**Is your feature request related to a problem? Please describe.**

Now that we have support parameterized query via java sdk (JDBC), python sdk. It would be nice if we work it out on api server.

**Describe the solution you'd like**

  - [ ] API desing
  - [ ] Implement 

**Describe alternatives you've considered**

**Additional context**

**Comment by dl239** [comment]
done in #2277
