### ISSUE TITLE
docker image not found in quick start

### ISSUE THREAD

**Issue by ideal** [4paradigm/OpenMLDB#3972]
**Bug Description**

In https://openmldb.ai/docs/zh/main/quickstart/openmldb_quickstart.html , running `docker run -it 4pdosc/openmldb:0.9.2 bash`, but actually the image `4pdosc/openmldb:0.9.2` does not exist.

```
Unable to find image '4pdosc/openmldb:0.9.2' locally
docker: Error response from daemon: manifest for 4pdosc/openmldb:0.9.2 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

**Expected Behavior**

The image `4pdosc/openmldb:0.9.2` exists.

**Relation Case**

None.

**Steps to Reproduce**

1. Running `docker run -it 4pdosc/openmldb:0.9.2 bash`

**Comment by zhanghaohit** [comment]
@ideal Hi. OpenMLDB is in the process of upgrading from 0.9.1 to 0.9.2. Now it is complete. Please try again. Sorry for the confusion.
