### ISSUE TITLE
import data from kafka to v0.9.2 opmendlb failed

### ISSUE THREAD

**Issue by wangdq** [4paradigm/OpenMLDB#3993]
**Bug Description**
import data from kafka to v0.9.2 openmldb failed
![bug](https://github.com/user-attachments/assets/2688092f-c863-42e2-b588-44ce64411c01)

**Comment by Shouren** [comment]
I checked the [doc](https://openmldb.ai/docs/zh/main/integration/online_datasources/kafka_connector_demo.html#id5) and found that the verison(v0.8.5) of `kafka-connect-jdbc` is compatible with OpenMLDB v0.9.2, however the latest version of `kafka-connect-jdbc` is v0.8.5 on  [openmldb.ai/download/kafka-connector/](url)

So the following actions should be taken:
- [x] Fix the doc
- [x] Upload a new verison of `kafka-connect-jdbc` to [openmldb.ai/download/kafka-connector/](url)
