### ISSUE TITLE
Package OpenMLDB Spark distribution for release

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#411]
OpenMLDB Spark distribution has some underlying optimization and becomes part of the OpenMLDB releases.

We should add CICD process to package OpenMLDB Spark distribution when OpenMLDB releases.

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [package customized Spark distribution for release](https://trello.com/c/xo9R68aX/20-package-customized-spark-distribution-for-release)

**Comment by aceforeverd** [comment]
- compile doc: https://github.com/4paradigm/OpenMLDB/blob/main/docs/en/compile.md
- problem may necessary to resolve: https://github.com/4paradigm/spark/tree/v3.0.0-openmldb

**Comment by tobegit3hub** [comment]
The compile issue has been resolved in https://github.com/4paradigm/spark/pull/4 .

**Comment by aceforeverd** [comment]
TODO: update OpenMLDB version from SNAPSHOT to release
