### ISSUE TITLE
SQL: support `LOAD DATA INFILE` Statement

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#443]
~~desc:  batch import data into OpenMLDB~~
~~format: import table  file_path~~
~~ex: `import demo_table1 file:///OpenMLDB/cli/examples/taxi_tour_parquet_all/raw_data.csv;`~~

Desc: support `LOAD DATA INFILE 'file_name'` SQL Statement like MySQL
E.g: `LOAD DATA INFILE 'hello.csv' INTO TABLE t1;`

**Comment by aceforeverd** [comment]
different with import statements e.g mysql's https://dev.mysql.com/doc/refman/8.0/en/import-table.html

**Comment by aceforeverd** [comment]
As discussed in #494 , this `import` feature should better write as `LOAD DATA INFILE`, since it do not import schema but just data. Also documented by MySQL:

> LOAD DATA is the complement of SELECT ... INTO OUTFILE. 

which is more  suitable with #455

**Comment by vagetablechicken** [comment]
`load data` supports `OPTIONS`, ref https://github.com/4paradigm/OpenMLDB/issues/455#issuecomment-942909834
Currently, we can support none, but should warn it.
