### ISSUE TITLE
Add  `DEPLOY` command

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#447]
`> DEPLOY demo_data_service select xxxxx;`

* package procedure
* create procedure
* parse index from sql
* add index

**Comment by jingchen2222** [comment]
Recomend using `DEPLOY demo_data_service SELECT xxxxx;`

**Comment by jingchen2222** [comment]
- [x] Zetasql support `DEPLOY demo_data_service SELECT xxxxx;`
- [x] Add CreateDeployment logical plan node.
- [ ] Support deploy cmd in cli and nameserver.

**Comment by aceforeverd** [comment]
should it be `create deployment` ? as it is correspond to `drop deployment` from #460.  Just like `create table` vs `drop table`

maybe `create deployment` and `deploy` stands for two things, and the `deploy` here just contains both of them ?
@dl239 @superzhaozheng
