### ISSUE TITLE
ci: pre-build macos pkg needs to select sdk

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#454]
Current macos-latest virtual env default xcode is Xcode 12.4, only support macOS 11.1 SDK(macosx11.1).
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#installed-sdks

So when we use the thirdparty pre-build pkg & hybridse pre-build pkg on mac(no 11.1 SDK) will cause:

![image](https://user-images.githubusercontent.com/24697960/134613314-6d63f00b-e277-4b7d-8f18-c47dc21739b2.png)

~~We should select xcode version to support macOS 10.15 SDK?
Can macOS 11.x support older SDK?~~

- [x] `No rule to make` error 
see https://github.com/4paradigm/OpenMLDB/issues/454#issuecomment-941909973

- [x] all thirdparty & hybridse built on sdk11.1, can 10.15 machine run the binary?
--Nope. brpc will gen endless warning logs see #954

**Comment by aceforeverd** [comment]
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs` has symlink
<img width="1063" alt="Screen Shot 2021-09-24 at 11 28 08 AM" src="https://user-images.githubusercontent.com/11715200/134613677-0f7cd524-c856-4458-bcb8-3a3f42f77916.png">

**Comment by aceforeverd** [comment]
build on macos11.x should fine, just with some warning: #242

**Comment by vagetablechicken** [comment]
> build on macos11.x should fine, just with some warning: #242

OK, I've checked the macos-11 virtual env https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#installed-sdks. SDK version is fine.

If the pre-build is built on sdk 11.1, building on sdk 11.x works fine. But building on sdk 10.x will get error.
So we may need to set an old sdk version when pre-building.

**Comment by vagetablechicken** [comment]
macOS-latest workflows will use macOS-11 soon. So we use macos-11 or stay 10.15? To build thirdparty on SDK 10.15.

**Comment by vagetablechicken** [comment]
I've test building hybridse on 10.15 thirdparty, got the error `No rule to make target.. /Application/.../CoreFoundation.framework` too.
Then I found it's the bug of absl lib. absl set the abs directory in its cmakeConfig.
The easiest way is to reset the property of absl.

**Comment by vagetablechicken** [comment]
#954 will do sdk select, close this issue
