### ISSUE TITLE
Support `SELECT INTO OUTFILE` syntax

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#455]
`SELECT xxx INTO OUTFILE '/xxx/t2.csv' OPTIONS ( delimit = ',' );`
`SELECT xxx INTO OUTFILE '/xxx/t2.csv';`

**Comment by jingchen2222** [comment]
@aceforeverd Does **zetasql** support syntax like that?
If not, we might need to work it out.

**Comment by aceforeverd** [comment]
> @aceforeverd Does **zetasql** support syntax like that?
> If not, we might need to work it out.

not supported yet

**Comment by tobegit3hub** [comment]
We should support options like these.

| Options      | Type            | Default       |
| ----------- | ----------- | ----------- |
| delimiter     | String         | ,                   |
| header        | Boolean      | true             |
| null_value   | String         | null              |
| format         | String         | csv              |
| mode          | String         | error_if_exists|
