### ISSUE TITLE
CreateDB API does not follow the syntax rules  leads that  use Database Command does not work

### ISSUE THREAD

**Issue by imotai** [4paradigm/OpenMLDB#46]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

## Expected Behavior
CreateDB("121314") return false

## Current Behavior
CreateDB("121314") return true
![image](https://user-images.githubusercontent.com/8623385/116028214-38497280-a689-11eb-963b-9022a938f95d.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by vagetablechicken** [comment]
SDK `createDB()` doesn't check the db string. But we can `use` this db, by using backquotes.
```
127.0.0.1:6527/> use `123456`;
Database changed
```
Actually, we can create db in cmd by using backquotes too.

```
127.0.0.1:6527/> create database `123456`;
Create database success
```
