### ISSUE TITLE
Add `SHOW DEPLOYMENT` and `DROP DEPLOYMENT` command

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#460]
`> SHOW DEPLOYMENT demo_data_service;`
`> SHOW DEPLOYMENTS;`
`> DROP DEPLOYMENT demo_data_service;`

drop index and procedure in `DROP DEPLOYMENT`

**Comment by aceforeverd** [comment]
> `> SHOW DEPLOYMENT demo_data_service;`

what's the meaning of `show deployment xxx`?
If that means the deployment status, is it necessary to add `show create deployment xxx`, which means deployment schema

> `> SHOW DEPLOYMENTS;`
> `> DROP DEPLOYMENT demo_data_service;`
> 
> drop index and procedure in `DROP DEPLOYMENT`
