### ISSUE TITLE
Update catalog in stand alone mode

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#461]

**Comment by vagetablechicken** [comment]
After #501 , StandAloneSDK is already able to get table infos from nameserver. But it can't get sp infos now.
Nameserver only has sp names, it won't store sp infos, tablet server has them.
So the solution is to make nameserver store sp infos, then sdk can get sp infos from nameserver.

**Comment by vagetablechicken** [comment]
- [x] We refresh catalog every 2s, it'll generate too may DEBUG logs. Need to improve.

Set refresh log to vlog(5)

**Comment by vagetablechicken** [comment]
nameserver standalone mode is not complete, needs #447 fix.
This issue only add `ShowProcedure` API, ns client and nameserverimpl need change.
