### ISSUE TITLE
Feat: Support explain for dataframe in openmldb-batch

### ISSUE THREAD

**Issue by zekai427** [4paradigm/OpenMLDB#488]
- We can't use 'explain' to get hybrids code generation plan now.
- For example: `val explain = openmldbSession.sql(sqlText).explain()` will get spark code plan instead of getting hybrids code generation plan.

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features of OpenMLDB Batch](https://trello.com/c/nm0e9SZN/27-features-of-openmldb-batch)

**Comment by tobegit3hub** [comment]
To keep the openmldb physical node and enable to print the node tree, we have to keep the c object in memory which may leaks memory. Here is the code we have to change to reserve the physical node object.

```
    @Override
     public synchronized void close() throws Exception {
        engine.delete();
        engine = null;

        compileInfo.delete();
        compileInfo = null;

        options.delete();
        options = null;

        // Notice that the physical node is reversed in output dataframe and do not delete here
        //plan.delete();
        //plan = null;

        // TODO: session object is required
        //session.delete();
        //session = null;

        catalog.delete();
        catalog = null;
    }
```

**Comment by tobegit3hub** [comment]
After consideration, we should not keep the openmldb physical node object. And just print the tree of offline planner nodes.

**Comment by tobegit3hub** [comment]
We should not implement new `explain()` with C++ physical node object and may support new debug sql API later.
