### ISSUE TITLE
ci: build improve

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#495]
We use `mkdir; cd && cmake && make &&` in many places. But a list of cmd, e.g. `cmake && make && cd`, if make(the internal cmd of list) got error,  `set -e` can't handle this error.

We should convert to multi-line script, without `&&`, `||`

_Originally posted by @aceforeverd in https://github.com/4paradigm/OpenMLDB/pull/493#discussion_r724812660_

But many places need convert, maybe we could write a good build script.

**Comment by aceforeverd** [comment]
gona resolve on #676
