### ISSUE TITLE
Support non-performance-sensitive in batch mode for standalone version

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#510]
Now `performance sensitive` is enable for in-memory batch mode since we hope users to create indexes before running.

But in standalone version, `non-performance-sensitive` should be supported so that we can run ad-hoc SQL without creating all the indexes in advance.

**Comment by tobegit3hub** [comment]
Now the config of `performance_sensitive_` is in `EngineOptions` which is initialized when tablet starting.

**Comment by jingchen2222** [comment]
> Now the config of `performance_sensitive_` is in `EngineOptions` which is initialized when tablet starting.

we have to deal with engine cache on `performance_sensitive_` mode and `non_perforamnce_sensitive_` mode.

**Comment by jingchen2222** [comment]
- [ ] deal with performance-sensitive settting when deal with `create procedure`  compile and cache @tobegit3hub

**Comment by tobegit3hub** [comment]
Resolve by https://github.com/4paradigm/OpenMLDB/pull/531 .
