### ISSUE TITLE
Bug: hybridse compile error

### ISSUE THREAD

**Issue by zoyopei** [4paradigm/OpenMLDB#513]
missing link library libboost_system

/usr/bin/ld: CMakeFiles/ast_node_converter_test.dir/planv2/ast_node_converter_test.cc.o: undefined reference to symbol '_ZN5boost6system16generic_categoryEv'

os: ubuntu18.04
gcc version: 8.4.0

**Comment by lumianph** [comment]
@jingchen2222 please follow up this issue

**Comment by aceforeverd** [comment]
I'll check this

**Comment by aceforeverd** [comment]
for ubuntu, the best solution is compile thirdparty from source. We'v recently add the third-party module, and is under active test.  You can do it simply by
```bash
cmake -S third-party -B .deps -DBUILD_BUNDLED=ON -DBUILD_ZOOKEEPER_PATCH=ON
cmake --build .deps 
```
We'll provide a ubuntu:20.04 pre-compiled archive for thirdparty

**Comment by aceforeverd** [comment]
> for ubuntu, the best solution is compile thirdparty from source. We'v recently add the third-party module, and is under active test. You can do it simply by
> 
> ```shell
> cmake -S third-party -B .deps -DBUILD_BUNDLED=ON -DBUILD_ZOOKEEPER_PATCH=ON
> cmake --build .deps 
> ```
> 
> We'll provide a ubuntu:20.04 pre-compiled archive for thirdparty

now there is pre-compiled thirdparty for ubuntu 20.04: https://github.com/4paradigm/hybridsql-asserts/releases/tag/v0.4.3,
if that not suit 18.04, compile thirdparty from source
