### ISSUE TITLE
bug: `GetNsClient` can't get the new client if ns changed

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#515]
`ns_client_` won't be deleted, so it can't be recreated when ns changed. Let's add a todo, fix it in the next time.

_Originally posted by @vagetablechicken in https://github.com/4paradigm/OpenMLDB/pull/501#discussion_r727736063_

**Comment by dl239** [comment]
- add watch to ns leader [node](https://github.com/4paradigm/OpenMLDB/blob/main/src/sdk/db_sdk.cc#L254)
- update [ns_client](https://github.com/4paradigm/OpenMLDB/blob/main/src/sdk/db_sdk.h#L120) if nameserver leader changed.

**Comment by dl239** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.5.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-05x)

**Comment by vagetablechicken** [comment]
taskmanager client can't refresh, so add a watch for it too.
