### ISSUE TITLE
Bug: ast_node_converter_test run failed

### ISSUE THREAD

**Issue by zoyopei** [4paradigm/OpenMLDB#516]
OpenMLDB/hybridse/src/planv2/ast_node_converter_test.cc:861: Failure
Expected equality of these values:
  s2.code
    Which is: 1002
  common::kOk
    Which is: 0
[  FAILED  ] ASTNodeConverterTest.ASTIntLiteralToNumberTest (0 ms)

**Comment by lumianph** [comment]
@jingchen2222 please follow up this issue
