### ISSUE TITLE
Openmldb-batchjob should generate Java docs for mvn deploy

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#540]
Currently we have this issue when deploying the java modules including `openmldb-batchjob`.

<img width="1142" alt="Screen Shot 2021-10-18 at 3 00 10 PM" src="https://user-images.githubusercontent.com/2715000/137683932-59f4717a-cad8-4630-9ace-67aba5d9d31c.png">

**Comment by vagetablechicken** [comment]
In https://github.com/4paradigm/OpenMLDB/actions/runs/1352974537, we want to set 0.2.4-SNAPSHOT to modules, and 0.2.4-macos-SNAPSHOT. But only the macos version set succeed.
So ci tried to deploy openmldb-batch-0.2.3, not the snapshot version.
![image](https://user-images.githubusercontent.com/24697960/137696022-edcc25fd-3ae2-48d0-b1a4-69fb52a2de7d.png)

and the correct macos version:
![image](https://user-images.githubusercontent.com/24697960/137696160-d2dac127-7724-43bd-81c6-2b5d4325da6d.png)

It's a bug too.

**Comment by tobegit3hub** [comment]
Thanks @vagetablechicken and I have created another issue to track this https://github.com/4paradigm/OpenMLDB/issues/552 .
