### ISSUE TITLE
Bug: zetasql lib isn't up-to-date after running init_env.sh

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#550]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

We found that users might fail to update their zetasql lib if they had installed third-party before even they had re-run init_env.sh script.
## Expected Behavior

Download libzetasql if is has been updated.
## Current Behavior

Skip update third-party if the third-party has been installed before.
## Steps to Reproduce

1.
2.
3.
4.

**Comment by jingchen2222** [comment]
TODO:

- [ ] add zetasql version check when CMake
- [ ] update zetasql lib if version < mini_version

maybe we can config libzetasql url in CMakeList.txt instead init_env.sh @aceforeverd

**Comment by aceforeverd** [comment]
> TODO:
> 
> * [ ]  add zetasql version check when CMake
> * [ ]  update zetasql lib if version < mini_version
> 
> maybe we can config libzetasql url in CMakeList.txt instead init_env.sh @aceforeverd

I'll check cmake's `ExternalProject`

**Comment by aceforeverd** [comment]
> TODO:
> 
> * [ ]  add zetasql version check when CMake
> * [ ]  update zetasql lib if version < mini_version
> 
> maybe we can config libzetasql url in CMakeList.txt instead init_env.sh @aceforeverd

I'll create a separate cmake module named 'third-party' which do the dependencies download and update.
For simpleness only manage zetasql first

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [building processing improvement](https://trello.com/c/VcpqXsbY/3-building-processing-improvement)
