### ISSUE TITLE
Deprecate string constructor in `StringRef` ？

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#560]
**Is your feature request related to a problem? Please describe.**

Problem: 
StringRef hold a pointer to `std::string` pass by constructor parameter, which may destroyed after. 

deprecate string constructor in `StringRef`, as it is easily wrongly used just like this bug. https://github.com/4paradigm/OpenMLDB/issues/516 

_Originally posted by @aceforeverd in https://github.com/4paradigm/OpenMLDB/issues/551#issuecomment-947381970_

https://github.com/4paradigm/OpenMLDB/issues/561

problem exam:
```cpp
std::string Foo() {
    return "content";
}

StringRef ref(Foo()); // string "content" will destroy after construction
ref.xxx(); // if xxx() access the pointer to string, cause problem
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aceforeverd** [comment]
well, reference zetasql's `IdString` and abseil/std's `string_view`
