### ISSUE TITLE
Feat: support column default value

### ISSUE THREAD

**Issue by zoyopei** [4paradigm/OpenMLDB#562]
**Is your feature request related to a problem? Please describe.**
We expect to support column default value when creating a table.

**Describe the solution you'd like**
```
create table t1 (
col1 int default 1 not null,
col2 bigint not null,
index(key=col1, ts=col2)
);

insert into t1(col2) values(100);
```

**Describe alternatives you've considered**

**Additional context**

**Comment by jingchen2222** [comment]
Thanks for your advice. We will work it out in the future.
```sql
create table t1 (
col1 int default 1 not null DEFAULT 0, 
col2 bigint not null,
index(key=col1, ts=col2)
);

insert into t1(col2) values(100);
```

**Comment by jingchen2222** [comment]
Todo:
- [x] 1. SQL syntax has been supported already.
- [x] 2. Support DefaultValue in SQLNode and LogicalPlan. @zoyopei  #563 
- [x] 3. Encode InsertRow with default value. @zoyopei   #563 
- [ ] 4. Column default value test @wuyou10206 . (after v0.3.0)

**Comment by jingchen2222** [comment]
@zoyopei Would you like to help us to support this feature? 
If you feel a little bit challenged with the Row Encode job, maybe you can start by supporting the default value in LogicalPlan.

Any questions are welcomed.

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [community pr/issue tracking](https://trello.com/c/S4D8P57j/17-community-pr-issue-tracking)
