### ISSUE TITLE
Set openmldb-batch version and deploy three versions when release

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#566]
Now openmldb-batch is merged into java parent modules and should be deploy for three version(linux, macos and allinone) when release.

**Comment by vagetablechicken** [comment]
The mac deploy in cicd will failed now. The problem is’openmldb-batch version set and pack’. If this issue fixed, that problem will be fixed too?

**Comment by lumianph** [comment]
we are not going to officially support different OS at this moment, I will close this issue.
