### ISSUE TITLE
ddl parser api is missing in java sdk

### ISSUE THREAD

**Issue by shawn-happy** [4paradigm/OpenMLDB#588]
create ddl parser api for java sdk.

**Comment by lumianph** [comment]
thanks for the suggestion, @dl239  will follow up this issue
BTW, can you please elaborate on your requirements and potential solutions about this issue? We are looking forward to your contribution.

**Comment by shawn-happy** [comment]
* **requirements**：
I wish I had provided sql statements, tables and schemas of each table that could return the statement that created the table。
* **solutions**：
1. create a virtual method called genDDL in sql_router.h, The method has two parameters: (string sql, map<string, vector<map<string, string>>> tableMap).

example:
the sql parameter is a query statements such as :
`SELECT
  a.itemId as itemId,
  b.brandName as name,
  b.brandId as brandId,
  c.actionValue as label
FROM a
  LAST JOIN c ON c.itemId = a.itemId
  LAST JOIN adinfo ON a.itemId = b.id;`

the tableMap parameter is Is used to indicate the mapping between tables and schemas of each table:
`
{
        "a":
        [
            {
                "name": "itemId",
                "type": "string"
            },
            {
                "name": "reqId",
                "type": "string"
            }
        ],
        "b":
        [
            {
                "name": "id",
                "type": "string"
            }
        ],
        "c":
        [
            {
                "name": "itemId",
                "type": "string"
            },
            {
                "name": "reqId",
                "type": "string"
            }
        ]
    }
`
2. create rpc method in nameserver. proto and define ddl parser request and response 
e.g:
`rpc ExecuteDDLParser(DDLParserRequest) returns (DDLParserResponse);`
`message DDLParserRequest{
    optional string sql = 3;
    optional string table = 3;
    repeated openmldb.common.ColumnDesc column_desc= 1;
}`

`message DDLParserResponse{
    optional int32 code = 2;
    optional string msg = 3;
    repeated string ddl = 1;
}
`
3. create virtual ExecuteDDLParser() in name_server_impl.h and Implement  ExecuteDDLParser method in name_server_impl.cc
` void ExecuteDDLParser(RpcController* controller, const DDLParserRequest* request, DDLParserResponse* response,
                          Closure* done);`
4. create a method in ns_client.cc for sql_router can access rpc method

@dl239 @vagetablechicken please review this solution to give me some advice

**Comment by vagetablechicken** [comment]
Maybe `ExtractIndexRequest` is better, or `DDLParseRequest`, not parser request.
We want to support tables, but request only has one table and its columns. You could try inner message, like:
```
message Request {
    message Table{
        optional table_name;
        repeated cols;
    }
   repeated Table tables;
}
```

**Comment by dl239** [comment]
Why add `ExecuteDDLParser` rpc interface to server? @shawn-happy

**Comment by shawn-happy** [comment]
i want to auto create table in server after genDDl statement @dl239
