### ISSUE TITLE
Support disk storage, such as SSD or HDD

### ISSUE THREAD

**Issue by njzyfr** [4paradigm/OpenMLDB#589]
In some case,  hardware resource is insufficient and not sensitive to performance. 
In limited resource application, if support ssd or hdd disk storage, it will be better.

**Comment by lumianph** [comment]
thank you for the suggestion, we will follow up this issue, please stay tuned for more details

**Comment by zhanghaohit** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [long time window - storage engine](https://trello.com/c/UxAMvWh5/5-long-time-window-storage-engine)
