### ISSUE TITLE
SQL client support querying and other APIs without setting database

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#591]
Now we have support multiple databases and can use SQL without setting database in advance. But `use $db` is required for command-line SQL client. We should remove this restriction by passing default database name.

**Comment by jingchen2222** [comment]
@tobegit3hub 
I recommend supporting querying without setting defautl-database in v0.3.0
And support other possible operations in the next version. (e.g, insert, create table, drop, desc ...)
