### ISSUE TITLE
Speed up downloads of third-party dependencies

### ISSUE THREAD

**Issue by shawn-happy** [4paradigm/OpenMLDB#601]
Speed up downloads of third-party dependencies in china.
Add a Chinese source mirror。

**Comment by lumianph** [comment]
thanks for the suggestion and pr, @zhanghaohit will follow up

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [building processing improvement](https://trello.com/c/VcpqXsbY/3-building-processing-improvement)

**Comment by vagetablechicken** [comment]
#3769
