### ISSUE TITLE
bug: SqlClusterRouter cache table name, but do not check table id

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#604]
https://github.com/4paradigm/OpenMLDB/blob/ca8ce048423984347783580baf81a9a8188c8502/src/sdk/sql_cluster_router.cc#L1077-L1094
The cache logic is: if we use the same sql, get the same cache, and use `cache->name()` to  find tablet.
But if we cache the sql of table t1(tid=1), then recreate table t1(tid=2), use the same sql, we will get the cache of t1(tid=1), it's not ok.

**Comment by vagetablechicken** [comment]
We can add check in `GetCache()`, if the cached table info is not equal to table info from dbsdk, return null.
We should add the new `SQLCache`, but boost::lru_cache::insert can't do anything if key exists.
boost::lru_cache is simple, so we can do some small changes. e.g. A new method lru_cache::upsert, if key exists, we will update it's value and it should be the most recenlty used item.

So we will get:
1. GetCache(key): if cache is valid, return. If not, leave the invalid sql cache(it'll be update later), return null as if no cache.
2. BuildCache of key...
3. SetCache(key, new_cache): we'll update the cache of the key here(by lru_cache::upsert).

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [minor bugfix tracking](https://trello.com/c/wEQ9HW0k/25-minor-bugfix-tracking)
