### ISSUE TITLE
move third-party libraries building project repository to 4paradigm/xxxxxx

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#617]
**Is your feature request related to a problem? Please describe.**

1. Our third-party libraries packing project is owned by https://github.com/jingchen2222/hybridsql-asserts. We had better move the project to https://github.com/4paradigm/hybridsql-asserts if we have one.
2. OpenMLDB parser is based on zetasql(https://github.com/jingchen2222/zetasql). Should be moved to  https://github.com/4paradigm/zetasql as well.
 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aceforeverd** [comment]
resolved in 0.4.0
