### ISSUE TITLE
build: support build and test on popular linux distributions (e.g ubuntu)

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#619]
**Is your feature request related to a problem? Please describe.**

currently support build from hybridsql docker image only, which is centos7
build from ubuntu fail #514 

**Describe the solution you'd like**

necessary to support build thirdparty from source first: #618  

**Describe alternatives you've considered**

**Additional context**

**Comment by zhanghaohit** [comment]
The issue will be solved in #618 

An Ubuntu pre-compiled third-party will be also available to speedup the build process.

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [building processing improvement](https://trello.com/c/VcpqXsbY/3-building-processing-improvement)

**Comment by aceforeverd** [comment]
https://github.com/4paradigm/hybridsql-asserts/pull/17
added pre-compiled binary for 
- macOS
- ubuntu 20.04
- centos7

**Comment by aceforeverd** [comment]
now pre-compiled thirdparty and zetasql is available, no workflow yet.
for resource reason, I'd prefer not add a ubuntu job @zhanghaohit

**Comment by zhanghaohit** [comment]
> now pre-compiled thirdparty and zetasql is available, no workflow yet. for resource reason, I'd prefer not add a ubuntu job @zhanghaohit

Can we add the job for release only?

**Comment by aceforeverd** [comment]
> > now pre-compiled thirdparty and zetasql is available, no workflow yet. for resource reason, I'd prefer not add a ubuntu job @zhanghaohit
> 
> Can we add the job for release only?

I think release job is not useful, the centos compiled binary should runnable in ubuntu as well. The ubuntu job is useful during compile and test

**Comment by zhanghaohit** [comment]
> > > now pre-compiled thirdparty and zetasql is available, no workflow yet. for resource reason, I'd prefer not add a ubuntu job @zhanghaohit
> > 
> > 
> > Can we add the job for release only?
> 
> I think release job is not useful, the centos compiled binary should runnable in ubuntu as well. The ubuntu job is useful during compile and test

Oh. What I means is that we should make sure that we can compile and test on ubuntu after at least every big change (i.e., release). Not necessary to release the ubuntu binary.

**Comment by aceforeverd** [comment]
better run tests locally on ubuntu image, closing
