### ISSUE TITLE
add standalone mode in java sdk

### ISSUE THREAD

**Issue by shawn-happy** [4paradigm/OpenMLDB#620]
requirement：
openmldb server has standalone cluster, but this standalone mode is missing in java sdk. 
maybe provide standalone mode in client  is better

**Comment by dl239** [comment]
standalone mode may not use in production environment. We will evaluate this requirement later. thank you

**Comment by dl239** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SDK support for standalone version](https://trello.com/c/IG6NK8bt/19-sdk-support-for-standalone-version)
