### ISSUE TITLE
Deny create table with distribution options for standalone DB

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#621]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

Now, we have the standalone DB. 
It might be inappropriate if we support creating a table with distribution and replica configuration.
We have to give a warning or just deny creating a table when users configure cluster options.
## Expected Behavior

```cmd
create table {auto} (
      c1 string, c3 int, c4 bigint, c5 float, c6 double, c7 timestamp, c8 date,
      index(key=(c3), ts=c4))
      options (
      replicanum = 3,
      partitionnum = 8,
      distribution = [ ('{tb_endpoint_0}', ['{tb_endpoint_1}'])]
      )
```

ERROR: Fail to create a table with the distribution configuration in standalone DB
## Steps to Reproduce

1.
2.
3.
4.

**Comment by jingchen2222** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix tracking](https://trello.com/c/wEQ9HW0k/25-bugfix-tracking)

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-denglong](https://trello.com/c/sdJl9Vdl/2-bugfix-denglong)
