### ISSUE TITLE
build(cmake): add hybridse to root CMakeLists.txt

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#625]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

as simple as `add_subdirectory(hybridse)`

**Describe alternatives you've considered**

**Additional context**

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [building processing improvement](https://trello.com/c/VcpqXsbY/3-building-processing-improvement)

**Comment by aceforeverd** [comment]
can resolve #636 in the meantime
