### ISSUE TITLE
ci: openmldb-batch deploy failed on macos version

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#627]
https://github.com/4paradigm/OpenMLDB/runs/4075637707?check_suite_focus=true
![image](https://user-images.githubusercontent.com/24697960/139812857-985fe9e2-d2e9-44ee-b477-7c4c1935330a.png)

It seems like, set openmldb-batch version to xxx-macos-xx failed.

**Comment by aceforeverd** [comment]
hybridse-native:0.2.4-SNAPSHOT exists.

high rate to fail, have a chance to win.

**Comment by aceforeverd** [comment]
will resolve in #673

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [github workflow reorganization](https://trello.com/c/upawl5mF/8-github-workflow-reorganization)
