### ISSUE TITLE
Delete GLOG message in sql_cluster_router

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#656]
Log message display on CLI directly is not well. 
![2e2b4fe7d6efcab8a768ba3244fee369](https://user-images.githubusercontent.com/6183996/140457660-28ef8354-6e23-4a10-a5a3-810ffce30c78.png)

**Comment by dl239** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [api & code cleanup](https://trello.com/c/YK7NZ65f/13-api-code-cleanup)

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [删除CLI内不必要的输出信息](https://trello.com/c/03WaBLjf/23-%E5%88%A0%E9%99%A4cli%E5%86%85%E4%B8%8D%E5%BF%85%E8%A6%81%E7%9A%84%E8%BE%93%E5%87%BA%E4%BF%A1%E6%81%AF)

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.5.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-05x)

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority Bugs (0.6.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-06x)

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug List (0.7)](https://trello.com/c/JVdN9kkX/161-bug-list-07)
