### ISSUE TITLE
Support quote in FileOptionsParser options

### ISSUE THREAD

**Issue by zekai427** [4paradigm/OpenMLDB#661]
Mysql and spark can distinguish "" and the separator can be part of the value. We can support this feature for correctly reading some input data such as "aa", "bb".
![image](https://user-images.githubusercontent.com/26684958/140855550-6b4c598d-da7c-4b9f-bc6c-405d2e458a32.png)

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [minor bugfix tracking](https://trello.com/c/wEQ9HW0k/25-minor-bugfix-tracking)
