### ISSUE TITLE
hybridsql docker: download thirdsrc can be removed

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#663]
**Is your feature request related to a problem? Please describe.**

thirdsrc download: https://github.com/4paradigm/OpenMLDB/blob/main/hybridse/docker/Dockerfile#L30 can be removed, we'll download thirdsrc during building

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [文档整理](https://trello.com/c/EW0F7yOb/1-%E6%96%87%E6%A1%A3%E6%95%B4%E7%90%86)

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [compilation improvement](https://trello.com/c/VcpqXsbY/3-compilation-improvement)

**Comment by aceforeverd** [comment]
won't do.
thirdparty will added to docker image by default: #670
