### ISSUE TITLE
Update  version in `CMakeFile` and `setup.py` when auto release package

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#665]
The version displayed when execute `./bin/openmldb --version` is not correct. 
We should update  version in `CMakeFile` and `setup.py` when auto release package

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [github workflow reorganization](https://trello.com/c/upawl5mF/8-github-workflow-reorganization)
