### ISSUE TITLE
Support execute in sql router

### ISSUE THREAD

**Issue by zekai427** [4paradigm/OpenMLDB#666]
- Now, we don't have execute function in sql router. And it will make some problems：
-   1. We can't use execute("Use db") in JDBC. So we can't change database in JDBC when we need.
-   2. We can't use execute("Set performance_sensitive = true"), execute("Select .. into ..") which only define in sql_cmd.h for the same reason.
- In order to solve this problem, we probably need to do these:
-   1. Move `HandleSQL` function which in sql_cmd.h to sql_cluster_router.h and rename to `execute`.
-   2. Move others functions to sql_cluster_router.h
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/26684958/141064734-b80ffc87-a596-4c65-83b5-613bee09b5b5.png">

-   3. Redefine `db` in sql_cluster_router.h(`struct SqlRouterOptions`) instead of sql_cmd.h and refactor functions which use db.
-   4. Redefine `performance_sensitive` in sql_cluster_router.h(struct SqlRouterOptions) too.

**Comment by Kanekanekane** [comment]
Linked: https://github.com/4paradigm/OpenMLDB/issues/605

**Comment by Kanekanekane** [comment]
#605

**Comment by tobegit3hub** [comment]
We could add the `execute(String sql)` function firstly and do not refactor all the related class at the same time.

**Comment by zekai427** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JDBC APIs standardisation](https://trello.com/c/BSUCBFig/14-jdbc-apis-standardisation)

**Comment by lumianph** [comment]
is this done? @tobegit3hub @dl239

**Comment by lumianph** [comment]
shall we link the PR and close it?

**Comment by vagetablechicken** [comment]
closed by #1231
