### ISSUE TITLE
move thirdparty repos to 4paradigm

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#669]
Move the following two repos to /4paradigm

https://github.com/jingchen2222/hybridsql-asserts
https://github.com/jingchen2222/zetasql

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [building processing improvement](https://trello.com/c/VcpqXsbY/3-building-processing-improvement)

**Comment by aceforeverd** [comment]
that two repos are in @jingchen2222 's space

**Comment by aceforeverd** [comment]
resolved
