### ISSUE TITLE
openmldb docker tag should match the openmldb release version

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#672]
Currently docker build will always download v0.2.0 of openmldb and spark.

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [demo image improvement](https://trello.com/c/kMDLwDLx/2-demo-image-improvement)

**Comment by dl239** [comment]
`ghcr.io/4paradigm/openmldb:0.3.0` and `ghcr.io/4paradigm/openmldb:0.3.2` have been released again
