### ISSUE TITLE
fix: OpenMLDB-batch java module not integrated well with it's parent module

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#673]
`revision` value not defined, cause `mvn deploy` job fail

https://github.com/4paradigm/OpenMLDB/blob/92395d76bbdb9e33f63d82fbc3844354f9466b24/java/openmldb-batch/pom.xml#L16

**Comment by tobegit3hub** [comment]
This is defined in profile which has default value. Refer to https://github.com/4paradigm/OpenMLDB/blob/92395d76bbdb9e33f63d82fbc3844354f9466b24/java/openmldb-batch/pom.xml#L53 .

**Comment by aceforeverd** [comment]
> This is defined in profile which has default value. Refer to
> 
> https://github.com/4paradigm/OpenMLDB/blob/92395d76bbdb9e33f63d82fbc3844354f9466b24/java/openmldb-batch/pom.xml#L53
> 
> .

Got it. But on GitHub workflow, we run `mvn deploy` over it's parent directory, and runs `mvn versions:set -DnewVersion=xxx` to tweak version in all submodule before deploy. Idealy, this module is not covered

Just remove this line

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [github workflow reorganization](https://trello.com/c/upawl5mF/8-github-workflow-reorganization)

**Comment by aceforeverd** [comment]
will resoved by #744 and #745
