### ISSUE TITLE
feat: move hybridse java module to OpenMLDB

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#674]
Modules in `java` e.g `opgenmldb-batch` depends on hybridse java module. Since both of the modules are in the same code base, it is necessary to merge hybridse java module into OpenMLDB.

**Comment by aceforeverd** [comment]
depends on #673

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [github workflow reorganization](https://trello.com/c/upawl5mF/8-github-workflow-reorganization)
