### ISSUE TITLE
ci(python): job for python sdk on macOS

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#675]
- [x] fix the building issue on mac: #272 
- [x] add mac support in `src/sdk/CMakeLists.txt`, different `plat-name`
- [x] add a workflow job for python SDK on mac, which is able to build, test, and publish.

**diss: how to publish the macos lib**

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [github workflow reorganization](https://trello.com/c/upawl5mF/8-github-workflow-reorganization)

**Comment by vagetablechicken** [comment]
> * [ ]  fix the building issue on mac: [Fail to build python sdk on MACOS #272](https://github.com/4paradigm/OpenMLDB/issues/272)
> * [ ]  add a workflow job for python SDK on mac, which is able to build, test, and publish.
> 
> **diss: how to publish the macos lib**

Issues #272 and https://github.com/4paradigm/OpenMLDB/issues/905 are fixed. We avoid strip on MacOS.

**Comment by aceforeverd** [comment]
v0.4.0 publish python sdk for linux only, with the plat-name `manylinux1_x86_64`

**Comment by HuilinWu2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve functionality of Python SDK](https://trello.com/c/xlXZPfTf/20-improve-functionality-of-python-sdk)

**Comment by aceforeverd** [comment]
feature has completed #1448
