### ISSUE TITLE
ci: refactor Github jobs, merge HybridSE and OpenMLDB workflow

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#676]
1. Merge the `hybridse-ci` workflow into `cicd` workflow. 
- `hybridse-ci`'s `test report` and `release` action can be removed.
- merge serval `prepare_release.sh` script
   hint: tweak cpp and python version should removed, instead, create a bump version commit directly before release

2. Better workflow style
- #495 

![openmldb-jobs drawio](https://user-images.githubusercontent.com/11715200/141264811-db61fb55-95eb-4c1b-82eb-c12a70218655.png)

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [github workflow reorganization](https://trello.com/c/upawl5mF/8-github-workflow-reorganization)
