### ISSUE TITLE
ci: include OpenMLDB cpp & java code in codecoverage report

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#677]
Currently, coverage only report over hybirdse's cpp and java module. It's necessary to also coverage OpenMLDB's code

The issue may depends on #625

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [github workflow reorganization](https://trello.com/c/upawl5mF/8-github-workflow-reorganization)

**Comment by aceforeverd** [comment]
resolved in #884
