### ISSUE TITLE
doc: add compatibility note and upgrade guide about compile image

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#678]
- For code starting from v0.2.3 (inclusive), it should fine to compile it on docker image `ghcr.io/4paradigm/hybridsql:0.3.0` or above
- how to compile v0.5.0 on image 0.4.0

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [github workflow reorganization](https://trello.com/c/upawl5mF/8-github-workflow-reorganization)

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [docs reorganize, review and udpate](https://trello.com/c/EW0F7yOb/1-docs-reorganize-review-and-udpate)

**Comment by aceforeverd** [comment]
resolved in #1615
