### ISSUE TITLE
missing getOutputSchema method

### ISSUE THREAD

**Issue by shawn-happy** [4paradigm/OpenMLDB#680]
java sdk provide com._4paradigm.openmldb.sdk.impl.SqlClusterExecutor#getInputSchema, why not provide getOutputSchema.
maybe i can call showProcedure this method to get output schema, but this must created procedure.
at the moment, maybe i haven't created procedure.
getInputSchema can get ExplainInfo.

**Comment by jingchen2222** [comment]
We can consider to provides getOutputSchema in `SqlClusterExecutor `.

**Comment by jingchen2222** [comment]
@shawn-happy 
SqlClusterExecutor is going to provide `getOutputSchema ` which can be used when all related input tables are created in the database.
#### For example:
- step 1: create table `t1` in database `demo_db`
```
> USE demo_db;
> CREATE TABLE t1 (col0 string, col1 int, col2 double, col3 timestamp, index(key=col0, ts=col3));
```

- step 2: get output schema via `getOutputSchema` or `expalin` interface
```java
// getOutputSchema after t1 has been created in demo_db
SqlClusterExecutor executor = ....
executor.getOutputScehma("demo_db", "select col0, col1, col2, col3, sum(col2) over w1 as w1_sum_col2 from t1 window as w1(partition by col0 order by col3 rows between 100 preceding and current row);")
// or maybe we can provide explain()
ExplainInfo explain = executor.explain("demo_db", "select col0, col1, col2, col3, sum(col2) over w1 as w1_sum_col2 from t1 window as w1(partition by col0 order by col3 rows between 100 preceding and current row");
explain.getInputSchema();
explain.getOutputSchema();
```

@shawn-happy if you need to get `output_schema` without creating tables in the database, we are working on #689 to achieve the purpose.

**Comment by dl239** [comment]
#689  closed
