### ISSUE TITLE
Support obtain output schema from `ExecuteDDLParse`

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#689]
**Is your feature request related to a problem? Please describe.**

Users may need to get `output_schema` before they create tables in the database.

Now,  `ExecuteDDLParse` can analyze SQL and generate DDL script with given input tables' `schemas`. 
However,  since `ExecuteDDLParse` only returns the DDL script, users will be frustrated when they need more details like the output schema.

In this issue, we are going to extend the abilities of `ExecuteDDLParse` to enable get more pieces of information (e.g., ddl script, output schema, input schema) without having input tables in databases.

**Describe the solution you'd like**

- `ExecuteDDLParse` return `DDLParseInfo` instead of `string`. `DDLParseInfo` can consist of `ddl_script`, `output_schema`, etc
- extend `genDDL` in java SDK 

**Describe alternatives you've considered**

**Additional context**

**Comment by vagetablechicken** [comment]
`ExecuteDDLParse` is not a good method(it must create client, so it must connect the openmldb server), and `DDLParseInfo`(contains ddl strings and output schema) is not easy for follow-up development(it'll make dev to modify swig file).

 It seems that it's not a big cost to use two methods separately(genDDL for index, genOutputSchema output schema). We could improve it when it was necessary.

So for simplicity, we'll add getOutputSchema in DDLPaser, then wrap the two method to GenDDL/GenOutputSchema(to hide the ddl_parser). 
Then in java sdk, we create two static methods(the same name) to call swig methods and do some convert jobs.

**Comment by jingchen2222** [comment]
> `ExecuteDDLParse` is not a good method(it must create client, so it must connect the openmldb server), and `DDLParseInfo`(contains ddl strings and output schema) is not easy for follow-up development(it'll make dev to modify swig file).
> 
> It seems that it's not a big cost to use two methods separately(genDDL for index, genOutputSchema output schema). We could improve it when it was necessary.
> 
> So for simplicity, we'll add getOutputSchema in DDLPaser, then wrap the two method to GenDDL/GenOutputSchema(to hide the ddl_parser). Then in java sdk, we create two static methods(the same name) to call swig methods and do some convert jobs.

Nice.
