### ISSUE TITLE
After adding a new index to the stand-alone version, the query result is incorrect

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#708]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

After adding a new index to the stand-alone version, the query result is incorrect

## Expected Behavior
[4,"aa", 1, 1590738990000]

## Current Behavior
Empty set

## Steps to Reproduce
1.  create
create table auto_hXeZOqOS(
id int,
c1 string,
c2 int,
c3 timestamp,
c4 timestamp,
index(key=(c1),ts=c4))options(partitionnum=1,replicanum=1);
2. insert
insert into auto_hXeZOqOS values
(1,'aa',1,1590738990000,1637056523316);
insert into auto_hXeZOqOS values
(2,'aa',1,1590738990000,1637056523316);
insert into auto_hXeZOqOS values
(3,'aa',3,1590738990000,1637057123257);
insert into auto_hXeZOqOS values
(4,'aa',1,1590738990000,1637057123317);
3. create index
CREATE INDEX index1 ON auto_hXeZOqOS (c2) OPTIONS (ts=c4, ttl=10m, ttl_type=absolute);
4. select
select id,c1,c2,c3 from auto_hXeZOqOS where c2 = 1;

## Possible Implementation
![wecom-temp-1916aa5d250509ac8295a67509b71f73](https://user-images.githubusercontent.com/18275570/141966061-b406f73a-cb99-4ac4-8460-9c33c53ae020.png)

**Comment by dl239** [comment]
Should call `ExtractMultiIndexData` after addIndex in standalone mode
