### ISSUE TITLE
Generate physical plan of "LOAD DATA" and " SELECT INTO" in SQL parser

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#725]
This is required for TaskManager to support importing and exporting data in cluster mode.

- [x] load data
- [ ] select into

**Comment by vagetablechicken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [data import for offline and online in the task manager](https://trello.com/c/OqReyYcD/23-data-import-for-offline-and-online-in-the-task-manager)

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implementation of TaskManager](https://trello.com/c/EkxZMO7i/28-implementation-of-taskmanager)
