### ISSUE TITLE
Support physical plan of "LOAD DATA" in Spark planner

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#726]
Support importing data with Spark in cluster mode.

**Comment by vagetablechicken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [data import for offline and online in the task manager](https://trello.com/c/OqReyYcD/23-data-import-for-offline-and-online-in-the-task-manager)

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implementation of TaskManager](https://trello.com/c/EkxZMO7i/28-implementation-of-taskmanager)
