### ISSUE TITLE
Support symbol-import without copying data

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#727]
Just like symbol-link to import data without copying.

**Comment by vagetablechicken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [data import for offline and online in the task manager](https://trello.com/c/OqReyYcD/23-data-import-for-offline-and-online-in-the-task-manager)

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implementation of TaskManager](https://trello.com/c/EkxZMO7i/28-implementation-of-taskmanager)
