### ISSUE TITLE
Support Spark connector to write data in online storage

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#728]
Support Spark connector for online table.

**Comment by vagetablechicken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [data import for offline and online in the task manager](https://trello.com/c/OqReyYcD/23-data-import-for-offline-and-online-in-the-task-manager)

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implementation of TaskManager](https://trello.com/c/EkxZMO7i/28-implementation-of-taskmanager)
