### ISSUE TITLE
Support SELECT INTO syntax and export data with Spark

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#731]
Support exporting data with Spark.

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implementation of TaskManager](https://trello.com/c/EkxZMO7i/28-implementation-of-taskmanager)

**Comment by vagetablechicken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [data import for offline and online in the task manager](https://trello.com/c/OqReyYcD/23-data-import-for-offline-and-online-in-the-task-manager)
