### ISSUE TITLE
Add unit test for TaskManager by submitting local classes

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#739]
We have to add more unit tests for TaskManager which does not depend on jars from `openmldb-batchjob`.

**Comment by vagetablechicken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [data import for offline and online in the task manager](https://trello.com/c/OqReyYcD/23-data-import-for-offline-and-online-in-the-task-manager)
