### ISSUE TITLE
[TBC] When executing SQL on the command line of cluster environment, the result of timestamp type is wrong

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#746]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion
When executing SQL on the command line of cluster environment, the result of timestamp type is wrong

## Expected Behavior
          - [ "aa",2,13,1590738989000 ]
          - [ "bb",21,131,1590738990000 ]
          - [ "cc",41,151,1590738992000 ]

## Current Behavior
![image](https://user-images.githubusercontent.com/18275570/142587897-ad97e73f-8ff5-4a9d-91b8-9155fda0469b.png)

## Steps to Reproduce
1. create database
create database db ;
create database db1 ;
create database db2 ;
2. create table
db1：
create table auto_ZYabMFsj(
c1 string,
c2 int,
c3 bigint,
c4 timestamp,
index(key=(c1),ts=c4))options(partitionnum=1,replicanum=1);
db2：
create table auto_fOwJtMrq(
c1 string,
c2 int,
c3 bigint,
c4 timestamp,
index(key=(c1),ts=c3))options(partitionnum=1,replicanum=1);
3. insert
insert into auto_ZYabMFsj values
('aa',2,3,1590738989000);
insert into auto_ZYabMFsj values
('bb',21,31,1590738990000);
insert into auto_ZYabMFsj values
('cc',41,51,1590738991000);

insert into auto_fOwJtMrq values
('aa',2,13,1590738989000);
insert into auto_fOwJtMrq values
('bb',21,131,1590738990000);
insert into auto_fOwJtMrq values
('cc',41,151,1590738992000);
4.  select
use db;
select db.t1.c1,db.t1.c2,db.t2.c3,db.t2.c4 from (select * from db1.auto_ZYabMFsj) as t1 last join (select * from db2.auto_fOwJtMrq) as t2 ORDER BY db.t2.c3 on db.t1.c1=db.t2.c1;

**Comment by vagetablechicken** [comment]
test on v0.7.1, no error
