### ISSUE TITLE
multiple defination error when linking on linux

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#748]
linux compile fail when setting `CMAKE_BUILD_TYPE` to Release

## Steps to Reproduce

1. cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DTESTING_ENABLE=ON
2. cmake --build build --target all

## Context (Environment)

https://github.com/4paradigm/OpenMLDB/runs/4260872394?check_suite_focus=true

**Comment by aceforeverd** [comment]
## Reason

 multiple definition found for `SQLSDKTest::DropProcedure`...

there are two libraries hold symbols from `mini_cluster_bm.cc`, one [`mini_cluster_bm_common`](https://github.com/4paradigm/OpenMLDB/blob/main/src/sdk/CMakeLists.txt#L16), another [`openmldb_sdk`](https://github.com/4paradigm/OpenMLDB/blob/main/src/CMakeLists.txt#L85).  both `mini_cluster_bm_common` and `openmldb_sdk` were marked dependency when linking cluster_bm_* targets

## How to resolve

- when compiling `openmldb_sdk`, `*_bm_*.cc` files should not included. Add a filter condition in `compile_lib` function
- function `DropProcedure` 's definition is in the header file, move to .cc file

## More improves

- add `BENCHMARK_ENABLE` option
- reorganize linking libs

**Comment by vagetablechicken** [comment]
It's ok to link both `mini_cluster_bm_common` and `openmldb_sdk`. The root cause may be that `make sql_sdk_test` is linking sql_sdk_test.o with openmldb_sdk.a.
So when `mini_cluster_bm.cc.o` wants `DropProcedure` definition, one in  openmldb_sdk.a, and another in sql_sdk_test.h(sql_sdk_test.cc includes it). It's multiple definitions.
Only O3 failed, O0/O2 is fine.
Anyway, the solution is nice.

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [compilation improvement](https://trello.com/c/VcpqXsbY/3-compilation-improvement)

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [compilation improvement](https://trello.com/c/VcpqXsbY/3-compilation-improvement)
