### ISSUE TITLE
Lack of openmld-jdbc 0.3.0-allinone and 0.3.2-allinone

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#760]
![image](https://user-images.githubusercontent.com/2715000/142827130-e0db269c-4541-45f5-88dc-5bbacdaf6ceb.png)

Now version 0.3.0-allinone and 0.3.2-allinone of openmld-jdbc  are missing.

**Comment by tobegit3hub** [comment]
Check all versions in https://search.maven.org/artifact/com.4paradigm.openmldb/openmldb-jdbc .

**Comment by aceforeverd** [comment]
TODO
- [x] deploy allinone variants in workflow

**Comment by aceforeverd** [comment]
#1056
