### ISSUE TITLE
openmldb demo image test fail on GitHub Runner

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#768]
`docker-compose up` test fail, we are unable to test demo image over Github Runner

A fail example:
https://github.com/4paradigm/OpenMLDB/runs/4299339487?check_suite_focus=true#step:5:2200

**Comment by dl239** [comment]
<img width="782" alt="WX20211125-112957@2x" src="https://user-images.githubusercontent.com/6183996/143375157-cc0acf1a-88bf-42ce-8ec9-ec7cfb1889af.png">

https://github.com/4paradigm/OpenMLDB/runs/4319276090?check_suite_focus=true#step:5:2172

**Comment by jingchen2222** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix tracking](https://trello.com/c/wEQ9HW0k/25-bugfix-tracking)

**Comment by aceforeverd** [comment]
enhancement:
- how to add non-interactive test suit just like what taxi demo described
