### ISSUE TITLE
built-in function: Support degrees() function

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#787]
**Is your feature request related to a problem? Please describe.**

degrees(value) - Converts radians to degrees.

**Examples:**
```sql
SELECT degrees(3.141592653589793);
-- output  180.0
```
reference:
https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_degrees
https://spark.apache.org/docs/2.3.0/api/sql/#degrees

**Describe the solution you'd like**

We do provide a built-in function development guide for you. 
Please check [OpenMLDB Build-In Function Develop Guide](https://github.com/4paradigm/OpenMLDB/blob/main/docs/en/built_in_function_develop_guide.md) or the [Chinese version](https://github.com/4paradigm/OpenMLDB/blob/main/docs/cn/built_in_function_develop_guide.md) for help.

Please make sure you:
- [ ] Add built-in C++ function in src/udf/udf.h and src/udf/udf.cc
- [ ] Register function to default library from function `void DefaultUdfLibrary::IniMathUdf()` in src/udf/default_udf_library.cc.
- [ ] Add related unit test in src/codegen/udf_ir_builder_test.cc
- [ ] Documenting function 

If you have any questions or concerns, please let us know. We appreciate every piece of code, comment.
**Describe alternatives you've considered**

**Additional context**

**Comment by wuxiaobai24** [comment]
I would like to help
