### ISSUE TITLE
built-in function: Support UPPER() and UCASE() function

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#789]
**Is your feature request related to a problem? Please describe.**

The SQL UPPER function converts all the characters in a string into uppercase. 
The following illustrates the syntax of the UPPER and UCASE function.

```sql
SELECT UPPER('sql upper') as str1, UCASE('sql ucase') as str2;
str1              str2
--------      ------------
SQL UPPER    SQL UCASE
(1 row)
```

**Describe the solution you'd like**

We provide a built-in function development guide for you. Please check it and develop the functions under the guide.

https://github.com/4paradigm/OpenMLDB/pull/782

Please:

- [ ] Add built-in C++ function in src/udf/udf.h and src/udf/udf.cc
- [ ] Register function to default library from function `void DefaultUdfLibrary::InitStringUdf()` in src/udf/default_udf_library.cc.
- [ ] Add related unit test in src/codegen/udf_ir_builder_test.cc
- [ ] Documenting function 

If you have any questions or concerns, please let us know. We appreciate every piece of code, comment.
**Describe alternatives you've considered**

**Additional context**

**Comment by dl239** [comment]
the sql demo is to lower case rather than upper

**Comment by jingchen2222** [comment]
> the sql demo is to lower case rather than upper

Fixed it.
