### ISSUE TITLE
[JDBC] Use url to init connection

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#81]

**Comment by vagetablechicken** [comment]
I'll support it. And it's for pulsar jdbc sink connector.
So we just need the `Driver`, `Connection` and `INSERT`, `UPDATE/DELETE/...` will be marked as unsupported.

**Comment by vagetablechicken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Apache Pulsar connector](https://trello.com/c/RFPkvEzM/42-apache-pulsar-connector)
