### ISSUE TITLE
Remove the relevant code of `NearLineTablet`

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#810]
The following file/dir need to delete or update:
* java/openmldb-nearline-tablet
* src/proto/nl_tablet.proto
* nl_tablet in src/CMakeLists.txt
* src/client/nearline_tablet_client.h
* src/client/nearline_tablet_client.cc
* nearline_tablet_ in nameserver/name_server_impl.h and nameserver/name_server_impl.cc

**Comment by tobegit3hub** [comment]
And the Java module in `java/pom.xml`.

**Comment by dl239** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [api & code cleanup](https://trello.com/c/YK7NZ65f/13-api-code-cleanup)
