### ISSUE TITLE
Delete unused commands in tablet client

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#811]
The following commands should be deleted in [StartClient](https://github.com/4paradigm/OpenMLDB/blob/main/src/cmd/openmldb.cc#L4378)
* `create` 
* `put` 
* `sput` 
* `get` 
* `scan` 
* `benchmark`  
* `benget` 
* `benput` 
* `benscan`  

**Note**: Relevant help parameter and usage should be delete in  [HandleClientHelp](https://github.com/4paradigm/OpenMLDB/blob/main/src/cmd/openmldb.cc#L3266)

**Comment by nautaa** [comment]
I would like to help

**Comment by dl239** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [api & code cleanup](https://trello.com/c/YK7NZ65f/13-api-code-cleanup)
