### ISSUE TITLE
built-in function: Support `char_length()` and `character_length()` function

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#818]
**Is your feature request related to a problem? Please describe.**

### char_length(expr) 
Returns the character length of string data or number of bytes of binary data. The length of string data includes the trailing spaces. The length of binary data includes binary zeros.

### Examples:
```sql
> SELECT char_length('Spark SQL ');
 10
> SELECT CHAR_LENGTH('Spark SQL ');
 10
> SELECT character_length('Spark SQL ');
 10
> SELECT CHARACTER_LENGTH('Spark SQL ');
 10
```

### Reference:
https://spark.apache.org/docs/2.3.0/api/sql/#char_length

**Describe the solution you'd like**

We do provide a built-in function development guide for you. 
Please check [OpenMLDB Build-In Function Develop Guide](https://github.com/4paradigm/OpenMLDB/blob/main/docs/en/built_in_function_develop_guide.md) or the [Chinese version](https://github.com/4paradigm/OpenMLDB/blob/main/docs/cn/built_in_function_develop_guide.md) for help.

Please make sure you:
- [ ] Add built-in C++ function in src/udf/udf.h and src/udf/udf.cc
- [ ] Register function to default library from function `void DefaultUdfLibrary::IniStringUdf()` in src/udf/default_udf_library.cc.
- [ ] Add related unit test in src/codegen/udf_ir_builder_test.cc
- [ ] Documenting function 

**Describe alternatives you've considered**

**Additional context**

**Comment by Ivyee17** [comment]
I want to help this, plz assign it to me. WeOpen Star. @lumianph
