### ISSUE TITLE
editing and translation for the APIServer doc

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#826]
This issue consists of two tasks about the documentation

- [ ] Proofreading the Chinese version of APIServer doc `docs/cn/apiserver.md`
- [ ] Translating this Chinese version to English, named as `docs/en/apiserver.md`

**Comment by mahengyang** [comment]
I would like to help

**Comment by lumianph** [comment]
> I would like to help

hello @mahengyang , how is your progress now? you may let us know if you need any help 😄

**Comment by mahengyang** [comment]
sorry for late, this is my PR
#885
