### ISSUE TITLE
When inserting multiple pieces of data, there is an error prompt in the log

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#845]
When inserting multiple pieces of data, the log displays an error message, but the insertion is successful

1. create
CREATE TABLE IF NOT EXISTS behaviourTable(
	itemId string,
	reqId string,
	tags string,
	instanceKey string,
	eventTime timestamp,
	rank string,
	mcuid string,
	ip string,
	browser string,
	browser_version string,
	platform string,
	query string,
	sort_rule string,
	_i_rank string
);
2. insert
insert into behaviourTable values ('23384','1cbnZ2e7dc2b34b+6b84','h5_001,h','1cbnZ2e7dc2b34b+6b84^23384',1589518408000,'5','0950ae353c2ed610ffbeb0871480f5ea','219.130.217','UCBrowser','10.7.11.672','iPhone','丰田卡罗拉','def','a'),('22530','2bgyZ2e7dc2b64f+350f','h5_000,h','2bgyZ2e7dc2b64f+350f^22530',1589518408000,'6','a2bd5655107164801d5f4ceccc57fcaa','114.111.166','Google Chrome','33.0.0.0','Android','沃尔沃','def','8'),('17976','38j9Z2e7dc2b6d7+7486','pc_001,h','38j9Z2e7dc2b6d7+7486^17976',1589518408000,'1','38j9Z2e7dc2b6d7+7486+1','51.255.65','unknown','unknownVersion','UnknownPlatform','英菲尼迪','def','f'),('19776','38j9Z2e7dc2b6d7+7486','pc_001,h','38j9Z2e7dc2b6d7+7486^19776',1589518408000,'1','38j9Z2e7dc2b6d7+7486+1','51.255.65','unknown','unknownVersion','UnknownPlatform','英菲尼迪','def','6'),('21414','iyzsZ2e7dc2b5ce+5ada','h5_001,h','iyzsZ2e7dc2b5ce+5ada^21414',1589518408000,'3','956a3751f0c1f2bafcfef0d0103669ad','180.153.206','QQMobileBrowser','5.0','Android','','def','4'),('21414','tudoZ2e7dc2b643+4ee','pc_000,h','tudoZ2e7dc2b643+4ee^21414',1589518408000,'6','0981139481e004925c4a769721378cd4','113.195.97','LBBROWSER','unknownVersion','windows','','def','4'),('18638','1cbnZ2e7dc2c1de+6b6f','pc_001,h','1cbnZ2e7dc2c1de+6b6f^18638',1589518411000,'12','1cbnZ2e7dc2c1de+6b6f+12','101.226.169','Google Chrome','21.0.1180.89','windows','大众','def','a'),('17722','1cbnZ2e7dc2b34b+6b84','h5_001,h','1cbnZ2e7dc2b34b+6b84^17722',1589518408000,'5','0950ae353c2ed610ffbeb0871480f5ea','219.130.217','UCBrowser','10.7.11.672','iPhone','丰田卡罗拉','def','7'),('18723','38j9Z2e7dc2b6d7+7486','pc_001,h','38j9Z2e7dc2b6d7+7486^18723',1589518408000,'1','38j9Z2e7dc2b6d7+7486+1','51.255.65','unknown','unknownVersion','UnknownPlatform','英菲尼迪','def','e'),('15966','iyzsZ2e7dc2b5ce+5ada','h5_001,h','iyzsZ2e7dc2b5ce+5ada^15966',1589518408000,'3','956a3751f0c1f2bafcfef0d0103669ad','180.153.206','QQMobileBrowser','5.0','Android','','def','9');

## Context (Environment)
Using java SDK
## Error Info
![wecom-temp-3a875a1919b47531084e79800da101b6](https://user-images.githubusercontent.com/18275570/144815865-26ec31d4-733d-45da-828d-9b374adf5714.png)

**Comment by jingchen2222** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix tracking](https://trello.com/c/wEQ9HW0k/25-bugfix-tracking)

**Comment by dl239** [comment]
refer https://github.com/4paradigm/OpenMLDB/issues/954
