### ISSUE TITLE
like udf: address boundry error when executing `select like_match(___, string(NULL))`

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#867]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

this is a known issue from #841 

## Current Behavior

`select like_match(col2, 'm_ke', string(NULL)) as col from t1`

result
```log
terminated by signal SIGSEGV (Address boundary error)
```

only happens on linux, macOS passed though

## Steps to Reproduce

1.
2.
3.
4.

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [sql support for LIKE](https://trello.com/c/ZgAcOGCw/26-sql-support-for-like)

**Comment by jingchen2222** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix tracking](https://trello.com/c/wEQ9HW0k/25-bugfix-tracking)
