### ISSUE TITLE
automatically copy the utility scripts to the bin dir

### ISSUE THREAD

**Issue by lumianph** [4paradigm/OpenMLDB#868]
at the end of compilation, the utility scripts (https://github.com/4paradigm/OpenMLDB/tree/main/release/bin) should be automatically copied to the install dir (by default the `bin` dir)

**Comment by jingchen2222** [comment]
> at the end of compilation, the utility scripts (https://github.com/4paradigm/OpenMLDB/tree/main/release/bin) should be automatically copied to the install dir (by default the `bin` dir)

We can use install openmldb bin into release/bin during make install

**Comment by aceforeverd** [comment]
> > at the end of compilation, the utility scripts (https://github.com/4paradigm/OpenMLDB/tree/main/release/bin) should be automatically copied to the install dir (by default the `bin` dir)
> 
> We can use install openmldb bin into release/bin during make install

Right. But user may specify install dir by `-DCMAKE_INSTALL_PREFIX`, I'll copy the built binary and script together into install dir. 
Also, I'd like change the name of `release` directory 😕

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [minor bugfix tracking](https://trello.com/c/wEQ9HW0k/25-minor-bugfix-tracking)
