### ISSUE TITLE
Support standard Python SQLAlchemy API and throw exceptions for unsupported methods

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#888]
Now we support some basic Python SQLAlchemy APIs but it is not documented. We should add documents for supported APIs and throw exception or print errors for unsupported methods.

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make Python SDK available for users](https://trello.com/c/Mfqg2o9I/33-make-python-sdk-available-for-users)

**Comment by HuilinWu2** [comment]
Throw exceptions for unsupported methods: (still testing and collecting cases)
