### ISSUE TITLE
Add docs for OpenMLDB Python SDK

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#890]
* Add the docs for users about usage
* Add the docs for developers

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make Python SDK available for users](https://trello.com/c/Mfqg2o9I/33-make-python-sdk-available-for-users)

**Comment by HuilinWu2** [comment]
Common users: Install and use examples of Python SDK (should include more details)
Developer: example of build&install of Openmldb and Python SDK setup in docker environment

**Comment by tobegit3hub** [comment]
Resolved.
