### ISSUE TITLE
ci: java sdk deploy on MacOS failed

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#897]
![image](https://user-images.githubusercontent.com/24697960/145980312-cfe5cc3f-1a20-474e-ba6c-86606ec03340.png)
https://github.com/4paradigm/OpenMLDB/runs/4508246684?check_suite_focus=true

We can find 0.4.0-SNAPSHOT on oss, why error?
P.S. java sdk deployment will set version to xxx-macos[-snapshot], so the openmldb-common module will be add 'macos'. So we will deploy the macos version of openmldb-common, which is needless.

If we want to use the local openmdb-common, we should package openmldb-common without 'macos' tag.

**Comment by aceforeverd** [comment]
do not specify dependency with SNAPSHOT version, snapshot repository is not configured.
https://github.com/4paradigm/OpenMLDB/blob/main/java/openmldb-taskmanager/pom.xml#L25

**Comment by aceforeverd** [comment]
> do not specify dependency with SNAPSHOT version, snapshot repository is not configured.
> https://github.com/4paradigm/OpenMLDB/blob/main/java/openmldb-taskmanager/pom.xml#L25

no,  strange. What it can't find the `openmldb-common` submodule

**Comment by aceforeverd** [comment]
Might understand, OpenMLDB-common dependency should write as 
`<version>${project.parent.version}</version>`

variant version really a pain

**Comment by vagetablechicken** [comment]
If replace `openmldb-common.version` with `project.parent.version`, it will be `0.4.0-macos-SNAPSHOT`. So we deploy `openmldb-common:0.4.0-macos-SNAPSHOT`? Is it right? I think openmldb-common should be just one package.

**Comment by aceforeverd** [comment]
> If replace `openmldb-common.version` with `project.parent.version`, it will be `0.4.0-macos-SNAPSHOT`. So we deploy `openmldb-common:0.4.0-macos-SNAPSHOT`? Is it right? I think openmldb-common should be just one package.

if `openmldb-parent` is, it should be.
and I'm afraid problem like #243 arise more

**Comment by aceforeverd** [comment]
resolved in #919
