### ISSUE TITLE
There is a bug in the like expression

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#898]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

c1 like 'a%b%'

a_b -> false

## Expected Behavior
a_b -> true

## Current Behavior
a_b -> false

**Comment by jingchen2222** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix tracking](https://trello.com/c/wEQ9HW0k/25-bugfix-tracking)

**Comment by aceforeverd** [comment]
confirmed
