### ISSUE TITLE
SQL syntax support doc

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#904]
**Is your feature request related to a problem? Please describe.**
Currently there are no available doc describing what SQL syntax are supported by openmldb.

For example, time windows `FOLLOWING` is not supported, but it is not known to the end users.

**Describe the solution you'd like**
SQL syntax support doc

**Comment by jingchen2222** [comment]
@zhanghaohit we are working on it. https://github.com/4paradigm/HybridSQL-docs/pull/41
I will add more descriptions to clarify the usage of time windows. Thanks for your suggestions.

**Comment by tobegit3hub** [comment]
Resolved.
