### ISSUE TITLE
CPP UNIT: ZkClientTest.ZkNodeChange possible to fail

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#916]
two kind failed test:
- ZkClientTest.ZkNodeChange
- TableTest.AbsOrLatSetGet

failed runner: https://github.com/4paradigm/OpenMLDB/runs/4556094927?check_suite_focus=true#step:8:958

**Comment by aceforeverd** [comment]
another failed test

`TableTest.AbsOrLatSetGet`
https://github.com/4paradigm/OpenMLDB/runs/4557906365?check_suite_focus=true#step:8:1085


```log
I1217 07:00:46.102149  5953 mem_table.cc:315] gc segment[0][5] done consumed 0 for table table1 tid 1 pid 0
1074
I1217 07:00:46.102156  5953 mem_table.cc:315] gc segment[0][6] done consumed 0 for table table1 tid 1 pid 0
1075
I1217 07:00:46.102164  5953 mem_table.cc:315] gc segment[0][7] done consumed 0 for table table1 tid 1 pid 0
1076
I1217 07:00:46.102172  5953 mem_table.cc:324] gc finished, gc_idx_cnt 4, gc_record_cnt 4 consumed 0 ms for table table1 tid 1 pid 0
1077
I1217 07:00:46.102190  5953 mem_table.cc:81] drop memtable. tid 1 pid 0
1078
[       OK ] TableTest.GcAbsAndLat (0 ms)
1079
[----------] 22 tests from TableTest (309 ms total)
1080

1081
[----------] Global test environment tear-down
1082
[==========] 22 tests from 1 test suite ran. (310 ms total)
1083
[  PASSED  ] 21 tests.
1084
[  FAILED  ] 1 test, listed below:
```

**Comment by aceforeverd** [comment]
for `ZkNodeChange` test, it test a async interface `ZkClient::WatchItem`. We need more runtime log to inspect @vagetablechicken

**Comment by vagetablechicken** [comment]
> for `ZkNodeChange` test, it test a async interface `ZkClient::WatchItem`. We need more runtime log to inspect @vagetablechicken

Yes, so we need:

- sync get after sync set value, to make sure value is corrent in zk storage
- more info about watcher, is the watcher registered?(This needs more coding)

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix tracking](https://trello.com/c/wEQ9HW0k/25-bugfix-tracking)

**Comment by aceforeverd** [comment]
https://github.com/4paradigm/OpenMLDB/runs/4616344584?check_suite_focus=true#step:9:1485

the `SQLSDKParameterizedQuery/SQLSDKQueryTest.SqlSdkBatchTest/3` will fail
