### ISSUE TITLE
thirdparty: brpc is built by newer MacOS version, endless log output on MacOS 10.15

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#954]
with https://github.com/4paradigm/hybridsql-asserts/releases/download/v0.4.2/thirdparty-2021-12-10-darwin-i386.tar.gz, actually we can focus on libbrpc in thridparty.
error log is
```
 W1223 11:01:36.455538 214974464 default_variables.cpp:452] Fail to proc_pid_rusage: Invalid argument [22]
```
This pre-built brpc works fine on MacOS 11.x, tested by keyu.

My test env is 10.15, so ld will print warning:
```
ld: warning: object file (/Users/ark/Code/OpenMLDB2/.deps/usr/lib/libre2.a(re2.o)) was built for newer macOS version (11.1) than being linked (10.15)
```

P.S.  
maybe thirdparty-2021-12-08-darwin-i386.tar.gz will occur endless error log
```
Fail to sscanf: Undefined error: 0 [0]
```

thirdparty-2021-08-03-darwin-x86_64.tar.gz is fine with MacOS 10.15, tested by me and chenjing.

If we run java client test(must in IDEA or other IDE, openmldb-batch TestLoadDataPlan can but maybe not the only one) which built from v0.4.2/thirdparty-2021-12-10-darwin-i386.tar.gz, we can get all two errors. It'll print:
```
W1224 12:10:23.296401 105648128 default_variables.cpp:117] Fail to sscanf: Undefined error: 0 [0]
W1224 12:10:23.313041 105648128 default_variables.cpp:452] Fail to proc_pid_rusage: Invalid argument [22]
```

`proc_pid_rusage` error can be fixed by building thirdparty on sdk 10.15(ci select lower version Xcode). Although 
`int proc_pid_rusage(int pid, int flavor, rusage_info_t *buffer) __OSX_AVAILABLE_STARTING(__MAC_10_9, __IPHONE_7_0);
`, 11.x lib can't run well on 10.15. We should make the pre-built packages to use the lowest SDK version.

`sscanf` error is caused by "ps -o flags", it's hex(only mac), but sscanf read it by %u.
But macos 12 `ps` changed? still in hex.

So we should:

- [x] https://github.com/4paradigm/incubator-brpc/pull/4 fix brpc bug
- [x] modify third-party FetchBrpc.cmake https://github.com/4paradigm/OpenMLDB/tree/build/thirdparty-0.4.x
- [x] select xcode in thirdparty ci, and update openmldb commit https://github.com/4paradigm/hybridsql-asserts/runs/4640726930?check_suite_focus=true
- [x] release new thirdparty pkg https://github.com/4paradigm/hybridsql-asserts/releases/tag/v0.4.3

**Comment by tobegit3hub** [comment]
It is the issue of brpc, refer to https://github.com/apache/incubator-brpc/issues/1106 .

We need to re-compile brpc to fix that.

**Comment by vagetablechicken** [comment]
> It is the issue of brpc, refer to [apache/incubator-brpc#1106](https://github.com/apache/incubator-brpc/issues/1106) .
> 
> We need to re-compile brpc to fix that.

Yes, similar, but a little different. thirdparty-2021-12-10-darwin-i386.tar.gz is the function `proc_pid_rusage`. And https://github.com/apache/incubator-brpc/issues/1106 fixed it with src code modified.
I'll check if pre-build in MacOSX10.15 works.

**Comment by vagetablechicken** [comment]
- [x] https://github.com/vagetablechicken/hybridsql-asserts/actions/runs/1614010927
- [x] test it https://github.com/vagetablechicken/hybridsql-asserts/releases/tag/v0.4.3
OS12 still has  sscanf warning logs, need to modify the code. No proc_pid_rusage log.
If we `man ps`, it shows:
`flags      the process flags, in hexadecimal (alias f)`
The `flags` is in hex on OS10.15/11.1/12.x, so I'll change %u to %x, it'll work on all common version of MacOS.
https://github.com/4paradigm/incubator-brpc/pull/4
