### ISSUE TITLE
segmentation fault when trying demo under the standalone mode

### ISSUE THREAD

**Issue by yabg-shuai666** [4paradigm/OpenMLDB#956]
<img width="687" alt="image" src="https://user-images.githubusercontent.com/59086688/147231904-3f1c9150-9b34-4a43-a21b-b0f4974df4eb.png">
A segmentation fault occurs during the operation of Demo with The Standalone Mode ../openmldb/bin/openmldb --host 127.0.0.1 --port 6527, which may be caused by insufficient memory of the machine.

**Comment by lumianph** [comment]
what is your machine's DRAM capacity?

**Comment by dl239** [comment]
@yabg-shuai666 Could you post the backtrace info ?

**Comment by tobegit3hub** [comment]
@yabg-shuai666 you could check the memory of docker container first. Increasing the memory to 4g or larger may help.

**Comment by yabg-shuai666** [comment]
> 



> what is your machine's DRAM capacity?
<img width="410" alt="wecom-temp-05c27d3a6f42fefac90784363bcaa92e" src="https://user-images.githubusercontent.com/59086688/147311256-eea18990-72d2-4e3d-9c4e-7347c836d75c.png">

Now the memory of docker is 2GB, I will adjust it to 4GB and test again。

**Comment by yabg-shuai666** [comment]
> @yabg-shuai666 you could check the memory of docker container first. Increasing the memory to 4g or larger may help.
Ok I understand.

**Comment by yabg-shuai666** [comment]
The version of mac in the test environment is 10.15.7, and the version of Docker is 1.12.3 (cpus:3 Memory:8.0GB)

**Comment by zhanghaohit** [comment]
> The version of mac in the test environment is 10.15.7, and the version of Docker is 1.12.3 (cpus:3 Memory:8.0GB)

So 8.0 GB memory still cause the "segmentation fault"?

**Comment by yabg-shuai666** [comment]
> > The version of mac in the test environment is 10.15.7, and the version of Docker is 1.12.3 (cpus:3 Memory:8.0GB)
> 
> So 8.0 GB memory still cause the "segmentation fault"?

yes,upgrade the MAC system to 12.1 and the docker version to 4.3.2 (cpus:3 Memory:2.0GB), and the problem can be solved. The problem may be caused by the low docker version.

**Comment by yabg-shuai666** [comment]
> > @yabg-shuai666 you could check the memory of docker container first. Increasing the memory to 4g or larger may help.
> > Ok I understand.

Upgrade the MAC system to 12.1 and the docker version to 4.3.2 (cpus:3 Memory:2.0GB), and the problem can be solved. The problem may be caused by the low docker version!

**Comment by lumianph** [comment]
@yabg-shuai666 can you help confirm that it is caused by the low version of docker? If so, we may add this limitation into our docker document @zhanghaohit

**Comment by yabg-shuai666** [comment]
> @yabg-shuai666 can you help confirm that it is caused by the low version of docker? If so, we may add this limitation into our docker document @zhanghaohit

Okay, I will confirm which version of docker can support the startup of OpenMLDB CLI.

**Comment by yabg-shuai666** [comment]
The recommended docker version in stand-alone mode is 18.03.0 and above, otherwise segmentation fault will occur.

**Comment by yabg-shuai666** [comment]
The recommended docker version in stand-alone mode is 18.03 and above, otherwise a "segmentation fault" will appear when the OpenMLDB CLI is started.

**Comment by jingchen2222** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix tracking](https://trello.com/c/wEQ9HW0k/25-bugfix-tracking)

**Comment by yabg-shuai666** [comment]
> ![](https://camo.githubusercontent.com/208d50cabd9d101500fe5dd548265dcfa00e017e397395692a173e7116c1094a/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [bugfix tracking](https://trello.com/c/wEQ9HW0k/25-bugfix-tracking)

ok！
