### ISSUE TITLE
openmldb-sqlalchemy in pypi does not support MacOS

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#957]
Maybe Do not allow to install in MacOS by setting supported OS in `setup.py`.

**Comment by HuilinWu2** [comment]
[PEP 496](https://www.python.org/dev/peps/pep-0496/) & [PEP 508](https://www.python.org/dev/peps/pep-0508/#environment-markers) shows examples of dependency specification for Python packages installation.

Commonly, there are two ways to manage that in `setup.py`:
1) `extras_require`
extras_require = {
':sys_platform == "linux"': ['sqlalchemy < 1.4.0']
}
2) `install_requires`
install_requires = [
'sqlalchemy < 1.4.0; platform_system == "Linux"'
],

However, these operations only focus on the dependent packages
now I am trying setting a global os limitation.

**Comment by tobegit3hub** [comment]
It seems that PEP-496 and PEP-508 describe the way to package dependencies for different operating system but not the way to build the package for different OS.

You may find the way build the packages for different OS and arch just like what `numpy` did.

![image](https://user-images.githubusercontent.com/2715000/147339505-6cde2faa-9543-4be3-8deb-6360d5bd03cc.png)

**Comment by HuilinWu2** [comment]
> It seems that PEP-496 and PEP-508 describe the way to package dependencies for different operating system but not the way to build the package for different OS.
> 
> You may find the way build the packages for different OS and arch just like what `numpy` did.
> 
> ![image](https://user-images.githubusercontent.com/2715000/147339505-6cde2faa-9543-4be3-8deb-6360d5bd03cc.png)

Thanks for the advices :)

**Comment by HuilinWu2** [comment]
For example, if we've built a Linux specific wheel only, the wheel file will not be downloaded by users on Mac/Windows OS.
i.e. PIP will first check whether there is a wheel file that is compatible with current OS, then follows the [PEP 425 Use recommendations](https://www.python.org/dev/peps/pep-0425/#id1);
![image](https://user-images.githubusercontent.com/68987242/147463251-c32c66da-2e98-4099-a3ab-9d97e0661d31.png)

Next: 
build custom packages for testing mentioned above

**Comment by HuilinWu2** [comment]
Generally, standard wheel file is named as follows:
`<packagename>-<version>-<python tag>-<abi tag>-<platform tag>.whl`

When building wheel file, we can add additional options:
`python setup.py bdist_wheel --python-tag py3 --plat-name macosx_10_15_x86_64/manylinux1_x86_64`
then we will get the wheel file with `<package name>-<version>-py3-none-<specific platform>.whl`

Note: default name without options is: `xxx-xxx-py3-none-any.whl`


When users try to pip install the package, it would automatically install the package that is compatible with the current OS.

* if there is no `whl` file that matches current OS, it will raise error 
`ERROR: Could not find a version that satisfies the requirement xxxxx(package) (from versions: none)`
`ERROR: No matching distribution found for xxxxxx(package)`

* if there are several files that meets the platform requirements, then follows the[ PEP 425(Mac&Windows)](https://www.python.org/dev/peps/pep-0425/).For detailed platform compatibility tags, please refer to [Link](https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/)
