### ISSUE TITLE
Run standard sqlalchemy tests for openmldb-sqlalchemy

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#959]
Run the tests from `sqlalchemy`.

**Comment by tobegit3hub** [comment]
Refer to https://github.com/zzzeek/sqlalchemy/blob/master/README.dialects.rst .

**Comment by HuilinWu2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve functionality of Python SDK](https://trello.com/c/xlXZPfTf/20-improve-functionality-of-python-sdk)

**Comment by tobegit3hub** [comment]
Done.
