### ISSUE TITLE
delete job job_id should prompt an error message

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#976]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion
delete job job_id should prompt an error message

## Expected Behavior
should prompt an error message

## Current Behavior
No hint

**Comment by jingchen2222** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix tracking](https://trello.com/c/wEQ9HW0k/25-bugfix-tracking)

**Comment by tobegit3hub** [comment]
Currently the delete command is accepted but not supported.

![image](https://user-images.githubusercontent.com/2715000/148156441-c0e40320-4af3-4f0f-ba69-0291c64c316b.png)

**Comment by tobegit3hub** [comment]
Fixed and print the error message now.

![image](https://user-images.githubusercontent.com/2715000/148157117-5eb669a9-1580-4449-a535-e6ce1a2c2bc1.png)
