### ISSUE TITLE
Support create, drop, desc db.table statement

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#977]
**Is your feature request related to a problem? Please describe.**

Users have to `USE db` before they perform DDL statement or DML statement.
In this issue, we are going to support execute DDL or DML statement without specifying default database.

1. support create db.table
```
CREATE db1.t1 (col1 int, col2 timestamp);
```

```
CREATE INDEX index1 (...) on db1.t1;
```
2. support cmd like desc, show ....
```sql
DESC db1.t1;
```

3. 
```sql
INSERT INTO db1.t1 values(1, 123456789);
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-chenjing](https://trello.com/c/J5u9EIk4/17-bugfix-chenjing)
