### ISSUE TITLE
When lang = zh_CN.UTF-8, the Java SDK executes an error

### ISSUE THREAD

**Issue by wuyou10206** [4paradigm/OpenMLDB#981]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion
When lang = zh_ CN. When UTF-8, the Java SDK executes an error

## Expected Behavior
no error

## Current Behavior
JVM dump

**Comment by tobegit3hub** [comment]
Fail to load the openmldb jsdk so because of the error "Fail to define ESTOP(-20) which is already defined as `未知的错误 -20', abort.".

<img width="1073" alt="wecom-temp-780ccbb9995341fbe16f06de15145a1c" src="https://user-images.githubusercontent.com/2715000/147653400-6fbb3be5-feca-4a1c-8f87-b7f0d1227494.png">

**Comment by vagetablechicken** [comment]
when brpc is registering errno, it will get system errno info by `strerror_r`, and only treat the infos as english. And it's only on linux, macos won't check the errno info. So we should use `LANG` of english(en_US.UTF-8 is the best?) to avoid this bug.

**Comment by vagetablechicken** [comment]
I'll fix this bug in brpc.

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-P1](https://trello.com/c/yMBAuhYq/22-bugfix-p1)

**Comment by tobegit3hub** [comment]
Workaround method to avoid this by setting charset when submitting Spark jobs.

```
launcher.setConf("spark.yarn.appMasterEnv.LANG", "en_US.UTF-8")
launcher.setConf("spark.yarn.appMasterEnv.LC_ALL", "en_US.UTF-8")
launcher.setConf("spark.yarn.executorEnv.LANG", "en_US.UTF-8")
launcher.setConf("spark.yarn.executorEnv.LC_ALL", "en_US.UTF-8")
```

**Comment by vagetablechicken** [comment]
https://github.com/4paradigm/incubator-brpc/pull/5
